/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.api.resources.diagrams.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.icepanel.api.core.ObjectMappers;
import com.icepanel.api.types.DiagramThumbnail;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DiagramsListThumbnailsResponse.Builder.class)
public final class DiagramsListThumbnailsResponse {
    private final Map<String, DiagramThumbnail> thumbnails;

    private final Map<String, Object> additionalProperties;

    private DiagramsListThumbnailsResponse(
            Map<String, DiagramThumbnail> thumbnails, Map<String, Object> additionalProperties) {
        this.thumbnails = thumbnails;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("thumbnails")
    public Map<String, DiagramThumbnail> getThumbnails() {
        return thumbnails;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DiagramsListThumbnailsResponse && equalTo((DiagramsListThumbnailsResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DiagramsListThumbnailsResponse other) {
        return thumbnails.equals(other.thumbnails);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.thumbnails);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Map<String, DiagramThumbnail> thumbnails = new LinkedHashMap<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(DiagramsListThumbnailsResponse other) {
            thumbnails(other.getThumbnails());
            return this;
        }

        @JsonSetter(value = "thumbnails", nulls = Nulls.SKIP)
        public Builder thumbnails(Map<String, DiagramThumbnail> thumbnails) {
            this.thumbnails.clear();
            if (thumbnails != null) {
                this.thumbnails.putAll(thumbnails);
            }
            return this;
        }

        public Builder putAllThumbnails(Map<String, DiagramThumbnail> thumbnails) {
            if (thumbnails != null) {
                this.thumbnails.putAll(thumbnails);
            }
            return this;
        }

        public Builder thumbnails(String key, DiagramThumbnail value) {
            this.thumbnails.put(key, value);
            return this;
        }

        public DiagramsListThumbnailsResponse build() {
            return new DiagramsListThumbnailsResponse(thumbnails, additionalProperties);
        }
    }
}
