/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.model.connections;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.icepanel.core.ClientOptions;
import com.icepanel.core.IcePanelClientApiException;
import com.icepanel.core.IcePanelClientException;
import com.icepanel.core.IcePanelClientHttpResponse;
import com.icepanel.core.ObjectMappers;
import com.icepanel.core.RequestOptions;
import com.icepanel.errors.InternalServerError;
import com.icepanel.errors.NotFoundError;
import com.icepanel.errors.UnauthorizedError;
import com.icepanel.errors.UnprocessableEntityError;
import com.icepanel.model.connections.types.ModelConnectionsExportCsvRequest;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawExportClient {
    protected final ClientOptions clientOptions;

    public RawExportClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    public IcePanelClientHttpResponse<String> csv(ModelConnectionsExportCsvRequest request) {
        return csv(request, null);
    }

    public IcePanelClientHttpResponse<String> csv(
            ModelConnectionsExportCsvRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("landscapes")
                .addPathSegment(request.getLandscapeId())
                .addPathSegments("versions")
                .addPathSegment(request.getVersionId())
                .addPathSegments("model/connections/export")
                .addPathSegments("csv");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new IcePanelClientHttpResponse<>(responseBodyString, response);
            }
            try {
                switch (response.code()) {
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 422:
                        throw new UnprocessableEntityError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new IcePanelClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new IcePanelClientException("Network error executing HTTP request", e);
        }
    }
}
