/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel;

import com.icepanel.core.ClientOptions;
import com.icepanel.core.RequestOptions;
import com.icepanel.core.Suppliers;
import com.icepanel.tags.AsyncGroupsClient;
import com.icepanel.types.TagCreateRequest;
import com.icepanel.types.TagDeleteRequest;
import com.icepanel.types.TagFindRequest;
import com.icepanel.types.TagUpdateRequest;
import com.icepanel.types.TagUpsertRequest;
import com.icepanel.types.TagsCreateResponse;
import com.icepanel.types.TagsDeleteResponse;
import com.icepanel.types.TagsGetResponse;
import com.icepanel.types.TagsListRequest;
import com.icepanel.types.TagsListResponse;
import com.icepanel.types.TagsUpdateResponse;
import com.icepanel.types.TagsUpsertResponse;
import java.util.concurrent.CompletableFuture;
import java.util.function.Supplier;

public class AsyncTagsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawTagsClient rawClient;

    protected final Supplier<AsyncGroupsClient> groupsClient;

    public AsyncTagsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawTagsClient(clientOptions);
        this.groupsClient = Suppliers.memoize(() -> new AsyncGroupsClient(clientOptions));
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawTagsClient withRawResponse() {
        return this.rawClient;
    }

    public CompletableFuture<TagsListResponse> list(TagsListRequest request) {
        return this.rawClient.list(request).thenApply(response -> response.body());
    }

    public CompletableFuture<TagsListResponse> list(TagsListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<TagsCreateResponse> create(TagCreateRequest request) {
        return this.rawClient.create(request).thenApply(response -> response.body());
    }

    public CompletableFuture<TagsCreateResponse> create(TagCreateRequest request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<TagsGetResponse> get(TagFindRequest request) {
        return this.rawClient.get(request).thenApply(response -> response.body());
    }

    public CompletableFuture<TagsGetResponse> get(TagFindRequest request, RequestOptions requestOptions) {
        return this.rawClient.get(request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<TagsUpsertResponse> upsert(TagUpsertRequest request) {
        return this.rawClient.upsert(request).thenApply(response -> response.body());
    }

    public CompletableFuture<TagsUpsertResponse> upsert(TagUpsertRequest request, RequestOptions requestOptions) {
        return this.rawClient.upsert(request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<TagsDeleteResponse> delete(TagDeleteRequest request) {
        return this.rawClient.delete(request).thenApply(response -> response.body());
    }

    public CompletableFuture<TagsDeleteResponse> delete(TagDeleteRequest request, RequestOptions requestOptions) {
        return this.rawClient.delete(request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<TagsUpdateResponse> update(TagUpdateRequest request) {
        return this.rawClient.update(request).thenApply(response -> response.body());
    }

    public CompletableFuture<TagsUpdateResponse> update(TagUpdateRequest request, RequestOptions requestOptions) {
        return this.rawClient.update(request, requestOptions).thenApply(response -> response.body());
    }

    public AsyncGroupsClient groups() {
        return this.groupsClient.get();
    }
}
