/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.api.resources.catalog;

import com.icepanel.api.core.ClientOptions;
import com.icepanel.api.core.Suppliers;
import com.icepanel.api.resources.catalog.technologies.TechnologiesClient;
import java.util.function.Supplier;

public class CatalogClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<TechnologiesClient> technologiesClient;

    public CatalogClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.technologiesClient = Suppliers.memoize(() -> new TechnologiesClient(clientOptions));
    }

    public TechnologiesClient technologies() {
        return this.technologiesClient.get();
    }
}
