/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.api.resources.landscapes.logs.stats;

import com.icepanel.api.core.ClientOptions;
import com.icepanel.api.core.RequestOptions;
import com.icepanel.api.resources.landscapes.logs.stats.requests.ActionLogStatsByEntityRequest;
import com.icepanel.api.resources.landscapes.logs.stats.requests.ActionLogStatsByTypeRequest;
import com.icepanel.api.types.ActionLogStatsListByEntity;
import com.icepanel.api.types.ActionLogStatsListByType;

public class StatsClient {
    protected final ClientOptions clientOptions;

    private final RawStatsClient rawClient;

    public StatsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawStatsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawStatsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * List total counts of actions for each action type (e.g. diagram-content-update, model-object-create)
     */
    public ActionLogStatsListByType byType(String landscapeId) {
        return this.rawClient.byType(landscapeId).body();
    }

    /**
     * List total counts of actions for each action type (e.g. diagram-content-update, model-object-create)
     */
    public ActionLogStatsListByType byType(String landscapeId, ActionLogStatsByTypeRequest request) {
        return this.rawClient.byType(landscapeId, request).body();
    }

    /**
     * List total counts of actions for each action type (e.g. diagram-content-update, model-object-create)
     */
    public ActionLogStatsListByType byType(
            String landscapeId, ActionLogStatsByTypeRequest request, RequestOptions requestOptions) {
        return this.rawClient.byType(landscapeId, request, requestOptions).body();
    }

    /**
     * List total counts of actions for each entity identifier
     */
    public ActionLogStatsListByEntity byEntity(String landscapeId) {
        return this.rawClient.byEntity(landscapeId).body();
    }

    /**
     * List total counts of actions for each entity identifier
     */
    public ActionLogStatsListByEntity byEntity(String landscapeId, ActionLogStatsByEntityRequest request) {
        return this.rawClient.byEntity(landscapeId, request).body();
    }

    /**
     * List total counts of actions for each entity identifier
     */
    public ActionLogStatsListByEntity byEntity(
            String landscapeId, ActionLogStatsByEntityRequest request, RequestOptions requestOptions) {
        return this.rawClient.byEntity(landscapeId, request, requestOptions).body();
    }
}
