/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.organizations.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.icepanel.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = OrganizationLogFindRequest.Builder.class)
public final class OrganizationLogFindRequest {
    private final String organizationId;

    private final String organizationLogId;

    private final Map<String, Object> additionalProperties;

    private OrganizationLogFindRequest(
            String organizationId, String organizationLogId, Map<String, Object> additionalProperties) {
        this.organizationId = organizationId;
        this.organizationLogId = organizationLogId;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("organizationId")
    public String getOrganizationId() {
        return organizationId;
    }

    @JsonProperty("organizationLogId")
    public String getOrganizationLogId() {
        return organizationLogId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof OrganizationLogFindRequest && equalTo((OrganizationLogFindRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(OrganizationLogFindRequest other) {
        return organizationId.equals(other.organizationId) && organizationLogId.equals(other.organizationLogId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.organizationId, this.organizationLogId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static OrganizationIdStage builder() {
        return new Builder();
    }

    public interface OrganizationIdStage {
        OrganizationLogIdStage organizationId(@NotNull String organizationId);

        Builder from(OrganizationLogFindRequest other);
    }

    public interface OrganizationLogIdStage {
        _FinalStage organizationLogId(@NotNull String organizationLogId);
    }

    public interface _FinalStage {
        OrganizationLogFindRequest build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements OrganizationIdStage, OrganizationLogIdStage, _FinalStage {
        private String organizationId;

        private String organizationLogId;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(OrganizationLogFindRequest other) {
            organizationId(other.getOrganizationId());
            organizationLogId(other.getOrganizationLogId());
            return this;
        }

        @java.lang.Override
        @JsonSetter("organizationId")
        public OrganizationLogIdStage organizationId(@NotNull String organizationId) {
            this.organizationId = Objects.requireNonNull(organizationId, "organizationId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("organizationLogId")
        public _FinalStage organizationLogId(@NotNull String organizationLogId) {
            this.organizationLogId = Objects.requireNonNull(organizationLogId, "organizationLogId must not be null");
            return this;
        }

        @java.lang.Override
        public OrganizationLogFindRequest build() {
            return new OrganizationLogFindRequest(organizationId, organizationLogId, additionalProperties);
        }
    }
}
