/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.diagrams.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.icepanel.core.ObjectMappers;
import com.icepanel.types.DiagramExportImage;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ExportCreateResponse.Builder.class)
public final class ExportCreateResponse {
    private final DiagramExportImage diagramExportImage;

    private final Map<String, Object> additionalProperties;

    private ExportCreateResponse(DiagramExportImage diagramExportImage, Map<String, Object> additionalProperties) {
        this.diagramExportImage = diagramExportImage;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("diagramExportImage")
    public DiagramExportImage getDiagramExportImage() {
        return diagramExportImage;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ExportCreateResponse && equalTo((ExportCreateResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ExportCreateResponse other) {
        return diagramExportImage.equals(other.diagramExportImage);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.diagramExportImage);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static DiagramExportImageStage builder() {
        return new Builder();
    }

    public interface DiagramExportImageStage {
        _FinalStage diagramExportImage(@NotNull DiagramExportImage diagramExportImage);

        Builder from(ExportCreateResponse other);
    }

    public interface _FinalStage {
        ExportCreateResponse build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements DiagramExportImageStage, _FinalStage {
        private DiagramExportImage diagramExportImage;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ExportCreateResponse other) {
            diagramExportImage(other.getDiagramExportImage());
            return this;
        }

        @java.lang.Override
        @JsonSetter("diagramExportImage")
        public _FinalStage diagramExportImage(@NotNull DiagramExportImage diagramExportImage) {
            this.diagramExportImage = Objects.requireNonNull(diagramExportImage, "diagramExportImage must not be null");
            return this;
        }

        @java.lang.Override
        public ExportCreateResponse build() {
            return new ExportCreateResponse(diagramExportImage, additionalProperties);
        }
    }
}
