/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.api.resources.diagrams.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.icepanel.api.core.ObjectMappers;
import com.icepanel.api.types.DiagramFilter;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DiagramThumbnailsListRequest.Builder.class)
public final class DiagramThumbnailsListRequest {
    private final Optional<DiagramFilter> filter;

    private final Map<String, Object> additionalProperties;

    private DiagramThumbnailsListRequest(Optional<DiagramFilter> filter, Map<String, Object> additionalProperties) {
        this.filter = filter;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("filter")
    public Optional<DiagramFilter> getFilter() {
        return filter;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DiagramThumbnailsListRequest && equalTo((DiagramThumbnailsListRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DiagramThumbnailsListRequest other) {
        return filter.equals(other.filter);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.filter);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<DiagramFilter> filter = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(DiagramThumbnailsListRequest other) {
            filter(other.getFilter());
            return this;
        }

        @JsonSetter(value = "filter", nulls = Nulls.SKIP)
        public Builder filter(Optional<DiagramFilter> filter) {
            this.filter = filter;
            return this;
        }

        public Builder filter(DiagramFilter filter) {
            this.filter = Optional.ofNullable(filter);
            return this;
        }

        public DiagramThumbnailsListRequest build() {
            return new DiagramThumbnailsListRequest(filter, additionalProperties);
        }
    }
}
