/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ActionOrganizationUserUpdateType {
    public static final ActionOrganizationUserUpdateType ORGANIZATION_USER_UPDATE =
            new ActionOrganizationUserUpdateType(Value.ORGANIZATION_USER_UPDATE, "organization-user-update");

    private final Value value;

    private final String string;

    ActionOrganizationUserUpdateType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ActionOrganizationUserUpdateType
                        && this.string.equals(((ActionOrganizationUserUpdateType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case ORGANIZATION_USER_UPDATE:
                return visitor.visitOrganizationUserUpdate();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ActionOrganizationUserUpdateType valueOf(String value) {
        switch (value) {
            case "organization-user-update":
                return ORGANIZATION_USER_UPDATE;
            default:
                return new ActionOrganizationUserUpdateType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        ORGANIZATION_USER_UPDATE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitOrganizationUserUpdate();

        T visitUnknown(String unknownType);
    }
}
