/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ActionDiagramGroupDeleteType {
    public static final ActionDiagramGroupDeleteType DIAGRAM_GROUP_DELETE =
            new ActionDiagramGroupDeleteType(Value.DIAGRAM_GROUP_DELETE, "diagram-group-delete");

    private final Value value;

    private final String string;

    ActionDiagramGroupDeleteType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ActionDiagramGroupDeleteType
                        && this.string.equals(((ActionDiagramGroupDeleteType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case DIAGRAM_GROUP_DELETE:
                return visitor.visitDiagramGroupDelete();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ActionDiagramGroupDeleteType valueOf(String value) {
        switch (value) {
            case "diagram-group-delete":
                return DIAGRAM_GROUP_DELETE;
            default:
                return new ActionDiagramGroupDeleteType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        DIAGRAM_GROUP_DELETE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitDiagramGroupDelete();

        T visitUnknown(String unknownType);
    }
}
