/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ActionOrganizationDeleteType {
    public static final ActionOrganizationDeleteType ORGANIZATION_DELETE =
            new ActionOrganizationDeleteType(Value.ORGANIZATION_DELETE, "organization-delete");

    private final Value value;

    private final String string;

    ActionOrganizationDeleteType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ActionOrganizationDeleteType
                        && this.string.equals(((ActionOrganizationDeleteType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case ORGANIZATION_DELETE:
                return visitor.visitOrganizationDelete();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ActionOrganizationDeleteType valueOf(String value) {
        switch (value) {
            case "organization-delete":
                return ORGANIZATION_DELETE;
            default:
                return new ActionOrganizationDeleteType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        ORGANIZATION_DELETE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitOrganizationDelete();

        T visitUnknown(String unknownType);
    }
}
