/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ActionDraftCreateType {
    public static final ActionDraftCreateType DRAFT_CREATE =
            new ActionDraftCreateType(Value.DRAFT_CREATE, "draft-create");

    private final Value value;

    private final String string;

    ActionDraftCreateType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ActionDraftCreateType
                        && this.string.equals(((ActionDraftCreateType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case DRAFT_CREATE:
                return visitor.visitDraftCreate();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ActionDraftCreateType valueOf(String value) {
        switch (value) {
            case "draft-create":
                return DRAFT_CREATE;
            default:
                return new ActionDraftCreateType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        DRAFT_CREATE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitDraftCreate();

        T visitUnknown(String unknownType);
    }
}
