/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.icepanel.api.core.Nullable;
import com.icepanel.api.core.NullableNonemptyFilter;
import com.icepanel.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ActionShareLinkUpdateContext.Builder.class)
public final class ActionShareLinkUpdateContext {
    private final Optional<String> draftHandleId;

    private final Optional<String> draftName;

    private final String shortId;

    private final Optional<String> versionModelHandleId;

    private final String versionName;

    private final Map<String, Object> additionalProperties;

    private ActionShareLinkUpdateContext(
            Optional<String> draftHandleId,
            Optional<String> draftName,
            String shortId,
            Optional<String> versionModelHandleId,
            String versionName,
            Map<String, Object> additionalProperties) {
        this.draftHandleId = draftHandleId;
        this.draftName = draftName;
        this.shortId = shortId;
        this.versionModelHandleId = versionModelHandleId;
        this.versionName = versionName;
        this.additionalProperties = additionalProperties;
    }

    @JsonIgnore
    public Optional<String> getDraftHandleId() {
        if (draftHandleId == null) {
            return Optional.empty();
        }
        return draftHandleId;
    }

    @JsonProperty("draftName")
    public Optional<String> getDraftName() {
        return draftName;
    }

    @JsonProperty("shortId")
    public String getShortId() {
        return shortId;
    }

    @JsonIgnore
    public Optional<String> getVersionModelHandleId() {
        if (versionModelHandleId == null) {
            return Optional.empty();
        }
        return versionModelHandleId;
    }

    @JsonProperty("versionName")
    public String getVersionName() {
        return versionName;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("draftHandleId")
    private Optional<String> _getDraftHandleId() {
        return draftHandleId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("versionModelHandleId")
    private Optional<String> _getVersionModelHandleId() {
        return versionModelHandleId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ActionShareLinkUpdateContext && equalTo((ActionShareLinkUpdateContext) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ActionShareLinkUpdateContext other) {
        return draftHandleId.equals(other.draftHandleId)
                && draftName.equals(other.draftName)
                && shortId.equals(other.shortId)
                && versionModelHandleId.equals(other.versionModelHandleId)
                && versionName.equals(other.versionName);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.draftHandleId, this.draftName, this.shortId, this.versionModelHandleId, this.versionName);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ShortIdStage builder() {
        return new Builder();
    }

    public interface ShortIdStage {
        VersionNameStage shortId(@NotNull String shortId);

        Builder from(ActionShareLinkUpdateContext other);
    }

    public interface VersionNameStage {
        _FinalStage versionName(@NotNull String versionName);
    }

    public interface _FinalStage {
        ActionShareLinkUpdateContext build();

        _FinalStage draftHandleId(Optional<String> draftHandleId);

        _FinalStage draftHandleId(String draftHandleId);

        _FinalStage draftHandleId(Nullable<String> draftHandleId);

        _FinalStage draftName(Optional<String> draftName);

        _FinalStage draftName(String draftName);

        _FinalStage versionModelHandleId(Optional<String> versionModelHandleId);

        _FinalStage versionModelHandleId(String versionModelHandleId);

        _FinalStage versionModelHandleId(Nullable<String> versionModelHandleId);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ShortIdStage, VersionNameStage, _FinalStage {
        private String shortId;

        private String versionName;

        private Optional<String> versionModelHandleId = Optional.empty();

        private Optional<String> draftName = Optional.empty();

        private Optional<String> draftHandleId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ActionShareLinkUpdateContext other) {
            draftHandleId(other.getDraftHandleId());
            draftName(other.getDraftName());
            shortId(other.getShortId());
            versionModelHandleId(other.getVersionModelHandleId());
            versionName(other.getVersionName());
            return this;
        }

        @java.lang.Override
        @JsonSetter("shortId")
        public VersionNameStage shortId(@NotNull String shortId) {
            this.shortId = Objects.requireNonNull(shortId, "shortId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("versionName")
        public _FinalStage versionName(@NotNull String versionName) {
            this.versionName = Objects.requireNonNull(versionName, "versionName must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage versionModelHandleId(Nullable<String> versionModelHandleId) {
            if (versionModelHandleId.isNull()) {
                this.versionModelHandleId = null;
            } else if (versionModelHandleId.isEmpty()) {
                this.versionModelHandleId = Optional.empty();
            } else {
                this.versionModelHandleId = Optional.of(versionModelHandleId.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage versionModelHandleId(String versionModelHandleId) {
            this.versionModelHandleId = Optional.ofNullable(versionModelHandleId);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "versionModelHandleId", nulls = Nulls.SKIP)
        public _FinalStage versionModelHandleId(Optional<String> versionModelHandleId) {
            this.versionModelHandleId = versionModelHandleId;
            return this;
        }

        @java.lang.Override
        public _FinalStage draftName(String draftName) {
            this.draftName = Optional.ofNullable(draftName);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "draftName", nulls = Nulls.SKIP)
        public _FinalStage draftName(Optional<String> draftName) {
            this.draftName = draftName;
            return this;
        }

        @java.lang.Override
        public _FinalStage draftHandleId(Nullable<String> draftHandleId) {
            if (draftHandleId.isNull()) {
                this.draftHandleId = null;
            } else if (draftHandleId.isEmpty()) {
                this.draftHandleId = Optional.empty();
            } else {
                this.draftHandleId = Optional.of(draftHandleId.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage draftHandleId(String draftHandleId) {
            this.draftHandleId = Optional.ofNullable(draftHandleId);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "draftHandleId", nulls = Nulls.SKIP)
        public _FinalStage draftHandleId(Optional<String> draftHandleId) {
            this.draftHandleId = draftHandleId;
            return this;
        }

        @java.lang.Override
        public ActionShareLinkUpdateContext build() {
            return new ActionShareLinkUpdateContext(
                    draftHandleId, draftName, shortId, versionModelHandleId, versionName, additionalProperties);
        }
    }
}
