/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.icepanel.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CatalogTechnologyFilter.Builder.class)
public final class CatalogTechnologyFilter {
    private final Optional<CatalogTechnologyFilterProvider> provider;

    private final Optional<CatalogTechnologyFilterRestrictions> restrictions;

    private final Optional<CatalogTechnologyFilterStatus> status;

    private final Optional<CatalogTechnologyFilterType> type;

    private final Map<String, Object> additionalProperties;

    private CatalogTechnologyFilter(
            Optional<CatalogTechnologyFilterProvider> provider,
            Optional<CatalogTechnologyFilterRestrictions> restrictions,
            Optional<CatalogTechnologyFilterStatus> status,
            Optional<CatalogTechnologyFilterType> type,
            Map<String, Object> additionalProperties) {
        this.provider = provider;
        this.restrictions = restrictions;
        this.status = status;
        this.type = type;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("provider")
    public Optional<CatalogTechnologyFilterProvider> getProvider() {
        return provider;
    }

    @JsonProperty("restrictions")
    public Optional<CatalogTechnologyFilterRestrictions> getRestrictions() {
        return restrictions;
    }

    @JsonProperty("status")
    public Optional<CatalogTechnologyFilterStatus> getStatus() {
        return status;
    }

    @JsonProperty("type")
    public Optional<CatalogTechnologyFilterType> getType() {
        return type;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CatalogTechnologyFilter && equalTo((CatalogTechnologyFilter) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CatalogTechnologyFilter other) {
        return provider.equals(other.provider)
                && restrictions.equals(other.restrictions)
                && status.equals(other.status)
                && type.equals(other.type);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.provider, this.restrictions, this.status, this.type);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<CatalogTechnologyFilterProvider> provider = Optional.empty();

        private Optional<CatalogTechnologyFilterRestrictions> restrictions = Optional.empty();

        private Optional<CatalogTechnologyFilterStatus> status = Optional.empty();

        private Optional<CatalogTechnologyFilterType> type = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(CatalogTechnologyFilter other) {
            provider(other.getProvider());
            restrictions(other.getRestrictions());
            status(other.getStatus());
            type(other.getType());
            return this;
        }

        @JsonSetter(value = "provider", nulls = Nulls.SKIP)
        public Builder provider(Optional<CatalogTechnologyFilterProvider> provider) {
            this.provider = provider;
            return this;
        }

        public Builder provider(CatalogTechnologyFilterProvider provider) {
            this.provider = Optional.ofNullable(provider);
            return this;
        }

        @JsonSetter(value = "restrictions", nulls = Nulls.SKIP)
        public Builder restrictions(Optional<CatalogTechnologyFilterRestrictions> restrictions) {
            this.restrictions = restrictions;
            return this;
        }

        public Builder restrictions(CatalogTechnologyFilterRestrictions restrictions) {
            this.restrictions = Optional.ofNullable(restrictions);
            return this;
        }

        @JsonSetter(value = "status", nulls = Nulls.SKIP)
        public Builder status(Optional<CatalogTechnologyFilterStatus> status) {
            this.status = status;
            return this;
        }

        public Builder status(CatalogTechnologyFilterStatus status) {
            this.status = Optional.ofNullable(status);
            return this;
        }

        @JsonSetter(value = "type", nulls = Nulls.SKIP)
        public Builder type(Optional<CatalogTechnologyFilterType> type) {
            this.type = type;
            return this;
        }

        public Builder type(CatalogTechnologyFilterType type) {
            this.type = Optional.ofNullable(type);
            return this;
        }

        public CatalogTechnologyFilter build() {
            return new CatalogTechnologyFilter(provider, restrictions, status, type, additionalProperties);
        }
    }
}
