/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.icepanel.api.core.Nullable;
import com.icepanel.api.core.NullableNonemptyFilter;
import com.icepanel.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CatalogTechnology.Builder.class)
public final class CatalogTechnology {
    private final Optional<String> category;

    private final TagColor color;

    private final Optional<OffsetDateTime> deprecatedAt;

    private final Optional<String> description;

    private final Optional<String> docsUrl;

    private final Optional<String> iconUrlDark;

    private final Optional<String> iconUrlLight;

    private final String name;

    private final Optional<String> nameShort;

    private final Optional<CatalogProviderNullable> provider;

    private final Optional<String> rejectionMessage;

    private final Optional<CatalogTechnologyReviewRejectionReason> rejectionReason;

    private final Optional<List<CatalogRestriction>> restrictions;

    private final Optional<CatalogTechnologyStatus> status;

    private final Optional<CatalogTechnologyTypeNullable> type;

    private final Optional<String> updatesUrl;

    private final Optional<String> websiteUrl;

    private final Optional<String> awsXmlSelector;

    private final Optional<String> azureUpdatesKeyword;

    private final OffsetDateTime createdAt;

    private final AuthType createdBy;

    private final String createdById;

    private final Optional<String> defaultSlug;

    private final Optional<OffsetDateTime> deletedAt;

    private final Optional<AuthType> deletedBy;

    private final Optional<String> deletedById;

    private final boolean disabled;

    private final Optional<String> iconUrl;

    private final String id;

    private final Optional<String> organizationId;

    private final Optional<List<String>> slugs;

    private final OffsetDateTime updatedAt;

    private final AuthType updatedBy;

    private final String updatedById;

    private final Optional<String> updatesXmlUrl;

    private final Map<String, Object> additionalProperties;

    private CatalogTechnology(
            Optional<String> category,
            TagColor color,
            Optional<OffsetDateTime> deprecatedAt,
            Optional<String> description,
            Optional<String> docsUrl,
            Optional<String> iconUrlDark,
            Optional<String> iconUrlLight,
            String name,
            Optional<String> nameShort,
            Optional<CatalogProviderNullable> provider,
            Optional<String> rejectionMessage,
            Optional<CatalogTechnologyReviewRejectionReason> rejectionReason,
            Optional<List<CatalogRestriction>> restrictions,
            Optional<CatalogTechnologyStatus> status,
            Optional<CatalogTechnologyTypeNullable> type,
            Optional<String> updatesUrl,
            Optional<String> websiteUrl,
            Optional<String> awsXmlSelector,
            Optional<String> azureUpdatesKeyword,
            OffsetDateTime createdAt,
            AuthType createdBy,
            String createdById,
            Optional<String> defaultSlug,
            Optional<OffsetDateTime> deletedAt,
            Optional<AuthType> deletedBy,
            Optional<String> deletedById,
            boolean disabled,
            Optional<String> iconUrl,
            String id,
            Optional<String> organizationId,
            Optional<List<String>> slugs,
            OffsetDateTime updatedAt,
            AuthType updatedBy,
            String updatedById,
            Optional<String> updatesXmlUrl,
            Map<String, Object> additionalProperties) {
        this.category = category;
        this.color = color;
        this.deprecatedAt = deprecatedAt;
        this.description = description;
        this.docsUrl = docsUrl;
        this.iconUrlDark = iconUrlDark;
        this.iconUrlLight = iconUrlLight;
        this.name = name;
        this.nameShort = nameShort;
        this.provider = provider;
        this.rejectionMessage = rejectionMessage;
        this.rejectionReason = rejectionReason;
        this.restrictions = restrictions;
        this.status = status;
        this.type = type;
        this.updatesUrl = updatesUrl;
        this.websiteUrl = websiteUrl;
        this.awsXmlSelector = awsXmlSelector;
        this.azureUpdatesKeyword = azureUpdatesKeyword;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
        this.createdById = createdById;
        this.defaultSlug = defaultSlug;
        this.deletedAt = deletedAt;
        this.deletedBy = deletedBy;
        this.deletedById = deletedById;
        this.disabled = disabled;
        this.iconUrl = iconUrl;
        this.id = id;
        this.organizationId = organizationId;
        this.slugs = slugs;
        this.updatedAt = updatedAt;
        this.updatedBy = updatedBy;
        this.updatedById = updatedById;
        this.updatesXmlUrl = updatesXmlUrl;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("category")
    public Optional<String> getCategory() {
        return category;
    }

    /**
     * @return Technology color used in diagrams
     */
    @JsonProperty("color")
    public TagColor getColor() {
        return color;
    }

    @JsonProperty("deprecatedAt")
    public Optional<OffsetDateTime> getDeprecatedAt() {
        return deprecatedAt;
    }

    /**
     * @return Technical description for the technology, avoid marketing language
     */
    @JsonProperty("description")
    public Optional<String> getDescription() {
        return description;
    }

    /**
     * @return Documentation or readme url
     */
    @JsonProperty("docsUrl")
    public Optional<String> getDocsUrl() {
        return docsUrl;
    }

    /**
     * @return Icon that only works on dark backgrounds
     */
    @JsonIgnore
    public Optional<String> getIconUrlDark() {
        if (iconUrlDark == null) {
            return Optional.empty();
        }
        return iconUrlDark;
    }

    /**
     * @return Icon that only works on light backgrounds
     */
    @JsonIgnore
    public Optional<String> getIconUrlLight() {
        if (iconUrlLight == null) {
            return Optional.empty();
        }
        return iconUrlLight;
    }

    /**
     * @return Long verbose name
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    /**
     * @return Short one or two word name to show in places with limited space
     */
    @JsonProperty("nameShort")
    public Optional<String> getNameShort() {
        return nameShort;
    }

    /**
     * @return Service provider that provides this technology
     */
    @JsonIgnore
    public Optional<CatalogProviderNullable> getProvider() {
        if (provider == null) {
            return Optional.empty();
        }
        return provider;
    }

    /**
     * @return If rejected, detail description of why
     */
    @JsonProperty("rejectionMessage")
    public Optional<String> getRejectionMessage() {
        return rejectionMessage;
    }

    /**
     * @return If rejected, the reason why
     */
    @JsonProperty("rejectionReason")
    public Optional<CatalogTechnologyReviewRejectionReason> getRejectionReason() {
        return rejectionReason;
    }

    /**
     * @return Restriction on which model object or connections this technology can be added to
     */
    @JsonIgnore
    public Optional<List<CatalogRestriction>> getRestrictions() {
        if (restrictions == null) {
            return Optional.empty();
        }
        return restrictions;
    }

    /**
     * @return Current status of the technology, including pending review, approved, and rejected. Approved technologies are visible to all users.
     */
    @JsonProperty("status")
    public Optional<CatalogTechnologyStatus> getStatus() {
        return status;
    }

    /**
     * @return Type or category of technology
     */
    @JsonIgnore
    public Optional<CatalogTechnologyTypeNullable> getType() {
        if (type == null) {
            return Optional.empty();
        }
        return type;
    }

    /**
     * @return Release notes or changelog url
     */
    @JsonProperty("updatesUrl")
    public Optional<String> getUpdatesUrl() {
        return updatesUrl;
    }

    /**
     * @return Landing page website url
     */
    @JsonProperty("websiteUrl")
    public Optional<String> getWebsiteUrl() {
        return websiteUrl;
    }

    @JsonProperty("awsXmlSelector")
    public Optional<String> getAwsXmlSelector() {
        return awsXmlSelector;
    }

    @JsonProperty("azureUpdatesKeyword")
    public Optional<String> getAzureUpdatesKeyword() {
        return azureUpdatesKeyword;
    }

    @JsonProperty("createdAt")
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    @JsonProperty("createdBy")
    public AuthType getCreatedBy() {
        return createdBy;
    }

    @JsonProperty("createdById")
    public String getCreatedById() {
        return createdById;
    }

    /**
     * @return URL path name for the technology, used by stackfeed
     */
    @JsonProperty("defaultSlug")
    public Optional<String> getDefaultSlug() {
        return defaultSlug;
    }

    @JsonProperty("deletedAt")
    public Optional<OffsetDateTime> getDeletedAt() {
        return deletedAt;
    }

    @JsonProperty("deletedBy")
    public Optional<AuthType> getDeletedBy() {
        return deletedBy;
    }

    @JsonProperty("deletedById")
    public Optional<String> getDeletedById() {
        return deletedById;
    }

    /**
     * @return Whether the technology is disabled and not visible to users
     */
    @JsonProperty("disabled")
    public boolean getDisabled() {
        return disabled;
    }

    /**
     * @return Use either iconUrlDark or iconUrlLight
     */
    @JsonIgnore
    public Optional<String> getIconUrl() {
        if (iconUrl == null) {
            return Optional.empty();
        }
        return iconUrl;
    }

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    /**
     * @return Organization that owns this technology, or null if its publicly accessible
     */
    @JsonIgnore
    public Optional<String> getOrganizationId() {
        if (organizationId == null) {
            return Optional.empty();
        }
        return organizationId;
    }

    /**
     * @return Current and historical url path names used for the technology, used by stackfeed
     */
    @JsonProperty("slugs")
    public Optional<List<String>> getSlugs() {
        return slugs;
    }

    @JsonProperty("updatedAt")
    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    @JsonProperty("updatedBy")
    public AuthType getUpdatedBy() {
        return updatedBy;
    }

    @JsonProperty("updatedById")
    public String getUpdatedById() {
        return updatedById;
    }

    @JsonProperty("updatesXmlUrl")
    public Optional<String> getUpdatesXmlUrl() {
        return updatesXmlUrl;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("iconUrlDark")
    private Optional<String> _getIconUrlDark() {
        return iconUrlDark;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("iconUrlLight")
    private Optional<String> _getIconUrlLight() {
        return iconUrlLight;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("provider")
    private Optional<CatalogProviderNullable> _getProvider() {
        return provider;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("restrictions")
    private Optional<List<CatalogRestriction>> _getRestrictions() {
        return restrictions;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("type")
    private Optional<CatalogTechnologyTypeNullable> _getType() {
        return type;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("iconUrl")
    private Optional<String> _getIconUrl() {
        return iconUrl;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("organizationId")
    private Optional<String> _getOrganizationId() {
        return organizationId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CatalogTechnology && equalTo((CatalogTechnology) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CatalogTechnology other) {
        return category.equals(other.category)
                && color.equals(other.color)
                && deprecatedAt.equals(other.deprecatedAt)
                && description.equals(other.description)
                && docsUrl.equals(other.docsUrl)
                && iconUrlDark.equals(other.iconUrlDark)
                && iconUrlLight.equals(other.iconUrlLight)
                && name.equals(other.name)
                && nameShort.equals(other.nameShort)
                && provider.equals(other.provider)
                && rejectionMessage.equals(other.rejectionMessage)
                && rejectionReason.equals(other.rejectionReason)
                && restrictions.equals(other.restrictions)
                && status.equals(other.status)
                && type.equals(other.type)
                && updatesUrl.equals(other.updatesUrl)
                && websiteUrl.equals(other.websiteUrl)
                && awsXmlSelector.equals(other.awsXmlSelector)
                && azureUpdatesKeyword.equals(other.azureUpdatesKeyword)
                && createdAt.equals(other.createdAt)
                && createdBy.equals(other.createdBy)
                && createdById.equals(other.createdById)
                && defaultSlug.equals(other.defaultSlug)
                && deletedAt.equals(other.deletedAt)
                && deletedBy.equals(other.deletedBy)
                && deletedById.equals(other.deletedById)
                && disabled == other.disabled
                && iconUrl.equals(other.iconUrl)
                && id.equals(other.id)
                && organizationId.equals(other.organizationId)
                && slugs.equals(other.slugs)
                && updatedAt.equals(other.updatedAt)
                && updatedBy.equals(other.updatedBy)
                && updatedById.equals(other.updatedById)
                && updatesXmlUrl.equals(other.updatesXmlUrl);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.category,
                this.color,
                this.deprecatedAt,
                this.description,
                this.docsUrl,
                this.iconUrlDark,
                this.iconUrlLight,
                this.name,
                this.nameShort,
                this.provider,
                this.rejectionMessage,
                this.rejectionReason,
                this.restrictions,
                this.status,
                this.type,
                this.updatesUrl,
                this.websiteUrl,
                this.awsXmlSelector,
                this.azureUpdatesKeyword,
                this.createdAt,
                this.createdBy,
                this.createdById,
                this.defaultSlug,
                this.deletedAt,
                this.deletedBy,
                this.deletedById,
                this.disabled,
                this.iconUrl,
                this.id,
                this.organizationId,
                this.slugs,
                this.updatedAt,
                this.updatedBy,
                this.updatedById,
                this.updatesXmlUrl);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ColorStage builder() {
        return new Builder();
    }

    public interface ColorStage {
        /**
         * <p>Technology color used in diagrams</p>
         */
        NameStage color(@NotNull TagColor color);

        Builder from(CatalogTechnology other);
    }

    public interface NameStage {
        /**
         * <p>Long verbose name</p>
         */
        CreatedAtStage name(@NotNull String name);
    }

    public interface CreatedAtStage {
        CreatedByStage createdAt(@NotNull OffsetDateTime createdAt);
    }

    public interface CreatedByStage {
        CreatedByIdStage createdBy(@NotNull AuthType createdBy);
    }

    public interface CreatedByIdStage {
        DisabledStage createdById(@NotNull String createdById);
    }

    public interface DisabledStage {
        /**
         * <p>Whether the technology is disabled and not visible to users</p>
         */
        IdStage disabled(boolean disabled);
    }

    public interface IdStage {
        UpdatedAtStage id(@NotNull String id);
    }

    public interface UpdatedAtStage {
        UpdatedByStage updatedAt(@NotNull OffsetDateTime updatedAt);
    }

    public interface UpdatedByStage {
        UpdatedByIdStage updatedBy(@NotNull AuthType updatedBy);
    }

    public interface UpdatedByIdStage {
        _FinalStage updatedById(@NotNull String updatedById);
    }

    public interface _FinalStage {
        CatalogTechnology build();

        _FinalStage category(Optional<String> category);

        _FinalStage category(String category);

        _FinalStage deprecatedAt(Optional<OffsetDateTime> deprecatedAt);

        _FinalStage deprecatedAt(OffsetDateTime deprecatedAt);

        /**
         * <p>Technical description for the technology, avoid marketing language</p>
         */
        _FinalStage description(Optional<String> description);

        _FinalStage description(String description);

        /**
         * <p>Documentation or readme url</p>
         */
        _FinalStage docsUrl(Optional<String> docsUrl);

        _FinalStage docsUrl(String docsUrl);

        /**
         * <p>Icon that only works on dark backgrounds</p>
         */
        _FinalStage iconUrlDark(Optional<String> iconUrlDark);

        _FinalStage iconUrlDark(String iconUrlDark);

        _FinalStage iconUrlDark(Nullable<String> iconUrlDark);

        /**
         * <p>Icon that only works on light backgrounds</p>
         */
        _FinalStage iconUrlLight(Optional<String> iconUrlLight);

        _FinalStage iconUrlLight(String iconUrlLight);

        _FinalStage iconUrlLight(Nullable<String> iconUrlLight);

        /**
         * <p>Short one or two word name to show in places with limited space</p>
         */
        _FinalStage nameShort(Optional<String> nameShort);

        _FinalStage nameShort(String nameShort);

        /**
         * <p>Service provider that provides this technology</p>
         */
        _FinalStage provider(Optional<CatalogProviderNullable> provider);

        _FinalStage provider(CatalogProviderNullable provider);

        _FinalStage provider(Nullable<CatalogProviderNullable> provider);

        /**
         * <p>If rejected, detail description of why</p>
         */
        _FinalStage rejectionMessage(Optional<String> rejectionMessage);

        _FinalStage rejectionMessage(String rejectionMessage);

        /**
         * <p>If rejected, the reason why</p>
         */
        _FinalStage rejectionReason(Optional<CatalogTechnologyReviewRejectionReason> rejectionReason);

        _FinalStage rejectionReason(CatalogTechnologyReviewRejectionReason rejectionReason);

        /**
         * <p>Restriction on which model object or connections this technology can be added to</p>
         */
        _FinalStage restrictions(Optional<List<CatalogRestriction>> restrictions);

        _FinalStage restrictions(List<CatalogRestriction> restrictions);

        _FinalStage restrictions(Nullable<List<CatalogRestriction>> restrictions);

        /**
         * <p>Current status of the technology, including pending review, approved, and rejected. Approved technologies are visible to all users.</p>
         */
        _FinalStage status(Optional<CatalogTechnologyStatus> status);

        _FinalStage status(CatalogTechnologyStatus status);

        /**
         * <p>Type or category of technology</p>
         */
        _FinalStage type(Optional<CatalogTechnologyTypeNullable> type);

        _FinalStage type(CatalogTechnologyTypeNullable type);

        _FinalStage type(Nullable<CatalogTechnologyTypeNullable> type);

        /**
         * <p>Release notes or changelog url</p>
         */
        _FinalStage updatesUrl(Optional<String> updatesUrl);

        _FinalStage updatesUrl(String updatesUrl);

        /**
         * <p>Landing page website url</p>
         */
        _FinalStage websiteUrl(Optional<String> websiteUrl);

        _FinalStage websiteUrl(String websiteUrl);

        _FinalStage awsXmlSelector(Optional<String> awsXmlSelector);

        _FinalStage awsXmlSelector(String awsXmlSelector);

        _FinalStage azureUpdatesKeyword(Optional<String> azureUpdatesKeyword);

        _FinalStage azureUpdatesKeyword(String azureUpdatesKeyword);

        /**
         * <p>URL path name for the technology, used by stackfeed</p>
         */
        _FinalStage defaultSlug(Optional<String> defaultSlug);

        _FinalStage defaultSlug(String defaultSlug);

        _FinalStage deletedAt(Optional<OffsetDateTime> deletedAt);

        _FinalStage deletedAt(OffsetDateTime deletedAt);

        _FinalStage deletedBy(Optional<AuthType> deletedBy);

        _FinalStage deletedBy(AuthType deletedBy);

        _FinalStage deletedById(Optional<String> deletedById);

        _FinalStage deletedById(String deletedById);

        /**
         * <p>Use either iconUrlDark or iconUrlLight</p>
         */
        _FinalStage iconUrl(Optional<String> iconUrl);

        _FinalStage iconUrl(String iconUrl);

        _FinalStage iconUrl(Nullable<String> iconUrl);

        /**
         * <p>Organization that owns this technology, or null if its publicly accessible</p>
         */
        _FinalStage organizationId(Optional<String> organizationId);

        _FinalStage organizationId(String organizationId);

        _FinalStage organizationId(Nullable<String> organizationId);

        /**
         * <p>Current and historical url path names used for the technology, used by stackfeed</p>
         */
        _FinalStage slugs(Optional<List<String>> slugs);

        _FinalStage slugs(List<String> slugs);

        _FinalStage updatesXmlUrl(Optional<String> updatesXmlUrl);

        _FinalStage updatesXmlUrl(String updatesXmlUrl);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements ColorStage,
                    NameStage,
                    CreatedAtStage,
                    CreatedByStage,
                    CreatedByIdStage,
                    DisabledStage,
                    IdStage,
                    UpdatedAtStage,
                    UpdatedByStage,
                    UpdatedByIdStage,
                    _FinalStage {
        private TagColor color;

        private String name;

        private OffsetDateTime createdAt;

        private AuthType createdBy;

        private String createdById;

        private boolean disabled;

        private String id;

        private OffsetDateTime updatedAt;

        private AuthType updatedBy;

        private String updatedById;

        private Optional<String> updatesXmlUrl = Optional.empty();

        private Optional<List<String>> slugs = Optional.empty();

        private Optional<String> organizationId = Optional.empty();

        private Optional<String> iconUrl = Optional.empty();

        private Optional<String> deletedById = Optional.empty();

        private Optional<AuthType> deletedBy = Optional.empty();

        private Optional<OffsetDateTime> deletedAt = Optional.empty();

        private Optional<String> defaultSlug = Optional.empty();

        private Optional<String> azureUpdatesKeyword = Optional.empty();

        private Optional<String> awsXmlSelector = Optional.empty();

        private Optional<String> websiteUrl = Optional.empty();

        private Optional<String> updatesUrl = Optional.empty();

        private Optional<CatalogTechnologyTypeNullable> type = Optional.empty();

        private Optional<CatalogTechnologyStatus> status = Optional.empty();

        private Optional<List<CatalogRestriction>> restrictions = Optional.empty();

        private Optional<CatalogTechnologyReviewRejectionReason> rejectionReason = Optional.empty();

        private Optional<String> rejectionMessage = Optional.empty();

        private Optional<CatalogProviderNullable> provider = Optional.empty();

        private Optional<String> nameShort = Optional.empty();

        private Optional<String> iconUrlLight = Optional.empty();

        private Optional<String> iconUrlDark = Optional.empty();

        private Optional<String> docsUrl = Optional.empty();

        private Optional<String> description = Optional.empty();

        private Optional<OffsetDateTime> deprecatedAt = Optional.empty();

        private Optional<String> category = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CatalogTechnology other) {
            category(other.getCategory());
            color(other.getColor());
            deprecatedAt(other.getDeprecatedAt());
            description(other.getDescription());
            docsUrl(other.getDocsUrl());
            iconUrlDark(other.getIconUrlDark());
            iconUrlLight(other.getIconUrlLight());
            name(other.getName());
            nameShort(other.getNameShort());
            provider(other.getProvider());
            rejectionMessage(other.getRejectionMessage());
            rejectionReason(other.getRejectionReason());
            restrictions(other.getRestrictions());
            status(other.getStatus());
            type(other.getType());
            updatesUrl(other.getUpdatesUrl());
            websiteUrl(other.getWebsiteUrl());
            awsXmlSelector(other.getAwsXmlSelector());
            azureUpdatesKeyword(other.getAzureUpdatesKeyword());
            createdAt(other.getCreatedAt());
            createdBy(other.getCreatedBy());
            createdById(other.getCreatedById());
            defaultSlug(other.getDefaultSlug());
            deletedAt(other.getDeletedAt());
            deletedBy(other.getDeletedBy());
            deletedById(other.getDeletedById());
            disabled(other.getDisabled());
            iconUrl(other.getIconUrl());
            id(other.getId());
            organizationId(other.getOrganizationId());
            slugs(other.getSlugs());
            updatedAt(other.getUpdatedAt());
            updatedBy(other.getUpdatedBy());
            updatedById(other.getUpdatedById());
            updatesXmlUrl(other.getUpdatesXmlUrl());
            return this;
        }

        /**
         * <p>Technology color used in diagrams</p>
         * <p>Technology color used in diagrams</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("color")
        public NameStage color(@NotNull TagColor color) {
            this.color = Objects.requireNonNull(color, "color must not be null");
            return this;
        }

        /**
         * <p>Long verbose name</p>
         * <p>Long verbose name</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public CreatedAtStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("createdAt")
        public CreatedByStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("createdBy")
        public CreatedByIdStage createdBy(@NotNull AuthType createdBy) {
            this.createdBy = Objects.requireNonNull(createdBy, "createdBy must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("createdById")
        public DisabledStage createdById(@NotNull String createdById) {
            this.createdById = Objects.requireNonNull(createdById, "createdById must not be null");
            return this;
        }

        /**
         * <p>Whether the technology is disabled and not visible to users</p>
         * <p>Whether the technology is disabled and not visible to users</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("disabled")
        public IdStage disabled(boolean disabled) {
            this.disabled = disabled;
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public UpdatedAtStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("updatedAt")
        public UpdatedByStage updatedAt(@NotNull OffsetDateTime updatedAt) {
            this.updatedAt = Objects.requireNonNull(updatedAt, "updatedAt must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("updatedBy")
        public UpdatedByIdStage updatedBy(@NotNull AuthType updatedBy) {
            this.updatedBy = Objects.requireNonNull(updatedBy, "updatedBy must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("updatedById")
        public _FinalStage updatedById(@NotNull String updatedById) {
            this.updatedById = Objects.requireNonNull(updatedById, "updatedById must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage updatesXmlUrl(String updatesXmlUrl) {
            this.updatesXmlUrl = Optional.ofNullable(updatesXmlUrl);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "updatesXmlUrl", nulls = Nulls.SKIP)
        public _FinalStage updatesXmlUrl(Optional<String> updatesXmlUrl) {
            this.updatesXmlUrl = updatesXmlUrl;
            return this;
        }

        /**
         * <p>Current and historical url path names used for the technology, used by stackfeed</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage slugs(List<String> slugs) {
            this.slugs = Optional.ofNullable(slugs);
            return this;
        }

        /**
         * <p>Current and historical url path names used for the technology, used by stackfeed</p>
         */
        @java.lang.Override
        @JsonSetter(value = "slugs", nulls = Nulls.SKIP)
        public _FinalStage slugs(Optional<List<String>> slugs) {
            this.slugs = slugs;
            return this;
        }

        /**
         * <p>Organization that owns this technology, or null if its publicly accessible</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage organizationId(Nullable<String> organizationId) {
            if (organizationId.isNull()) {
                this.organizationId = null;
            } else if (organizationId.isEmpty()) {
                this.organizationId = Optional.empty();
            } else {
                this.organizationId = Optional.of(organizationId.get());
            }
            return this;
        }

        /**
         * <p>Organization that owns this technology, or null if its publicly accessible</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage organizationId(String organizationId) {
            this.organizationId = Optional.ofNullable(organizationId);
            return this;
        }

        /**
         * <p>Organization that owns this technology, or null if its publicly accessible</p>
         */
        @java.lang.Override
        @JsonSetter(value = "organizationId", nulls = Nulls.SKIP)
        public _FinalStage organizationId(Optional<String> organizationId) {
            this.organizationId = organizationId;
            return this;
        }

        /**
         * <p>Use either iconUrlDark or iconUrlLight</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage iconUrl(Nullable<String> iconUrl) {
            if (iconUrl.isNull()) {
                this.iconUrl = null;
            } else if (iconUrl.isEmpty()) {
                this.iconUrl = Optional.empty();
            } else {
                this.iconUrl = Optional.of(iconUrl.get());
            }
            return this;
        }

        /**
         * <p>Use either iconUrlDark or iconUrlLight</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage iconUrl(String iconUrl) {
            this.iconUrl = Optional.ofNullable(iconUrl);
            return this;
        }

        /**
         * <p>Use either iconUrlDark or iconUrlLight</p>
         */
        @java.lang.Override
        @JsonSetter(value = "iconUrl", nulls = Nulls.SKIP)
        public _FinalStage iconUrl(Optional<String> iconUrl) {
            this.iconUrl = iconUrl;
            return this;
        }

        @java.lang.Override
        public _FinalStage deletedById(String deletedById) {
            this.deletedById = Optional.ofNullable(deletedById);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "deletedById", nulls = Nulls.SKIP)
        public _FinalStage deletedById(Optional<String> deletedById) {
            this.deletedById = deletedById;
            return this;
        }

        @java.lang.Override
        public _FinalStage deletedBy(AuthType deletedBy) {
            this.deletedBy = Optional.ofNullable(deletedBy);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "deletedBy", nulls = Nulls.SKIP)
        public _FinalStage deletedBy(Optional<AuthType> deletedBy) {
            this.deletedBy = deletedBy;
            return this;
        }

        @java.lang.Override
        public _FinalStage deletedAt(OffsetDateTime deletedAt) {
            this.deletedAt = Optional.ofNullable(deletedAt);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "deletedAt", nulls = Nulls.SKIP)
        public _FinalStage deletedAt(Optional<OffsetDateTime> deletedAt) {
            this.deletedAt = deletedAt;
            return this;
        }

        /**
         * <p>URL path name for the technology, used by stackfeed</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage defaultSlug(String defaultSlug) {
            this.defaultSlug = Optional.ofNullable(defaultSlug);
            return this;
        }

        /**
         * <p>URL path name for the technology, used by stackfeed</p>
         */
        @java.lang.Override
        @JsonSetter(value = "defaultSlug", nulls = Nulls.SKIP)
        public _FinalStage defaultSlug(Optional<String> defaultSlug) {
            this.defaultSlug = defaultSlug;
            return this;
        }

        @java.lang.Override
        public _FinalStage azureUpdatesKeyword(String azureUpdatesKeyword) {
            this.azureUpdatesKeyword = Optional.ofNullable(azureUpdatesKeyword);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "azureUpdatesKeyword", nulls = Nulls.SKIP)
        public _FinalStage azureUpdatesKeyword(Optional<String> azureUpdatesKeyword) {
            this.azureUpdatesKeyword = azureUpdatesKeyword;
            return this;
        }

        @java.lang.Override
        public _FinalStage awsXmlSelector(String awsXmlSelector) {
            this.awsXmlSelector = Optional.ofNullable(awsXmlSelector);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "awsXmlSelector", nulls = Nulls.SKIP)
        public _FinalStage awsXmlSelector(Optional<String> awsXmlSelector) {
            this.awsXmlSelector = awsXmlSelector;
            return this;
        }

        /**
         * <p>Landing page website url</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage websiteUrl(String websiteUrl) {
            this.websiteUrl = Optional.ofNullable(websiteUrl);
            return this;
        }

        /**
         * <p>Landing page website url</p>
         */
        @java.lang.Override
        @JsonSetter(value = "websiteUrl", nulls = Nulls.SKIP)
        public _FinalStage websiteUrl(Optional<String> websiteUrl) {
            this.websiteUrl = websiteUrl;
            return this;
        }

        /**
         * <p>Release notes or changelog url</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage updatesUrl(String updatesUrl) {
            this.updatesUrl = Optional.ofNullable(updatesUrl);
            return this;
        }

        /**
         * <p>Release notes or changelog url</p>
         */
        @java.lang.Override
        @JsonSetter(value = "updatesUrl", nulls = Nulls.SKIP)
        public _FinalStage updatesUrl(Optional<String> updatesUrl) {
            this.updatesUrl = updatesUrl;
            return this;
        }

        /**
         * <p>Type or category of technology</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage type(Nullable<CatalogTechnologyTypeNullable> type) {
            if (type.isNull()) {
                this.type = null;
            } else if (type.isEmpty()) {
                this.type = Optional.empty();
            } else {
                this.type = Optional.of(type.get());
            }
            return this;
        }

        /**
         * <p>Type or category of technology</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage type(CatalogTechnologyTypeNullable type) {
            this.type = Optional.ofNullable(type);
            return this;
        }

        /**
         * <p>Type or category of technology</p>
         */
        @java.lang.Override
        @JsonSetter(value = "type", nulls = Nulls.SKIP)
        public _FinalStage type(Optional<CatalogTechnologyTypeNullable> type) {
            this.type = type;
            return this;
        }

        /**
         * <p>Current status of the technology, including pending review, approved, and rejected. Approved technologies are visible to all users.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage status(CatalogTechnologyStatus status) {
            this.status = Optional.ofNullable(status);
            return this;
        }

        /**
         * <p>Current status of the technology, including pending review, approved, and rejected. Approved technologies are visible to all users.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "status", nulls = Nulls.SKIP)
        public _FinalStage status(Optional<CatalogTechnologyStatus> status) {
            this.status = status;
            return this;
        }

        /**
         * <p>Restriction on which model object or connections this technology can be added to</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage restrictions(Nullable<List<CatalogRestriction>> restrictions) {
            if (restrictions.isNull()) {
                this.restrictions = null;
            } else if (restrictions.isEmpty()) {
                this.restrictions = Optional.empty();
            } else {
                this.restrictions = Optional.of(restrictions.get());
            }
            return this;
        }

        /**
         * <p>Restriction on which model object or connections this technology can be added to</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage restrictions(List<CatalogRestriction> restrictions) {
            this.restrictions = Optional.ofNullable(restrictions);
            return this;
        }

        /**
         * <p>Restriction on which model object or connections this technology can be added to</p>
         */
        @java.lang.Override
        @JsonSetter(value = "restrictions", nulls = Nulls.SKIP)
        public _FinalStage restrictions(Optional<List<CatalogRestriction>> restrictions) {
            this.restrictions = restrictions;
            return this;
        }

        /**
         * <p>If rejected, the reason why</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage rejectionReason(CatalogTechnologyReviewRejectionReason rejectionReason) {
            this.rejectionReason = Optional.ofNullable(rejectionReason);
            return this;
        }

        /**
         * <p>If rejected, the reason why</p>
         */
        @java.lang.Override
        @JsonSetter(value = "rejectionReason", nulls = Nulls.SKIP)
        public _FinalStage rejectionReason(Optional<CatalogTechnologyReviewRejectionReason> rejectionReason) {
            this.rejectionReason = rejectionReason;
            return this;
        }

        /**
         * <p>If rejected, detail description of why</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage rejectionMessage(String rejectionMessage) {
            this.rejectionMessage = Optional.ofNullable(rejectionMessage);
            return this;
        }

        /**
         * <p>If rejected, detail description of why</p>
         */
        @java.lang.Override
        @JsonSetter(value = "rejectionMessage", nulls = Nulls.SKIP)
        public _FinalStage rejectionMessage(Optional<String> rejectionMessage) {
            this.rejectionMessage = rejectionMessage;
            return this;
        }

        /**
         * <p>Service provider that provides this technology</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage provider(Nullable<CatalogProviderNullable> provider) {
            if (provider.isNull()) {
                this.provider = null;
            } else if (provider.isEmpty()) {
                this.provider = Optional.empty();
            } else {
                this.provider = Optional.of(provider.get());
            }
            return this;
        }

        /**
         * <p>Service provider that provides this technology</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage provider(CatalogProviderNullable provider) {
            this.provider = Optional.ofNullable(provider);
            return this;
        }

        /**
         * <p>Service provider that provides this technology</p>
         */
        @java.lang.Override
        @JsonSetter(value = "provider", nulls = Nulls.SKIP)
        public _FinalStage provider(Optional<CatalogProviderNullable> provider) {
            this.provider = provider;
            return this;
        }

        /**
         * <p>Short one or two word name to show in places with limited space</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage nameShort(String nameShort) {
            this.nameShort = Optional.ofNullable(nameShort);
            return this;
        }

        /**
         * <p>Short one or two word name to show in places with limited space</p>
         */
        @java.lang.Override
        @JsonSetter(value = "nameShort", nulls = Nulls.SKIP)
        public _FinalStage nameShort(Optional<String> nameShort) {
            this.nameShort = nameShort;
            return this;
        }

        /**
         * <p>Icon that only works on light backgrounds</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage iconUrlLight(Nullable<String> iconUrlLight) {
            if (iconUrlLight.isNull()) {
                this.iconUrlLight = null;
            } else if (iconUrlLight.isEmpty()) {
                this.iconUrlLight = Optional.empty();
            } else {
                this.iconUrlLight = Optional.of(iconUrlLight.get());
            }
            return this;
        }

        /**
         * <p>Icon that only works on light backgrounds</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage iconUrlLight(String iconUrlLight) {
            this.iconUrlLight = Optional.ofNullable(iconUrlLight);
            return this;
        }

        /**
         * <p>Icon that only works on light backgrounds</p>
         */
        @java.lang.Override
        @JsonSetter(value = "iconUrlLight", nulls = Nulls.SKIP)
        public _FinalStage iconUrlLight(Optional<String> iconUrlLight) {
            this.iconUrlLight = iconUrlLight;
            return this;
        }

        /**
         * <p>Icon that only works on dark backgrounds</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage iconUrlDark(Nullable<String> iconUrlDark) {
            if (iconUrlDark.isNull()) {
                this.iconUrlDark = null;
            } else if (iconUrlDark.isEmpty()) {
                this.iconUrlDark = Optional.empty();
            } else {
                this.iconUrlDark = Optional.of(iconUrlDark.get());
            }
            return this;
        }

        /**
         * <p>Icon that only works on dark backgrounds</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage iconUrlDark(String iconUrlDark) {
            this.iconUrlDark = Optional.ofNullable(iconUrlDark);
            return this;
        }

        /**
         * <p>Icon that only works on dark backgrounds</p>
         */
        @java.lang.Override
        @JsonSetter(value = "iconUrlDark", nulls = Nulls.SKIP)
        public _FinalStage iconUrlDark(Optional<String> iconUrlDark) {
            this.iconUrlDark = iconUrlDark;
            return this;
        }

        /**
         * <p>Documentation or readme url</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage docsUrl(String docsUrl) {
            this.docsUrl = Optional.ofNullable(docsUrl);
            return this;
        }

        /**
         * <p>Documentation or readme url</p>
         */
        @java.lang.Override
        @JsonSetter(value = "docsUrl", nulls = Nulls.SKIP)
        public _FinalStage docsUrl(Optional<String> docsUrl) {
            this.docsUrl = docsUrl;
            return this;
        }

        /**
         * <p>Technical description for the technology, avoid marketing language</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage description(String description) {
            this.description = Optional.ofNullable(description);
            return this;
        }

        /**
         * <p>Technical description for the technology, avoid marketing language</p>
         */
        @java.lang.Override
        @JsonSetter(value = "description", nulls = Nulls.SKIP)
        public _FinalStage description(Optional<String> description) {
            this.description = description;
            return this;
        }

        @java.lang.Override
        public _FinalStage deprecatedAt(OffsetDateTime deprecatedAt) {
            this.deprecatedAt = Optional.ofNullable(deprecatedAt);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "deprecatedAt", nulls = Nulls.SKIP)
        public _FinalStage deprecatedAt(Optional<OffsetDateTime> deprecatedAt) {
            this.deprecatedAt = deprecatedAt;
            return this;
        }

        @java.lang.Override
        public _FinalStage category(String category) {
            this.category = Optional.ofNullable(category);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "category", nulls = Nulls.SKIP)
        public _FinalStage category(Optional<String> category) {
            this.category = category;
            return this;
        }

        @java.lang.Override
        public CatalogTechnology build() {
            return new CatalogTechnology(
                    category,
                    color,
                    deprecatedAt,
                    description,
                    docsUrl,
                    iconUrlDark,
                    iconUrlLight,
                    name,
                    nameShort,
                    provider,
                    rejectionMessage,
                    rejectionReason,
                    restrictions,
                    status,
                    type,
                    updatesUrl,
                    websiteUrl,
                    awsXmlSelector,
                    azureUpdatesKeyword,
                    createdAt,
                    createdBy,
                    createdById,
                    defaultSlug,
                    deletedAt,
                    deletedBy,
                    deletedById,
                    disabled,
                    iconUrl,
                    id,
                    organizationId,
                    slugs,
                    updatedAt,
                    updatedBy,
                    updatedById,
                    updatesXmlUrl,
                    additionalProperties);
        }
    }
}
