/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class CatalogSuggestionBrandLogoFormatFormat {
    public static final CatalogSuggestionBrandLogoFormatFormat WEBP =
            new CatalogSuggestionBrandLogoFormatFormat(Value.WEBP, "webp");

    public static final CatalogSuggestionBrandLogoFormatFormat JPEG =
            new CatalogSuggestionBrandLogoFormatFormat(Value.JPEG, "jpeg");

    public static final CatalogSuggestionBrandLogoFormatFormat SVG =
            new CatalogSuggestionBrandLogoFormatFormat(Value.SVG, "svg");

    public static final CatalogSuggestionBrandLogoFormatFormat PNG =
            new CatalogSuggestionBrandLogoFormatFormat(Value.PNG, "png");

    private final Value value;

    private final String string;

    CatalogSuggestionBrandLogoFormatFormat(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof CatalogSuggestionBrandLogoFormatFormat
                        && this.string.equals(((CatalogSuggestionBrandLogoFormatFormat) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case WEBP:
                return visitor.visitWebp();
            case JPEG:
                return visitor.visitJpeg();
            case SVG:
                return visitor.visitSvg();
            case PNG:
                return visitor.visitPng();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static CatalogSuggestionBrandLogoFormatFormat valueOf(String value) {
        switch (value) {
            case "webp":
                return WEBP;
            case "jpeg":
                return JPEG;
            case "svg":
                return SVG;
            case "png":
                return PNG;
            default:
                return new CatalogSuggestionBrandLogoFormatFormat(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        SVG,

        PNG,

        WEBP,

        JPEG,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitSvg();

        T visitPng();

        T visitWebp();

        T visitJpeg();

        T visitUnknown(String unknownType);
    }
}
