/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.icepanel.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DiagramFilter.Builder.class)
public final class DiagramFilter {
    private final Optional<Boolean> empty;

    private final Optional<DiagramFilterHandleId> handleId;

    private final Optional<Map<String, String>> labels;

    private final Optional<String> modelId;

    private final Optional<String> name;

    private final Optional<Boolean> pinned;

    private final Optional<DiagramFilterStatus> status;

    private final Optional<DiagramFilterType> type;

    private final Map<String, Object> additionalProperties;

    private DiagramFilter(
            Optional<Boolean> empty,
            Optional<DiagramFilterHandleId> handleId,
            Optional<Map<String, String>> labels,
            Optional<String> modelId,
            Optional<String> name,
            Optional<Boolean> pinned,
            Optional<DiagramFilterStatus> status,
            Optional<DiagramFilterType> type,
            Map<String, Object> additionalProperties) {
        this.empty = empty;
        this.handleId = handleId;
        this.labels = labels;
        this.modelId = modelId;
        this.name = name;
        this.pinned = pinned;
        this.status = status;
        this.type = type;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Filter diagrams that contain no objects
     */
    @JsonProperty("empty")
    public Optional<Boolean> getEmpty() {
        return empty;
    }

    @JsonProperty("handleId")
    public Optional<DiagramFilterHandleId> getHandleId() {
        return handleId;
    }

    @JsonProperty("labels")
    public Optional<Map<String, String>> getLabels() {
        return labels;
    }

    @JsonProperty("modelId")
    public Optional<String> getModelId() {
        return modelId;
    }

    @JsonProperty("name")
    public Optional<String> getName() {
        return name;
    }

    @JsonProperty("pinned")
    public Optional<Boolean> getPinned() {
        return pinned;
    }

    @JsonProperty("status")
    public Optional<DiagramFilterStatus> getStatus() {
        return status;
    }

    @JsonProperty("type")
    public Optional<DiagramFilterType> getType() {
        return type;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DiagramFilter && equalTo((DiagramFilter) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DiagramFilter other) {
        return empty.equals(other.empty)
                && handleId.equals(other.handleId)
                && labels.equals(other.labels)
                && modelId.equals(other.modelId)
                && name.equals(other.name)
                && pinned.equals(other.pinned)
                && status.equals(other.status)
                && type.equals(other.type);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.empty, this.handleId, this.labels, this.modelId, this.name, this.pinned, this.status, this.type);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Boolean> empty = Optional.empty();

        private Optional<DiagramFilterHandleId> handleId = Optional.empty();

        private Optional<Map<String, String>> labels = Optional.empty();

        private Optional<String> modelId = Optional.empty();

        private Optional<String> name = Optional.empty();

        private Optional<Boolean> pinned = Optional.empty();

        private Optional<DiagramFilterStatus> status = Optional.empty();

        private Optional<DiagramFilterType> type = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(DiagramFilter other) {
            empty(other.getEmpty());
            handleId(other.getHandleId());
            labels(other.getLabels());
            modelId(other.getModelId());
            name(other.getName());
            pinned(other.getPinned());
            status(other.getStatus());
            type(other.getType());
            return this;
        }

        /**
         * <p>Filter diagrams that contain no objects</p>
         */
        @JsonSetter(value = "empty", nulls = Nulls.SKIP)
        public Builder empty(Optional<Boolean> empty) {
            this.empty = empty;
            return this;
        }

        public Builder empty(Boolean empty) {
            this.empty = Optional.ofNullable(empty);
            return this;
        }

        @JsonSetter(value = "handleId", nulls = Nulls.SKIP)
        public Builder handleId(Optional<DiagramFilterHandleId> handleId) {
            this.handleId = handleId;
            return this;
        }

        public Builder handleId(DiagramFilterHandleId handleId) {
            this.handleId = Optional.ofNullable(handleId);
            return this;
        }

        @JsonSetter(value = "labels", nulls = Nulls.SKIP)
        public Builder labels(Optional<Map<String, String>> labels) {
            this.labels = labels;
            return this;
        }

        public Builder labels(Map<String, String> labels) {
            this.labels = Optional.ofNullable(labels);
            return this;
        }

        @JsonSetter(value = "modelId", nulls = Nulls.SKIP)
        public Builder modelId(Optional<String> modelId) {
            this.modelId = modelId;
            return this;
        }

        public Builder modelId(String modelId) {
            this.modelId = Optional.ofNullable(modelId);
            return this;
        }

        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public Builder name(Optional<String> name) {
            this.name = name;
            return this;
        }

        public Builder name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        @JsonSetter(value = "pinned", nulls = Nulls.SKIP)
        public Builder pinned(Optional<Boolean> pinned) {
            this.pinned = pinned;
            return this;
        }

        public Builder pinned(Boolean pinned) {
            this.pinned = Optional.ofNullable(pinned);
            return this;
        }

        @JsonSetter(value = "status", nulls = Nulls.SKIP)
        public Builder status(Optional<DiagramFilterStatus> status) {
            this.status = status;
            return this;
        }

        public Builder status(DiagramFilterStatus status) {
            this.status = Optional.ofNullable(status);
            return this;
        }

        @JsonSetter(value = "type", nulls = Nulls.SKIP)
        public Builder type(Optional<DiagramFilterType> type) {
            this.type = type;
            return this;
        }

        public Builder type(DiagramFilterType type) {
            this.type = Optional.ofNullable(type);
            return this;
        }

        public DiagramFilter build() {
            return new DiagramFilter(
                    empty, handleId, labels, modelId, name, pinned, status, type, additionalProperties);
        }
    }
}
