/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.icepanel.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DiagramContentPartial.Builder.class)
public final class DiagramContentPartial {
    private final Optional<DiagramContentPartialComments> comments;

    private final Optional<Double> commit;

    private final Optional<DiagramContentPartialConnections> connections;

    private final Optional<DiagramContentPartialObjects> objects;

    private final Map<String, Object> additionalProperties;

    private DiagramContentPartial(
            Optional<DiagramContentPartialComments> comments,
            Optional<Double> commit,
            Optional<DiagramContentPartialConnections> connections,
            Optional<DiagramContentPartialObjects> objects,
            Map<String, Object> additionalProperties) {
        this.comments = comments;
        this.commit = commit;
        this.connections = connections;
        this.objects = objects;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("comments")
    public Optional<DiagramContentPartialComments> getComments() {
        return comments;
    }

    @JsonProperty("commit")
    public Optional<Double> getCommit() {
        return commit;
    }

    @JsonProperty("connections")
    public Optional<DiagramContentPartialConnections> getConnections() {
        return connections;
    }

    @JsonProperty("objects")
    public Optional<DiagramContentPartialObjects> getObjects() {
        return objects;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DiagramContentPartial && equalTo((DiagramContentPartial) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DiagramContentPartial other) {
        return comments.equals(other.comments)
                && commit.equals(other.commit)
                && connections.equals(other.connections)
                && objects.equals(other.objects);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.comments, this.commit, this.connections, this.objects);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<DiagramContentPartialComments> comments = Optional.empty();

        private Optional<Double> commit = Optional.empty();

        private Optional<DiagramContentPartialConnections> connections = Optional.empty();

        private Optional<DiagramContentPartialObjects> objects = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(DiagramContentPartial other) {
            comments(other.getComments());
            commit(other.getCommit());
            connections(other.getConnections());
            objects(other.getObjects());
            return this;
        }

        @JsonSetter(value = "comments", nulls = Nulls.SKIP)
        public Builder comments(Optional<DiagramContentPartialComments> comments) {
            this.comments = comments;
            return this;
        }

        public Builder comments(DiagramContentPartialComments comments) {
            this.comments = Optional.ofNullable(comments);
            return this;
        }

        @JsonSetter(value = "commit", nulls = Nulls.SKIP)
        public Builder commit(Optional<Double> commit) {
            this.commit = commit;
            return this;
        }

        public Builder commit(Double commit) {
            this.commit = Optional.ofNullable(commit);
            return this;
        }

        @JsonSetter(value = "connections", nulls = Nulls.SKIP)
        public Builder connections(Optional<DiagramContentPartialConnections> connections) {
            this.connections = connections;
            return this;
        }

        public Builder connections(DiagramContentPartialConnections connections) {
            this.connections = Optional.ofNullable(connections);
            return this;
        }

        @JsonSetter(value = "objects", nulls = Nulls.SKIP)
        public Builder objects(Optional<DiagramContentPartialObjects> objects) {
            this.objects = objects;
            return this;
        }

        public Builder objects(DiagramContentPartialObjects objects) {
            this.objects = Optional.ofNullable(objects);
            return this;
        }

        public DiagramContentPartial build() {
            return new DiagramContentPartial(comments, commit, connections, objects, additionalProperties);
        }
    }
}
