/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.icepanel.api.core.Nullable;
import com.icepanel.api.core.NullableNonemptyFilter;
import com.icepanel.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DiagramConnectionPartial.Builder.class)
public final class DiagramConnectionPartial {
    private final Optional<String> id;

    private final Optional<Double> labelPosition;

    private final Optional<LineShape> lineShape;

    private final Optional<String> modelId;

    private final Optional<DiagramObjectConnector> originConnector;

    private final Optional<String> originId;

    private final Optional<List<DiagramConnectionPartialPointsItem>> points;

    private final Optional<DiagramObjectConnector> targetConnector;

    private final Optional<String> targetId;

    private final Map<String, Object> additionalProperties;

    private DiagramConnectionPartial(
            Optional<String> id,
            Optional<Double> labelPosition,
            Optional<LineShape> lineShape,
            Optional<String> modelId,
            Optional<DiagramObjectConnector> originConnector,
            Optional<String> originId,
            Optional<List<DiagramConnectionPartialPointsItem>> points,
            Optional<DiagramObjectConnector> targetConnector,
            Optional<String> targetId,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.labelPosition = labelPosition;
        this.lineShape = lineShape;
        this.modelId = modelId;
        this.originConnector = originConnector;
        this.originId = originId;
        this.points = points;
        this.targetConnector = targetConnector;
        this.targetId = targetId;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("id")
    public Optional<String> getId() {
        return id;
    }

    /**
     * @return The percentage along the line where the label should be placed
     */
    @JsonProperty("labelPosition")
    public Optional<Double> getLabelPosition() {
        return labelPosition;
    }

    @JsonProperty("lineShape")
    public Optional<LineShape> getLineShape() {
        return lineShape;
    }

    @JsonIgnore
    public Optional<String> getModelId() {
        if (modelId == null) {
            return Optional.empty();
        }
        return modelId;
    }

    @JsonIgnore
    public Optional<DiagramObjectConnector> getOriginConnector() {
        if (originConnector == null) {
            return Optional.empty();
        }
        return originConnector;
    }

    @JsonIgnore
    public Optional<String> getOriginId() {
        if (originId == null) {
            return Optional.empty();
        }
        return originId;
    }

    @JsonProperty("points")
    public Optional<List<DiagramConnectionPartialPointsItem>> getPoints() {
        return points;
    }

    @JsonIgnore
    public Optional<DiagramObjectConnector> getTargetConnector() {
        if (targetConnector == null) {
            return Optional.empty();
        }
        return targetConnector;
    }

    @JsonIgnore
    public Optional<String> getTargetId() {
        if (targetId == null) {
            return Optional.empty();
        }
        return targetId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("modelId")
    private Optional<String> _getModelId() {
        return modelId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("originConnector")
    private Optional<DiagramObjectConnector> _getOriginConnector() {
        return originConnector;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("originId")
    private Optional<String> _getOriginId() {
        return originId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("targetConnector")
    private Optional<DiagramObjectConnector> _getTargetConnector() {
        return targetConnector;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("targetId")
    private Optional<String> _getTargetId() {
        return targetId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DiagramConnectionPartial && equalTo((DiagramConnectionPartial) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DiagramConnectionPartial other) {
        return id.equals(other.id)
                && labelPosition.equals(other.labelPosition)
                && lineShape.equals(other.lineShape)
                && modelId.equals(other.modelId)
                && originConnector.equals(other.originConnector)
                && originId.equals(other.originId)
                && points.equals(other.points)
                && targetConnector.equals(other.targetConnector)
                && targetId.equals(other.targetId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.id,
                this.labelPosition,
                this.lineShape,
                this.modelId,
                this.originConnector,
                this.originId,
                this.points,
                this.targetConnector,
                this.targetId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> id = Optional.empty();

        private Optional<Double> labelPosition = Optional.empty();

        private Optional<LineShape> lineShape = Optional.empty();

        private Optional<String> modelId = Optional.empty();

        private Optional<DiagramObjectConnector> originConnector = Optional.empty();

        private Optional<String> originId = Optional.empty();

        private Optional<List<DiagramConnectionPartialPointsItem>> points = Optional.empty();

        private Optional<DiagramObjectConnector> targetConnector = Optional.empty();

        private Optional<String> targetId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(DiagramConnectionPartial other) {
            id(other.getId());
            labelPosition(other.getLabelPosition());
            lineShape(other.getLineShape());
            modelId(other.getModelId());
            originConnector(other.getOriginConnector());
            originId(other.getOriginId());
            points(other.getPoints());
            targetConnector(other.getTargetConnector());
            targetId(other.getTargetId());
            return this;
        }

        @JsonSetter(value = "id", nulls = Nulls.SKIP)
        public Builder id(Optional<String> id) {
            this.id = id;
            return this;
        }

        public Builder id(String id) {
            this.id = Optional.ofNullable(id);
            return this;
        }

        /**
         * <p>The percentage along the line where the label should be placed</p>
         */
        @JsonSetter(value = "labelPosition", nulls = Nulls.SKIP)
        public Builder labelPosition(Optional<Double> labelPosition) {
            this.labelPosition = labelPosition;
            return this;
        }

        public Builder labelPosition(Double labelPosition) {
            this.labelPosition = Optional.ofNullable(labelPosition);
            return this;
        }

        @JsonSetter(value = "lineShape", nulls = Nulls.SKIP)
        public Builder lineShape(Optional<LineShape> lineShape) {
            this.lineShape = lineShape;
            return this;
        }

        public Builder lineShape(LineShape lineShape) {
            this.lineShape = Optional.ofNullable(lineShape);
            return this;
        }

        @JsonSetter(value = "modelId", nulls = Nulls.SKIP)
        public Builder modelId(Optional<String> modelId) {
            this.modelId = modelId;
            return this;
        }

        public Builder modelId(String modelId) {
            this.modelId = Optional.ofNullable(modelId);
            return this;
        }

        public Builder modelId(Nullable<String> modelId) {
            if (modelId.isNull()) {
                this.modelId = null;
            } else if (modelId.isEmpty()) {
                this.modelId = Optional.empty();
            } else {
                this.modelId = Optional.of(modelId.get());
            }
            return this;
        }

        @JsonSetter(value = "originConnector", nulls = Nulls.SKIP)
        public Builder originConnector(Optional<DiagramObjectConnector> originConnector) {
            this.originConnector = originConnector;
            return this;
        }

        public Builder originConnector(DiagramObjectConnector originConnector) {
            this.originConnector = Optional.ofNullable(originConnector);
            return this;
        }

        public Builder originConnector(Nullable<DiagramObjectConnector> originConnector) {
            if (originConnector.isNull()) {
                this.originConnector = null;
            } else if (originConnector.isEmpty()) {
                this.originConnector = Optional.empty();
            } else {
                this.originConnector = Optional.of(originConnector.get());
            }
            return this;
        }

        @JsonSetter(value = "originId", nulls = Nulls.SKIP)
        public Builder originId(Optional<String> originId) {
            this.originId = originId;
            return this;
        }

        public Builder originId(String originId) {
            this.originId = Optional.ofNullable(originId);
            return this;
        }

        public Builder originId(Nullable<String> originId) {
            if (originId.isNull()) {
                this.originId = null;
            } else if (originId.isEmpty()) {
                this.originId = Optional.empty();
            } else {
                this.originId = Optional.of(originId.get());
            }
            return this;
        }

        @JsonSetter(value = "points", nulls = Nulls.SKIP)
        public Builder points(Optional<List<DiagramConnectionPartialPointsItem>> points) {
            this.points = points;
            return this;
        }

        public Builder points(List<DiagramConnectionPartialPointsItem> points) {
            this.points = Optional.ofNullable(points);
            return this;
        }

        @JsonSetter(value = "targetConnector", nulls = Nulls.SKIP)
        public Builder targetConnector(Optional<DiagramObjectConnector> targetConnector) {
            this.targetConnector = targetConnector;
            return this;
        }

        public Builder targetConnector(DiagramObjectConnector targetConnector) {
            this.targetConnector = Optional.ofNullable(targetConnector);
            return this;
        }

        public Builder targetConnector(Nullable<DiagramObjectConnector> targetConnector) {
            if (targetConnector.isNull()) {
                this.targetConnector = null;
            } else if (targetConnector.isEmpty()) {
                this.targetConnector = Optional.empty();
            } else {
                this.targetConnector = Optional.of(targetConnector.get());
            }
            return this;
        }

        @JsonSetter(value = "targetId", nulls = Nulls.SKIP)
        public Builder targetId(Optional<String> targetId) {
            this.targetId = targetId;
            return this;
        }

        public Builder targetId(String targetId) {
            this.targetId = Optional.ofNullable(targetId);
            return this;
        }

        public Builder targetId(Nullable<String> targetId) {
            if (targetId.isNull()) {
                this.targetId = null;
            } else if (targetId.isEmpty()) {
                this.targetId = Optional.empty();
            } else {
                this.targetId = Optional.of(targetId.get());
            }
            return this;
        }

        public DiagramConnectionPartial build() {
            return new DiagramConnectionPartial(
                    id,
                    labelPosition,
                    lineShape,
                    modelId,
                    originConnector,
                    originId,
                    points,
                    targetConnector,
                    targetId,
                    additionalProperties);
        }
    }
}
