/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.icepanel.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DraftTaskCommentReplyCreate.Builder.class)
public final class DraftTaskCommentReplyCreate {
    private final String commentId;

    private final String entityId;

    private final CommentReplyRequired props;

    private final DraftTaskCommentReplyCreateType type;

    private final Map<String, Object> additionalProperties;

    private DraftTaskCommentReplyCreate(
            String commentId,
            String entityId,
            CommentReplyRequired props,
            DraftTaskCommentReplyCreateType type,
            Map<String, Object> additionalProperties) {
        this.commentId = commentId;
        this.entityId = entityId;
        this.props = props;
        this.type = type;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("commentId")
    public String getCommentId() {
        return commentId;
    }

    @JsonProperty("entityId")
    public String getEntityId() {
        return entityId;
    }

    @JsonProperty("props")
    public CommentReplyRequired getProps() {
        return props;
    }

    @JsonProperty("type")
    public DraftTaskCommentReplyCreateType getType() {
        return type;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DraftTaskCommentReplyCreate && equalTo((DraftTaskCommentReplyCreate) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DraftTaskCommentReplyCreate other) {
        return commentId.equals(other.commentId)
                && entityId.equals(other.entityId)
                && props.equals(other.props)
                && type.equals(other.type);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.commentId, this.entityId, this.props, this.type);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static CommentIdStage builder() {
        return new Builder();
    }

    public interface CommentIdStage {
        EntityIdStage commentId(@NotNull String commentId);

        Builder from(DraftTaskCommentReplyCreate other);
    }

    public interface EntityIdStage {
        PropsStage entityId(@NotNull String entityId);
    }

    public interface PropsStage {
        TypeStage props(@NotNull CommentReplyRequired props);
    }

    public interface TypeStage {
        _FinalStage type(@NotNull DraftTaskCommentReplyCreateType type);
    }

    public interface _FinalStage {
        DraftTaskCommentReplyCreate build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements CommentIdStage, EntityIdStage, PropsStage, TypeStage, _FinalStage {
        private String commentId;

        private String entityId;

        private CommentReplyRequired props;

        private DraftTaskCommentReplyCreateType type;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(DraftTaskCommentReplyCreate other) {
            commentId(other.getCommentId());
            entityId(other.getEntityId());
            props(other.getProps());
            type(other.getType());
            return this;
        }

        @java.lang.Override
        @JsonSetter("commentId")
        public EntityIdStage commentId(@NotNull String commentId) {
            this.commentId = Objects.requireNonNull(commentId, "commentId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("entityId")
        public PropsStage entityId(@NotNull String entityId) {
            this.entityId = Objects.requireNonNull(entityId, "entityId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("props")
        public TypeStage props(@NotNull CommentReplyRequired props) {
            this.props = Objects.requireNonNull(props, "props must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("type")
        public _FinalStage type(@NotNull DraftTaskCommentReplyCreateType type) {
            this.type = Objects.requireNonNull(type, "type must not be null");
            return this;
        }

        @java.lang.Override
        public DraftTaskCommentReplyCreate build() {
            return new DraftTaskCommentReplyCreate(commentId, entityId, props, type, additionalProperties);
        }
    }
}
