/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.icepanel.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DraftTaskDiagramCreate.Builder.class)
public final class DraftTaskDiagramCreate {
    private final String entityId;

    private final DraftTaskDiagramCreateProps props;

    private final DraftTaskDiagramCreateType type;

    private final Map<String, Object> additionalProperties;

    private DraftTaskDiagramCreate(
            String entityId,
            DraftTaskDiagramCreateProps props,
            DraftTaskDiagramCreateType type,
            Map<String, Object> additionalProperties) {
        this.entityId = entityId;
        this.props = props;
        this.type = type;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("entityId")
    public String getEntityId() {
        return entityId;
    }

    @JsonProperty("props")
    public DraftTaskDiagramCreateProps getProps() {
        return props;
    }

    @JsonProperty("type")
    public DraftTaskDiagramCreateType getType() {
        return type;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DraftTaskDiagramCreate && equalTo((DraftTaskDiagramCreate) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DraftTaskDiagramCreate other) {
        return entityId.equals(other.entityId) && props.equals(other.props) && type.equals(other.type);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.entityId, this.props, this.type);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static EntityIdStage builder() {
        return new Builder();
    }

    public interface EntityIdStage {
        PropsStage entityId(@NotNull String entityId);

        Builder from(DraftTaskDiagramCreate other);
    }

    public interface PropsStage {
        TypeStage props(@NotNull DraftTaskDiagramCreateProps props);
    }

    public interface TypeStage {
        _FinalStage type(@NotNull DraftTaskDiagramCreateType type);
    }

    public interface _FinalStage {
        DraftTaskDiagramCreate build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements EntityIdStage, PropsStage, TypeStage, _FinalStage {
        private String entityId;

        private DraftTaskDiagramCreateProps props;

        private DraftTaskDiagramCreateType type;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(DraftTaskDiagramCreate other) {
            entityId(other.getEntityId());
            props(other.getProps());
            type(other.getType());
            return this;
        }

        @java.lang.Override
        @JsonSetter("entityId")
        public PropsStage entityId(@NotNull String entityId) {
            this.entityId = Objects.requireNonNull(entityId, "entityId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("props")
        public TypeStage props(@NotNull DraftTaskDiagramCreateProps props) {
            this.props = Objects.requireNonNull(props, "props must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("type")
        public _FinalStage type(@NotNull DraftTaskDiagramCreateType type) {
            this.type = Objects.requireNonNull(type, "type must not be null");
            return this;
        }

        @java.lang.Override
        public DraftTaskDiagramCreate build() {
            return new DraftTaskDiagramCreate(entityId, props, type, additionalProperties);
        }
    }
}
