/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class RealityConnectorBitbucketServerFileType {
    public static final RealityConnectorBitbucketServerFileType BITBUCKET_SERVER_FILE =
            new RealityConnectorBitbucketServerFileType(Value.BITBUCKET_SERVER_FILE, "bitbucket-server-file");

    private final Value value;

    private final String string;

    RealityConnectorBitbucketServerFileType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof RealityConnectorBitbucketServerFileType
                        && this.string.equals(((RealityConnectorBitbucketServerFileType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case BITBUCKET_SERVER_FILE:
                return visitor.visitBitbucketServerFile();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static RealityConnectorBitbucketServerFileType valueOf(String value) {
        switch (value) {
            case "bitbucket-server-file":
                return BITBUCKET_SERVER_FILE;
            default:
                return new RealityConnectorBitbucketServerFileType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        BITBUCKET_SERVER_FILE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitBitbucketServerFile();

        T visitUnknown(String unknownType);
    }
}
