/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class RealityConnectorBitbucketBranchType {
    public static final RealityConnectorBitbucketBranchType BITBUCKET_BRANCH =
            new RealityConnectorBitbucketBranchType(Value.BITBUCKET_BRANCH, "bitbucket-branch");

    private final Value value;

    private final String string;

    RealityConnectorBitbucketBranchType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof RealityConnectorBitbucketBranchType
                        && this.string.equals(((RealityConnectorBitbucketBranchType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case BITBUCKET_BRANCH:
                return visitor.visitBitbucketBranch();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static RealityConnectorBitbucketBranchType valueOf(String value) {
        switch (value) {
            case "bitbucket-branch":
                return BITBUCKET_BRANCH;
            default:
                return new RealityConnectorBitbucketBranchType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        BITBUCKET_BRANCH,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitBitbucketBranch();

        T visitUnknown(String unknownType);
    }
}
