/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.icepanel.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TagGroupFilter.Builder.class)
public final class TagGroupFilter {
    private final Optional<TagGroupFilterHandleId> handleId;

    private final Optional<Map<String, String>> labels;

    private final Optional<String> name;

    private final Map<String, Object> additionalProperties;

    private TagGroupFilter(
            Optional<TagGroupFilterHandleId> handleId,
            Optional<Map<String, String>> labels,
            Optional<String> name,
            Map<String, Object> additionalProperties) {
        this.handleId = handleId;
        this.labels = labels;
        this.name = name;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("handleId")
    public Optional<TagGroupFilterHandleId> getHandleId() {
        return handleId;
    }

    @JsonProperty("labels")
    public Optional<Map<String, String>> getLabels() {
        return labels;
    }

    @JsonProperty("name")
    public Optional<String> getName() {
        return name;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TagGroupFilter && equalTo((TagGroupFilter) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TagGroupFilter other) {
        return handleId.equals(other.handleId) && labels.equals(other.labels) && name.equals(other.name);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.handleId, this.labels, this.name);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<TagGroupFilterHandleId> handleId = Optional.empty();

        private Optional<Map<String, String>> labels = Optional.empty();

        private Optional<String> name = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(TagGroupFilter other) {
            handleId(other.getHandleId());
            labels(other.getLabels());
            name(other.getName());
            return this;
        }

        @JsonSetter(value = "handleId", nulls = Nulls.SKIP)
        public Builder handleId(Optional<TagGroupFilterHandleId> handleId) {
            this.handleId = handleId;
            return this;
        }

        public Builder handleId(TagGroupFilterHandleId handleId) {
            this.handleId = Optional.ofNullable(handleId);
            return this;
        }

        @JsonSetter(value = "labels", nulls = Nulls.SKIP)
        public Builder labels(Optional<Map<String, String>> labels) {
            this.labels = labels;
            return this;
        }

        public Builder labels(Map<String, String> labels) {
            this.labels = Optional.ofNullable(labels);
            return this;
        }

        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public Builder name(Optional<String> name) {
            this.name = name;
            return this;
        }

        public Builder name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        public TagGroupFilter build() {
            return new TagGroupFilter(handleId, labels, name, additionalProperties);
        }
    }
}
