/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.versions.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.icepanel.core.ObjectMappers;
import com.icepanel.types.VersionRevert;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = RevertsCreateResponse.Builder.class)
public final class RevertsCreateResponse {
    private final VersionRevert versionRevert;

    private final Map<String, Object> additionalProperties;

    private RevertsCreateResponse(VersionRevert versionRevert, Map<String, Object> additionalProperties) {
        this.versionRevert = versionRevert;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("versionRevert")
    public VersionRevert getVersionRevert() {
        return versionRevert;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof RevertsCreateResponse && equalTo((RevertsCreateResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(RevertsCreateResponse other) {
        return versionRevert.equals(other.versionRevert);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.versionRevert);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static VersionRevertStage builder() {
        return new Builder();
    }

    public interface VersionRevertStage {
        _FinalStage versionRevert(@NotNull VersionRevert versionRevert);

        Builder from(RevertsCreateResponse other);
    }

    public interface _FinalStage {
        RevertsCreateResponse build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements VersionRevertStage, _FinalStage {
        private VersionRevert versionRevert;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(RevertsCreateResponse other) {
            versionRevert(other.getVersionRevert());
            return this;
        }

        @java.lang.Override
        @JsonSetter("versionRevert")
        public _FinalStage versionRevert(@NotNull VersionRevert versionRevert) {
            this.versionRevert = Objects.requireNonNull(versionRevert, "versionRevert must not be null");
            return this;
        }

        @java.lang.Override
        public RevertsCreateResponse build() {
            return new RevertsCreateResponse(versionRevert, additionalProperties);
        }
    }
}
