/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.api.resources.comments;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.icepanel.api.core.ClientOptions;
import com.icepanel.api.core.IcePanelClientApiException;
import com.icepanel.api.core.IcePanelClientException;
import com.icepanel.api.core.IcePanelClientHttpResponse;
import com.icepanel.api.core.MediaTypes;
import com.icepanel.api.core.ObjectMappers;
import com.icepanel.api.core.QueryStringMapper;
import com.icepanel.api.core.RequestOptions;
import com.icepanel.api.errors.ConflictError;
import com.icepanel.api.errors.InternalServerError;
import com.icepanel.api.errors.NotFoundError;
import com.icepanel.api.errors.UnauthorizedError;
import com.icepanel.api.errors.UnprocessableEntityError;
import com.icepanel.api.resources.comments.requests.CommentCreateRequest;
import com.icepanel.api.resources.comments.requests.CommentDeleteRequest;
import com.icepanel.api.resources.comments.requests.CommentFindRequest;
import com.icepanel.api.resources.comments.requests.CommentUpdateRequest;
import com.icepanel.api.resources.comments.requests.CommentUpsertRequest;
import com.icepanel.api.resources.comments.requests.CommentsListRequest;
import com.icepanel.api.resources.comments.types.CommentsCreateResponse;
import com.icepanel.api.resources.comments.types.CommentsDeleteResponse;
import com.icepanel.api.resources.comments.types.CommentsGetResponse;
import com.icepanel.api.resources.comments.types.CommentsListResponse;
import com.icepanel.api.resources.comments.types.CommentsUpdateResponse;
import com.icepanel.api.resources.comments.types.CommentsUpsertResponse;
import com.icepanel.api.types.Error;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawCommentsClient {
    protected final ClientOptions clientOptions;

    public AsyncRawCommentsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    public CompletableFuture<IcePanelClientHttpResponse<CommentsListResponse>> list(
            String landscapeId, String versionId) {
        return list(landscapeId, versionId, CommentsListRequest.builder().build());
    }

    public CompletableFuture<IcePanelClientHttpResponse<CommentsListResponse>> list(
            String landscapeId, String versionId, CommentsListRequest request) {
        return list(landscapeId, versionId, request, null);
    }

    public CompletableFuture<IcePanelClientHttpResponse<CommentsListResponse>> list(
            String landscapeId, String versionId, CommentsListRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("landscapes")
                .addPathSegment(landscapeId)
                .addPathSegments("versions")
                .addPathSegment(versionId)
                .addPathSegments("comments");
        if (request.getStatus().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "status", request.getStatus().get(), true);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<IcePanelClientHttpResponse<CommentsListResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new IcePanelClientHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, CommentsListResponse.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 422:
                                future.completeExceptionally(new UnprocessableEntityError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new IcePanelClientApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(
                            new IcePanelClientException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new IcePanelClientException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    public CompletableFuture<IcePanelClientHttpResponse<CommentsCreateResponse>> create(
            String landscapeId, String versionId, CommentCreateRequest request) {
        return create(landscapeId, versionId, request, null);
    }

    public CompletableFuture<IcePanelClientHttpResponse<CommentsCreateResponse>> create(
            String landscapeId, String versionId, CommentCreateRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("landscapes")
                .addPathSegment(landscapeId)
                .addPathSegments("versions")
                .addPathSegment(versionId)
                .addPathSegments("comments")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request.getBody()), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new IcePanelClientException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<IcePanelClientHttpResponse<CommentsCreateResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new IcePanelClientHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, CommentsCreateResponse.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 422:
                                future.completeExceptionally(new UnprocessableEntityError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new IcePanelClientApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(
                            new IcePanelClientException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new IcePanelClientException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    public CompletableFuture<IcePanelClientHttpResponse<CommentsGetResponse>> get(
            String landscapeId, String versionId, String commentId) {
        return get(
                landscapeId, versionId, commentId, CommentFindRequest.builder().build());
    }

    public CompletableFuture<IcePanelClientHttpResponse<CommentsGetResponse>> get(
            String landscapeId, String versionId, String commentId, CommentFindRequest request) {
        return get(landscapeId, versionId, commentId, request, null);
    }

    public CompletableFuture<IcePanelClientHttpResponse<CommentsGetResponse>> get(
            String landscapeId,
            String versionId,
            String commentId,
            CommentFindRequest request,
            RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("landscapes")
                .addPathSegment(landscapeId)
                .addPathSegments("versions")
                .addPathSegment(versionId)
                .addPathSegments("comments")
                .addPathSegment(commentId)
                .build();
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl)
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<IcePanelClientHttpResponse<CommentsGetResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new IcePanelClientHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, CommentsGetResponse.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 422:
                                future.completeExceptionally(new UnprocessableEntityError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new IcePanelClientApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(
                            new IcePanelClientException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new IcePanelClientException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    public CompletableFuture<IcePanelClientHttpResponse<CommentsUpsertResponse>> upsert(
            String landscapeId, String versionId, String commentId, CommentUpsertRequest request) {
        return upsert(landscapeId, versionId, commentId, request, null);
    }

    public CompletableFuture<IcePanelClientHttpResponse<CommentsUpsertResponse>> upsert(
            String landscapeId,
            String versionId,
            String commentId,
            CommentUpsertRequest request,
            RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("landscapes")
                .addPathSegment(landscapeId)
                .addPathSegments("versions")
                .addPathSegment(versionId)
                .addPathSegments("comments")
                .addPathSegment(commentId)
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request.getBody()), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new IcePanelClientException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("PUT", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<IcePanelClientHttpResponse<CommentsUpsertResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new IcePanelClientHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, CommentsUpsertResponse.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 409:
                                future.completeExceptionally(new ConflictError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 422:
                                future.completeExceptionally(new UnprocessableEntityError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new IcePanelClientApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(
                            new IcePanelClientException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new IcePanelClientException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    public CompletableFuture<IcePanelClientHttpResponse<CommentsDeleteResponse>> delete(
            String landscapeId, String versionId, String commentId) {
        return delete(
                landscapeId,
                versionId,
                commentId,
                CommentDeleteRequest.builder().build());
    }

    public CompletableFuture<IcePanelClientHttpResponse<CommentsDeleteResponse>> delete(
            String landscapeId, String versionId, String commentId, CommentDeleteRequest request) {
        return delete(landscapeId, versionId, commentId, request, null);
    }

    public CompletableFuture<IcePanelClientHttpResponse<CommentsDeleteResponse>> delete(
            String landscapeId,
            String versionId,
            String commentId,
            CommentDeleteRequest request,
            RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("landscapes")
                .addPathSegment(landscapeId)
                .addPathSegments("versions")
                .addPathSegment(versionId)
                .addPathSegments("comments")
                .addPathSegment(commentId)
                .build();
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl)
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<IcePanelClientHttpResponse<CommentsDeleteResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new IcePanelClientHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, CommentsDeleteResponse.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 409:
                                future.completeExceptionally(new ConflictError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 422:
                                future.completeExceptionally(new UnprocessableEntityError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new IcePanelClientApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(
                            new IcePanelClientException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new IcePanelClientException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    public CompletableFuture<IcePanelClientHttpResponse<CommentsUpdateResponse>> update(
            String landscapeId, String versionId, String commentId, CommentUpdateRequest request) {
        return update(landscapeId, versionId, commentId, request, null);
    }

    public CompletableFuture<IcePanelClientHttpResponse<CommentsUpdateResponse>> update(
            String landscapeId,
            String versionId,
            String commentId,
            CommentUpdateRequest request,
            RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("landscapes")
                .addPathSegment(landscapeId)
                .addPathSegments("versions")
                .addPathSegment(versionId)
                .addPathSegments("comments")
                .addPathSegment(commentId)
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request.getBody()), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new IcePanelClientException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("PATCH", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<IcePanelClientHttpResponse<CommentsUpdateResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new IcePanelClientHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, CommentsUpdateResponse.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 409:
                                future.completeExceptionally(new ConflictError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 422:
                                future.completeExceptionally(new UnprocessableEntityError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new IcePanelClientApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(
                            new IcePanelClientException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new IcePanelClientException("Network error executing HTTP request", e));
            }
        });
        return future;
    }
}
