/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.organizations.users.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.icepanel.core.ObjectMappers;
import com.icepanel.types.OrganizationUserInvite;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = InvitesRevokeResponse.Builder.class)
public final class InvitesRevokeResponse {
    private final OrganizationUserInvite organizationUserInvite;

    private final Map<String, Object> additionalProperties;

    private InvitesRevokeResponse(
            OrganizationUserInvite organizationUserInvite, Map<String, Object> additionalProperties) {
        this.organizationUserInvite = organizationUserInvite;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("organizationUserInvite")
    public OrganizationUserInvite getOrganizationUserInvite() {
        return organizationUserInvite;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof InvitesRevokeResponse && equalTo((InvitesRevokeResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(InvitesRevokeResponse other) {
        return organizationUserInvite.equals(other.organizationUserInvite);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.organizationUserInvite);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static OrganizationUserInviteStage builder() {
        return new Builder();
    }

    public interface OrganizationUserInviteStage {
        _FinalStage organizationUserInvite(@NotNull OrganizationUserInvite organizationUserInvite);

        Builder from(InvitesRevokeResponse other);
    }

    public interface _FinalStage {
        InvitesRevokeResponse build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements OrganizationUserInviteStage, _FinalStage {
        private OrganizationUserInvite organizationUserInvite;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(InvitesRevokeResponse other) {
            organizationUserInvite(other.getOrganizationUserInvite());
            return this;
        }

        @java.lang.Override
        @JsonSetter("organizationUserInvite")
        public _FinalStage organizationUserInvite(@NotNull OrganizationUserInvite organizationUserInvite) {
            this.organizationUserInvite =
                    Objects.requireNonNull(organizationUserInvite, "organizationUserInvite must not be null");
            return this;
        }

        @java.lang.Override
        public InvitesRevokeResponse build() {
            return new InvitesRevokeResponse(organizationUserInvite, additionalProperties);
        }
    }
}
