/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.api.resources.versions.reverts;

import com.icepanel.api.core.ClientOptions;
import com.icepanel.api.core.RequestOptions;
import com.icepanel.api.resources.versions.reverts.requests.VersionRevertCreateRequest;
import com.icepanel.api.resources.versions.reverts.requests.VersionRevertFindRequest;
import com.icepanel.api.resources.versions.reverts.requests.VersionRevertUpdateRequest;
import com.icepanel.api.resources.versions.reverts.requests.VersionRevertsListRequest;
import com.icepanel.api.resources.versions.reverts.types.RevertsCreateResponse;
import com.icepanel.api.resources.versions.reverts.types.RevertsGetResponse;
import com.icepanel.api.resources.versions.reverts.types.RevertsListResponse;
import com.icepanel.api.resources.versions.reverts.types.RevertsUpdateResponse;
import java.util.concurrent.CompletableFuture;

public class AsyncRevertsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawRevertsClient rawClient;

    public AsyncRevertsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawRevertsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawRevertsClient withRawResponse() {
        return this.rawClient;
    }

    public CompletableFuture<RevertsListResponse> list(String landscapeId) {
        return this.rawClient.list(landscapeId).thenApply(response -> response.body());
    }

    public CompletableFuture<RevertsListResponse> list(String landscapeId, VersionRevertsListRequest request) {
        return this.rawClient.list(landscapeId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<RevertsListResponse> list(
            String landscapeId, VersionRevertsListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(landscapeId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<RevertsCreateResponse> create(String landscapeId, VersionRevertCreateRequest request) {
        return this.rawClient.create(landscapeId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<RevertsCreateResponse> create(
            String landscapeId, VersionRevertCreateRequest request, RequestOptions requestOptions) {
        return this.rawClient.create(landscapeId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<RevertsGetResponse> get(String landscapeId, String versionRevertId) {
        return this.rawClient.get(landscapeId, versionRevertId).thenApply(response -> response.body());
    }

    public CompletableFuture<RevertsGetResponse> get(
            String landscapeId, String versionRevertId, VersionRevertFindRequest request) {
        return this.rawClient.get(landscapeId, versionRevertId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<RevertsGetResponse> get(
            String landscapeId,
            String versionRevertId,
            VersionRevertFindRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .get(landscapeId, versionRevertId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<RevertsUpdateResponse> update(
            String landscapeId, String versionRevertId, VersionRevertUpdateRequest request) {
        return this.rawClient.update(landscapeId, versionRevertId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<RevertsUpdateResponse> update(
            String landscapeId,
            String versionRevertId,
            VersionRevertUpdateRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .update(landscapeId, versionRevertId, request, requestOptions)
                .thenApply(response -> response.body());
    }
}
