/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.api.resources.versions.reverts;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.icepanel.api.core.ClientOptions;
import com.icepanel.api.core.IcePanelClientApiException;
import com.icepanel.api.core.IcePanelClientException;
import com.icepanel.api.core.IcePanelClientHttpResponse;
import com.icepanel.api.core.MediaTypes;
import com.icepanel.api.core.ObjectMappers;
import com.icepanel.api.core.RequestOptions;
import com.icepanel.api.errors.ForbiddenError;
import com.icepanel.api.errors.InternalServerError;
import com.icepanel.api.errors.NotFoundError;
import com.icepanel.api.errors.UnauthorizedError;
import com.icepanel.api.errors.UnprocessableEntityError;
import com.icepanel.api.resources.versions.reverts.requests.VersionRevertCreateRequest;
import com.icepanel.api.resources.versions.reverts.requests.VersionRevertFindRequest;
import com.icepanel.api.resources.versions.reverts.requests.VersionRevertUpdateRequest;
import com.icepanel.api.resources.versions.reverts.requests.VersionRevertsListRequest;
import com.icepanel.api.resources.versions.reverts.types.RevertsCreateResponse;
import com.icepanel.api.resources.versions.reverts.types.RevertsGetResponse;
import com.icepanel.api.resources.versions.reverts.types.RevertsListResponse;
import com.icepanel.api.resources.versions.reverts.types.RevertsUpdateResponse;
import com.icepanel.api.types.Error;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawRevertsClient {
    protected final ClientOptions clientOptions;

    public RawRevertsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    public IcePanelClientHttpResponse<RevertsListResponse> list(String landscapeId) {
        return list(landscapeId, VersionRevertsListRequest.builder().build());
    }

    public IcePanelClientHttpResponse<RevertsListResponse> list(String landscapeId, VersionRevertsListRequest request) {
        return list(landscapeId, request, null);
    }

    public IcePanelClientHttpResponse<RevertsListResponse> list(
            String landscapeId, VersionRevertsListRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("landscapes")
                .addPathSegment(landscapeId)
                .addPathSegments("version")
                .addPathSegments("reverts")
                .build();
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl)
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new IcePanelClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, RevertsListResponse.class), response);
            }
            try {
                switch (response.code()) {
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 422:
                        throw new UnprocessableEntityError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new IcePanelClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new IcePanelClientException("Network error executing HTTP request", e);
        }
    }

    public IcePanelClientHttpResponse<RevertsCreateResponse> create(
            String landscapeId, VersionRevertCreateRequest request) {
        return create(landscapeId, request, null);
    }

    public IcePanelClientHttpResponse<RevertsCreateResponse> create(
            String landscapeId, VersionRevertCreateRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("landscapes")
                .addPathSegment(landscapeId)
                .addPathSegments("version")
                .addPathSegments("reverts")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request.getBody()), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new IcePanelClientException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new IcePanelClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, RevertsCreateResponse.class), response);
            }
            try {
                switch (response.code()) {
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 422:
                        throw new UnprocessableEntityError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new IcePanelClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new IcePanelClientException("Network error executing HTTP request", e);
        }
    }

    public IcePanelClientHttpResponse<RevertsGetResponse> get(String landscapeId, String versionRevertId) {
        return get(
                landscapeId, versionRevertId, VersionRevertFindRequest.builder().build());
    }

    public IcePanelClientHttpResponse<RevertsGetResponse> get(
            String landscapeId, String versionRevertId, VersionRevertFindRequest request) {
        return get(landscapeId, versionRevertId, request, null);
    }

    public IcePanelClientHttpResponse<RevertsGetResponse> get(
            String landscapeId,
            String versionRevertId,
            VersionRevertFindRequest request,
            RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("landscapes")
                .addPathSegment(landscapeId)
                .addPathSegments("version/reverts")
                .addPathSegment(versionRevertId)
                .build();
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl)
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new IcePanelClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, RevertsGetResponse.class), response);
            }
            try {
                switch (response.code()) {
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 422:
                        throw new UnprocessableEntityError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new IcePanelClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new IcePanelClientException("Network error executing HTTP request", e);
        }
    }

    public IcePanelClientHttpResponse<RevertsUpdateResponse> update(
            String landscapeId, String versionRevertId, VersionRevertUpdateRequest request) {
        return update(landscapeId, versionRevertId, request, null);
    }

    public IcePanelClientHttpResponse<RevertsUpdateResponse> update(
            String landscapeId,
            String versionRevertId,
            VersionRevertUpdateRequest request,
            RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("landscapes")
                .addPathSegment(landscapeId)
                .addPathSegments("version/reverts")
                .addPathSegment(versionRevertId)
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request.getBody()), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new IcePanelClientException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("PATCH", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new IcePanelClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, RevertsUpdateResponse.class), response);
            }
            try {
                switch (response.code()) {
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 422:
                        throw new UnprocessableEntityError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new IcePanelClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new IcePanelClientException("Network error executing HTTP request", e);
        }
    }
}
