/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.api.resources.landscapes.logs.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.icepanel.api.core.ObjectMappers;
import com.icepanel.api.types.ActionLog;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = LogsListChildrenResponse.Builder.class)
public final class LogsListChildrenResponse {
    private final List<ActionLog> actionLogs;

    private final Map<String, Object> additionalProperties;

    private LogsListChildrenResponse(List<ActionLog> actionLogs, Map<String, Object> additionalProperties) {
        this.actionLogs = actionLogs;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("actionLogs")
    public List<ActionLog> getActionLogs() {
        return actionLogs;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof LogsListChildrenResponse && equalTo((LogsListChildrenResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(LogsListChildrenResponse other) {
        return actionLogs.equals(other.actionLogs);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.actionLogs);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private List<ActionLog> actionLogs = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(LogsListChildrenResponse other) {
            actionLogs(other.getActionLogs());
            return this;
        }

        @JsonSetter(value = "actionLogs", nulls = Nulls.SKIP)
        public Builder actionLogs(List<ActionLog> actionLogs) {
            this.actionLogs.clear();
            if (actionLogs != null) {
                this.actionLogs.addAll(actionLogs);
            }
            return this;
        }

        public Builder addActionLogs(ActionLog actionLogs) {
            this.actionLogs.add(actionLogs);
            return this;
        }

        public Builder addAllActionLogs(List<ActionLog> actionLogs) {
            if (actionLogs != null) {
                this.actionLogs.addAll(actionLogs);
            }
            return this;
        }

        public LogsListChildrenResponse build() {
            return new LogsListChildrenResponse(actionLogs, additionalProperties);
        }
    }
}
