/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.types;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.icepanel.core.ObjectMappers;
import java.io.IOException;
import java.util.Map;
import java.util.Objects;

@JsonDeserialize(using = ActionOAuth.Deserializer.class)
public final class ActionOAuth {
    private final Object value;

    private final int type;

    private ActionOAuth(Object value, int type) {
        this.value = value;
        this.type = type;
    }

    @JsonValue
    public Object get() {
        return this.value;
    }

    @SuppressWarnings("unchecked")
    public <T> T visit(Visitor<T> visitor) {
        if (this.type == 0) {
            return visitor.visit((ActionOAuthConsentDeny) this.value);
        } else if (this.type == 1) {
            return visitor.visit((ActionOAuthConsentGrant) this.value);
        }
        throw new IllegalStateException("Failed to visit value. This should never happen.");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ActionOAuth && equalTo((ActionOAuth) other);
    }

    private boolean equalTo(ActionOAuth other) {
        return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
        return this.value.toString();
    }

    public static ActionOAuth of(ActionOAuthConsentDeny value) {
        return new ActionOAuth(value, 0);
    }

    public static ActionOAuth of(ActionOAuthConsentGrant value) {
        return new ActionOAuth(value, 1);
    }

    public interface Visitor<T> {
        T visit(ActionOAuthConsentDeny value);

        T visit(ActionOAuthConsentGrant value);
    }

    static final class Deserializer extends StdDeserializer<ActionOAuth> {
        Deserializer() {
            super(ActionOAuth.class);
        }

        @java.lang.Override
        public ActionOAuth deserialize(JsonParser p, DeserializationContext context) throws IOException {
            Object value = p.readValueAs(Object.class);
            if (value instanceof Map<?, ?>
                    && ((Map<?, ?>) value).containsKey("id")
                    && ((Map<?, ?>) value).containsKey("props")
                    && ((Map<?, ?>) value).containsKey("type")) {
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(value, ActionOAuthConsentDeny.class));
                } catch (RuntimeException e) {
                }
            }
            if (value instanceof Map<?, ?>
                    && ((Map<?, ?>) value).containsKey("id")
                    && ((Map<?, ?>) value).containsKey("props")
                    && ((Map<?, ?>) value).containsKey("type")) {
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(value, ActionOAuthConsentGrant.class));
                } catch (RuntimeException e) {
                }
            }
            throw new JsonParseException(p, "Failed to deserialize");
        }
    }
}
