/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.icepanel.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ActionOrganizationUserAdd.Builder.class)
public final class ActionOrganizationUserAdd {
    private final ActionOrganizationUserAddContext context;

    private final String id;

    private final OrganizationUser props;

    private final Type type;

    private final Map<String, Object> additionalProperties;

    private ActionOrganizationUserAdd(
            ActionOrganizationUserAddContext context,
            String id,
            OrganizationUser props,
            Type type,
            Map<String, Object> additionalProperties) {
        this.context = context;
        this.id = id;
        this.props = props;
        this.type = type;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("context")
    public ActionOrganizationUserAddContext getContext() {
        return context;
    }

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("props")
    public OrganizationUser getProps() {
        return props;
    }

    @JsonProperty("type")
    public Type getType() {
        return type;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ActionOrganizationUserAdd && equalTo((ActionOrganizationUserAdd) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ActionOrganizationUserAdd other) {
        return context.equals(other.context)
                && id.equals(other.id)
                && props.equals(other.props)
                && type.equals(other.type);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.context, this.id, this.props, this.type);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ContextStage builder() {
        return new Builder();
    }

    public interface ContextStage {
        IdStage context(@NotNull ActionOrganizationUserAddContext context);

        Builder from(ActionOrganizationUserAdd other);
    }

    public interface IdStage {
        PropsStage id(@NotNull String id);
    }

    public interface PropsStage {
        TypeStage props(@NotNull OrganizationUser props);
    }

    public interface TypeStage {
        _FinalStage type(@NotNull Type type);
    }

    public interface _FinalStage {
        ActionOrganizationUserAdd build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ContextStage, IdStage, PropsStage, TypeStage, _FinalStage {
        private ActionOrganizationUserAddContext context;

        private String id;

        private OrganizationUser props;

        private Type type;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ActionOrganizationUserAdd other) {
            context(other.getContext());
            id(other.getId());
            props(other.getProps());
            type(other.getType());
            return this;
        }

        @java.lang.Override
        @JsonSetter("context")
        public IdStage context(@NotNull ActionOrganizationUserAddContext context) {
            this.context = Objects.requireNonNull(context, "context must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public PropsStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("props")
        public TypeStage props(@NotNull OrganizationUser props) {
            this.props = Objects.requireNonNull(props, "props must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("type")
        public _FinalStage type(@NotNull Type type) {
            this.type = Objects.requireNonNull(type, "type must not be null");
            return this;
        }

        @java.lang.Override
        public ActionOrganizationUserAdd build() {
            return new ActionOrganizationUserAdd(context, id, props, type, additionalProperties);
        }
    }

    public static final class Type {
        public static final Type ORGANIZATION_USER_ADD = new Type(Value.ORGANIZATION_USER_ADD, "organization-user-add");

        private final Value value;

        private final String string;

        Type(Value value, String string) {
            this.value = value;
            this.string = string;
        }

        public Value getEnumValue() {
            return value;
        }

        @java.lang.Override
        @JsonValue
        public String toString() {
            return this.string;
        }

        @java.lang.Override
        public boolean equals(Object other) {
            return (this == other) || (other instanceof Type && this.string.equals(((Type) other).string));
        }

        @java.lang.Override
        public int hashCode() {
            return this.string.hashCode();
        }

        public <T> T visit(Visitor<T> visitor) {
            switch (value) {
                case ORGANIZATION_USER_ADD:
                    return visitor.visitOrganizationUserAdd();
                case UNKNOWN:
                default:
                    return visitor.visitUnknown(string);
            }
        }

        @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
        public static Type valueOf(String value) {
            switch (value) {
                case "organization-user-add":
                    return ORGANIZATION_USER_ADD;
                default:
                    return new Type(Value.UNKNOWN, value);
            }
        }

        public enum Value {
            ORGANIZATION_USER_ADD,

            UNKNOWN
        }

        public interface Visitor<T> {
            T visitOrganizationUserAdd();

            T visitUnknown(String unknownType);
        }
    }
}
