/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.icepanel.core.ObjectMappers;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonDeserialize(using = ActionLogFilterActionType.Deserializer.class)
public final class ActionLogFilterActionType {
    private final Object value;

    private final int type;

    private ActionLogFilterActionType(Object value, int type) {
        this.value = value;
        this.type = type;
    }

    @JsonValue
    public Object get() {
        return this.value;
    }

    @SuppressWarnings("unchecked")
    public <T> T visit(Visitor<T> visitor) {
        if (this.type == 0) {
            return visitor.visit((LandscapeActionType) this.value);
        } else if (this.type == 1) {
            return visitor.visit((List<LandscapeActionType>) this.value);
        } else if (this.type == 2) {
            return visitor.visit((Not) this.value);
        }
        throw new IllegalStateException("Failed to visit value. This should never happen.");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ActionLogFilterActionType && equalTo((ActionLogFilterActionType) other);
    }

    private boolean equalTo(ActionLogFilterActionType other) {
        return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
        return this.value.toString();
    }

    public static ActionLogFilterActionType of(LandscapeActionType value) {
        return new ActionLogFilterActionType(value, 0);
    }

    public static ActionLogFilterActionType of(List<LandscapeActionType> value) {
        return new ActionLogFilterActionType(value, 1);
    }

    public static ActionLogFilterActionType of(Not value) {
        return new ActionLogFilterActionType(value, 2);
    }

    public interface Visitor<T> {
        T visit(LandscapeActionType value);

        T visit(List<LandscapeActionType> value);

        T visit(Not value);
    }

    static final class Deserializer extends StdDeserializer<ActionLogFilterActionType> {
        Deserializer() {
            super(ActionLogFilterActionType.class);
        }

        @java.lang.Override
        public ActionLogFilterActionType deserialize(JsonParser p, DeserializationContext context) throws IOException {
            Object value = p.readValueAs(Object.class);
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, LandscapeActionType.class));
            } catch (RuntimeException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(
                        value, new TypeReference<List<LandscapeActionType>>() {}));
            } catch (RuntimeException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, Not.class));
            } catch (RuntimeException e) {
            }
            throw new JsonParseException(p, "Failed to deserialize");
        }
    }

    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    @JsonDeserialize(builder = Not.Builder.class)
    public static final class Not {
        private final Optional<Not_> not;

        private final Map<String, Object> additionalProperties;

        private Not(Optional<Not_> not, Map<String, Object> additionalProperties) {
            this.not = not;
            this.additionalProperties = additionalProperties;
        }

        @JsonProperty("$not")
        public Optional<Not_> getNot() {
            return not;
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof Not && equalTo((Not) other);
        }

        @JsonAnyGetter
        public Map<String, Object> getAdditionalProperties() {
            return this.additionalProperties;
        }

        private boolean equalTo(Not other) {
            return not.equals(other.not);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.not);
        }

        @java.lang.Override
        public String toString() {
            return ObjectMappers.stringify(this);
        }

        public static Builder builder() {
            return new Builder();
        }

        @JsonIgnoreProperties(ignoreUnknown = true)
        public static final class Builder {
            private Optional<Not_> not = Optional.empty();

            @JsonAnySetter
            private Map<String, Object> additionalProperties = new HashMap<>();

            private Builder() {}

            public Builder from(Not other) {
                not(other.getNot());
                return this;
            }

            @JsonSetter(value = "$not", nulls = Nulls.SKIP)
            public Builder not(Optional<Not_> not) {
                this.not = not;
                return this;
            }

            public Builder not(Not_ not) {
                this.not = Optional.ofNullable(not);
                return this;
            }

            public Not build() {
                return new Not(not, additionalProperties);
            }
        }

        @JsonDeserialize(using = Not_.Deserializer.class)
        public static final class Not_ {
            private final Object value;

            private final int type;

            private Not_(Object value, int type) {
                this.value = value;
                this.type = type;
            }

            @JsonValue
            public Object get() {
                return this.value;
            }

            @SuppressWarnings("unchecked")
            public <T> T visit(Visitor<T> visitor) {
                if (this.type == 0) {
                    return visitor.visit((LandscapeActionType) this.value);
                } else if (this.type == 1) {
                    return visitor.visit((List<LandscapeActionType>) this.value);
                }
                throw new IllegalStateException("Failed to visit value. This should never happen.");
            }

            @java.lang.Override
            public boolean equals(Object other) {
                if (this == other) return true;
                return other instanceof Not_ && equalTo((Not_) other);
            }

            private boolean equalTo(Not_ other) {
                return value.equals(other.value);
            }

            @java.lang.Override
            public int hashCode() {
                return Objects.hash(this.value);
            }

            @java.lang.Override
            public String toString() {
                return this.value.toString();
            }

            public static Not_ of(LandscapeActionType value) {
                return new Not_(value, 0);
            }

            public static Not_ of(List<LandscapeActionType> value) {
                return new Not_(value, 1);
            }

            public interface Visitor<T> {
                T visit(LandscapeActionType value);

                T visit(List<LandscapeActionType> value);
            }

            static final class Deserializer extends StdDeserializer<Not_> {
                Deserializer() {
                    super(Not_.class);
                }

                @java.lang.Override
                public Not_ deserialize(JsonParser p, DeserializationContext context) throws IOException {
                    Object value = p.readValueAs(Object.class);
                    try {
                        return of(ObjectMappers.JSON_MAPPER.convertValue(value, LandscapeActionType.class));
                    } catch (RuntimeException e) {
                    }
                    try {
                        return of(ObjectMappers.JSON_MAPPER.convertValue(
                                value, new TypeReference<List<LandscapeActionType>>() {}));
                    } catch (RuntimeException e) {
                    }
                    throw new JsonParseException(p, "Failed to deserialize");
                }
            }
        }
    }
}
