/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.icepanel.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ActionCommentUpdateContext.Builder.class)
public final class ActionCommentUpdateContext {
    private final Optional<String> domainHandleId;

    private final Optional<String> domainName;

    private final Optional<List<ActionContextModelObject>> modelFamily;

    private final Optional<String> targetHandleId;

    private final Optional<String> targetName;

    private final Map<String, Object> additionalProperties;

    private ActionCommentUpdateContext(
            Optional<String> domainHandleId,
            Optional<String> domainName,
            Optional<List<ActionContextModelObject>> modelFamily,
            Optional<String> targetHandleId,
            Optional<String> targetName,
            Map<String, Object> additionalProperties) {
        this.domainHandleId = domainHandleId;
        this.domainName = domainName;
        this.modelFamily = modelFamily;
        this.targetHandleId = targetHandleId;
        this.targetName = targetName;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("domainHandleId")
    public Optional<String> getDomainHandleId() {
        return domainHandleId;
    }

    @JsonProperty("domainName")
    public Optional<String> getDomainName() {
        return domainName;
    }

    @JsonProperty("modelFamily")
    public Optional<List<ActionContextModelObject>> getModelFamily() {
        return modelFamily;
    }

    @JsonProperty("targetHandleId")
    public Optional<String> getTargetHandleId() {
        return targetHandleId;
    }

    @JsonProperty("targetName")
    public Optional<String> getTargetName() {
        return targetName;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ActionCommentUpdateContext && equalTo((ActionCommentUpdateContext) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ActionCommentUpdateContext other) {
        return domainHandleId.equals(other.domainHandleId)
                && domainName.equals(other.domainName)
                && modelFamily.equals(other.modelFamily)
                && targetHandleId.equals(other.targetHandleId)
                && targetName.equals(other.targetName);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.domainHandleId, this.domainName, this.modelFamily, this.targetHandleId, this.targetName);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> domainHandleId = Optional.empty();

        private Optional<String> domainName = Optional.empty();

        private Optional<List<ActionContextModelObject>> modelFamily = Optional.empty();

        private Optional<String> targetHandleId = Optional.empty();

        private Optional<String> targetName = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ActionCommentUpdateContext other) {
            domainHandleId(other.getDomainHandleId());
            domainName(other.getDomainName());
            modelFamily(other.getModelFamily());
            targetHandleId(other.getTargetHandleId());
            targetName(other.getTargetName());
            return this;
        }

        @JsonSetter(value = "domainHandleId", nulls = Nulls.SKIP)
        public Builder domainHandleId(Optional<String> domainHandleId) {
            this.domainHandleId = domainHandleId;
            return this;
        }

        public Builder domainHandleId(String domainHandleId) {
            this.domainHandleId = Optional.ofNullable(domainHandleId);
            return this;
        }

        @JsonSetter(value = "domainName", nulls = Nulls.SKIP)
        public Builder domainName(Optional<String> domainName) {
            this.domainName = domainName;
            return this;
        }

        public Builder domainName(String domainName) {
            this.domainName = Optional.ofNullable(domainName);
            return this;
        }

        @JsonSetter(value = "modelFamily", nulls = Nulls.SKIP)
        public Builder modelFamily(Optional<List<ActionContextModelObject>> modelFamily) {
            this.modelFamily = modelFamily;
            return this;
        }

        public Builder modelFamily(List<ActionContextModelObject> modelFamily) {
            this.modelFamily = Optional.ofNullable(modelFamily);
            return this;
        }

        @JsonSetter(value = "targetHandleId", nulls = Nulls.SKIP)
        public Builder targetHandleId(Optional<String> targetHandleId) {
            this.targetHandleId = targetHandleId;
            return this;
        }

        public Builder targetHandleId(String targetHandleId) {
            this.targetHandleId = Optional.ofNullable(targetHandleId);
            return this;
        }

        @JsonSetter(value = "targetName", nulls = Nulls.SKIP)
        public Builder targetName(Optional<String> targetName) {
            this.targetName = targetName;
            return this;
        }

        public Builder targetName(String targetName) {
            this.targetName = Optional.ofNullable(targetName);
            return this;
        }

        public ActionCommentUpdateContext build() {
            return new ActionCommentUpdateContext(
                    domainHandleId, domainName, modelFamily, targetHandleId, targetName, additionalProperties);
        }
    }
}
