/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class AdrRelatedItemType {
    public static final AdrRelatedItemType DIAGRAM = new AdrRelatedItemType(Value.DIAGRAM, "diagram");

    public static final AdrRelatedItemType LINK = new AdrRelatedItemType(Value.LINK, "link");

    public static final AdrRelatedItemType ADR = new AdrRelatedItemType(Value.ADR, "adr");

    public static final AdrRelatedItemType DRAFT = new AdrRelatedItemType(Value.DRAFT, "draft");

    private final Value value;

    private final String string;

    AdrRelatedItemType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof AdrRelatedItemType && this.string.equals(((AdrRelatedItemType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case DIAGRAM:
                return visitor.visitDiagram();
            case LINK:
                return visitor.visitLink();
            case ADR:
                return visitor.visitAdr();
            case DRAFT:
                return visitor.visitDraft();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static AdrRelatedItemType valueOf(String value) {
        switch (value) {
            case "diagram":
                return DIAGRAM;
            case "link":
                return LINK;
            case "adr":
                return ADR;
            case "draft":
                return DRAFT;
            default:
                return new AdrRelatedItemType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        ADR,

        DIAGRAM,

        DRAFT,

        LINK,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitAdr();

        T visitDiagram();

        T visitDraft();

        T visitLink();

        T visitUnknown(String unknownType);
    }
}
