/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.icepanel.core.Nullable;
import com.icepanel.core.NullableNonemptyFilter;
import com.icepanel.core.ObjectMappers;
import com.icepanel.core.OptionalNullable;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CatalogSuggestionInformation.Builder.class)
public final class CatalogSuggestionInformation {
    private final Optional<String> description;

    private final Optional<String> docsUrl;

    private final Optional<String> githubUrl;

    private final Optional<String> name;

    private final Optional<String> nameShort;

    private final Optional<String> newsUrl;

    private final OptionalNullable<CatalogTechnologyTypeNullable> type;

    private final Optional<String> updatesUrl;

    private final Map<String, Object> additionalProperties;

    private CatalogSuggestionInformation(
            Optional<String> description,
            Optional<String> docsUrl,
            Optional<String> githubUrl,
            Optional<String> name,
            Optional<String> nameShort,
            Optional<String> newsUrl,
            OptionalNullable<CatalogTechnologyTypeNullable> type,
            Optional<String> updatesUrl,
            Map<String, Object> additionalProperties) {
        this.description = description;
        this.docsUrl = docsUrl;
        this.githubUrl = githubUrl;
        this.name = name;
        this.nameShort = nameShort;
        this.newsUrl = newsUrl;
        this.type = type;
        this.updatesUrl = updatesUrl;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Technical description for the technology
     */
    @JsonProperty("description")
    public Optional<String> getDescription() {
        return description;
    }

    /**
     * @return Documentation or readme url
     */
    @JsonProperty("docsUrl")
    public Optional<String> getDocsUrl() {
        return docsUrl;
    }

    /**
     * @return GitHub repo url
     */
    @JsonProperty("githubUrl")
    public Optional<String> getGithubUrl() {
        return githubUrl;
    }

    @JsonProperty("name")
    public Optional<String> getName() {
        return name;
    }

    /**
     * @return Short name to show in places with limited space
     */
    @JsonProperty("nameShort")
    public Optional<String> getNameShort() {
        return nameShort;
    }

    /**
     * @return News url
     */
    @JsonProperty("newsUrl")
    public Optional<String> getNewsUrl() {
        return newsUrl;
    }

    /**
     * @return Type or category of technology
     */
    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("type")
    public OptionalNullable<CatalogTechnologyTypeNullable> getType() {
        if (type == null) {
            return OptionalNullable.absent();
        }
        return type;
    }

    /**
     * @return Release notes or changelog url
     */
    @JsonProperty("updatesUrl")
    public Optional<String> getUpdatesUrl() {
        return updatesUrl;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("type")
    private OptionalNullable<CatalogTechnologyTypeNullable> _getType() {
        return type;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CatalogSuggestionInformation && equalTo((CatalogSuggestionInformation) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CatalogSuggestionInformation other) {
        return description.equals(other.description)
                && docsUrl.equals(other.docsUrl)
                && githubUrl.equals(other.githubUrl)
                && name.equals(other.name)
                && nameShort.equals(other.nameShort)
                && newsUrl.equals(other.newsUrl)
                && type.equals(other.type)
                && updatesUrl.equals(other.updatesUrl);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.description,
                this.docsUrl,
                this.githubUrl,
                this.name,
                this.nameShort,
                this.newsUrl,
                this.type,
                this.updatesUrl);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> description = Optional.empty();

        private Optional<String> docsUrl = Optional.empty();

        private Optional<String> githubUrl = Optional.empty();

        private Optional<String> name = Optional.empty();

        private Optional<String> nameShort = Optional.empty();

        private Optional<String> newsUrl = Optional.empty();

        private OptionalNullable<CatalogTechnologyTypeNullable> type = OptionalNullable.absent();

        private Optional<String> updatesUrl = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(CatalogSuggestionInformation other) {
            description(other.getDescription());
            docsUrl(other.getDocsUrl());
            githubUrl(other.getGithubUrl());
            name(other.getName());
            nameShort(other.getNameShort());
            newsUrl(other.getNewsUrl());
            type(other.getType());
            updatesUrl(other.getUpdatesUrl());
            return this;
        }

        /**
         * <p>Technical description for the technology</p>
         */
        @JsonSetter(value = "description", nulls = Nulls.SKIP)
        public Builder description(Optional<String> description) {
            this.description = description;
            return this;
        }

        public Builder description(String description) {
            this.description = Optional.ofNullable(description);
            return this;
        }

        /**
         * <p>Documentation or readme url</p>
         */
        @JsonSetter(value = "docsUrl", nulls = Nulls.SKIP)
        public Builder docsUrl(Optional<String> docsUrl) {
            this.docsUrl = docsUrl;
            return this;
        }

        public Builder docsUrl(String docsUrl) {
            this.docsUrl = Optional.ofNullable(docsUrl);
            return this;
        }

        /**
         * <p>GitHub repo url</p>
         */
        @JsonSetter(value = "githubUrl", nulls = Nulls.SKIP)
        public Builder githubUrl(Optional<String> githubUrl) {
            this.githubUrl = githubUrl;
            return this;
        }

        public Builder githubUrl(String githubUrl) {
            this.githubUrl = Optional.ofNullable(githubUrl);
            return this;
        }

        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public Builder name(Optional<String> name) {
            this.name = name;
            return this;
        }

        public Builder name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        /**
         * <p>Short name to show in places with limited space</p>
         */
        @JsonSetter(value = "nameShort", nulls = Nulls.SKIP)
        public Builder nameShort(Optional<String> nameShort) {
            this.nameShort = nameShort;
            return this;
        }

        public Builder nameShort(String nameShort) {
            this.nameShort = Optional.ofNullable(nameShort);
            return this;
        }

        /**
         * <p>News url</p>
         */
        @JsonSetter(value = "newsUrl", nulls = Nulls.SKIP)
        public Builder newsUrl(Optional<String> newsUrl) {
            this.newsUrl = newsUrl;
            return this;
        }

        public Builder newsUrl(String newsUrl) {
            this.newsUrl = Optional.ofNullable(newsUrl);
            return this;
        }

        /**
         * <p>Type or category of technology</p>
         */
        @JsonSetter(value = "type", nulls = Nulls.SKIP)
        public Builder type(OptionalNullable<CatalogTechnologyTypeNullable> type) {
            this.type = type;
            return this;
        }

        public Builder type(CatalogTechnologyTypeNullable type) {
            this.type = OptionalNullable.of(type);
            return this;
        }

        public Builder type(Optional<CatalogTechnologyTypeNullable> type) {
            if (type.isPresent()) {
                this.type = OptionalNullable.of(type.get());
            } else {
                this.type = OptionalNullable.absent();
            }
            return this;
        }

        public Builder type(Nullable<CatalogTechnologyTypeNullable> type) {
            if (type.isNull()) {
                this.type = OptionalNullable.ofNull();
            } else if (type.isEmpty()) {
                this.type = OptionalNullable.absent();
            } else {
                this.type = OptionalNullable.of(type.get());
            }
            return this;
        }

        /**
         * <p>Release notes or changelog url</p>
         */
        @JsonSetter(value = "updatesUrl", nulls = Nulls.SKIP)
        public Builder updatesUrl(Optional<String> updatesUrl) {
            this.updatesUrl = updatesUrl;
            return this;
        }

        public Builder updatesUrl(String updatesUrl) {
            this.updatesUrl = Optional.ofNullable(updatesUrl);
            return this;
        }

        public CatalogSuggestionInformation build() {
            return new CatalogSuggestionInformation(
                    description, docsUrl, githubUrl, name, nameShort, newsUrl, type, updatesUrl, additionalProperties);
        }
    }
}
