/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.icepanel.core.Nullable;
import com.icepanel.core.NullableNonemptyFilter;
import com.icepanel.core.ObjectMappers;
import com.icepanel.core.OptionalNullable;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DiagramContent.Builder.class)
public final class DiagramContent {
    private final Map<String, DiagramComment> comments;

    private final double commit;

    private final Map<String, DiagramConnection> connections;

    private final Map<String, DiagramObject> objects;

    private final OffsetDateTime createdAt;

    private final AuthType createdBy;

    private final String createdById;

    private final Optional<OffsetDateTime> deletedAt;

    private final Optional<AuthType> deletedBy;

    private final Optional<String> deletedById;

    private final OptionalNullable<String> groupId;

    private final String handleId;

    private final String id;

    private final String landscapeId;

    private final Optional<String> latestEntityId;

    private final String modelId;

    private final String name;

    private final DiagramStatus status;

    private final DiagramType type;

    private final OffsetDateTime updatedAt;

    private final AuthType updatedBy;

    private final String updatedById;

    private final double version;

    private final String versionId;

    private final Optional<OffsetDateTime> viewedAt;

    private final Optional<AuthType> viewedBy;

    private final Optional<String> viewedById;

    private final Map<String, Object> additionalProperties;

    private DiagramContent(
            Map<String, DiagramComment> comments,
            double commit,
            Map<String, DiagramConnection> connections,
            Map<String, DiagramObject> objects,
            OffsetDateTime createdAt,
            AuthType createdBy,
            String createdById,
            Optional<OffsetDateTime> deletedAt,
            Optional<AuthType> deletedBy,
            Optional<String> deletedById,
            OptionalNullable<String> groupId,
            String handleId,
            String id,
            String landscapeId,
            Optional<String> latestEntityId,
            String modelId,
            String name,
            DiagramStatus status,
            DiagramType type,
            OffsetDateTime updatedAt,
            AuthType updatedBy,
            String updatedById,
            double version,
            String versionId,
            Optional<OffsetDateTime> viewedAt,
            Optional<AuthType> viewedBy,
            Optional<String> viewedById,
            Map<String, Object> additionalProperties) {
        this.comments = comments;
        this.commit = commit;
        this.connections = connections;
        this.objects = objects;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
        this.createdById = createdById;
        this.deletedAt = deletedAt;
        this.deletedBy = deletedBy;
        this.deletedById = deletedById;
        this.groupId = groupId;
        this.handleId = handleId;
        this.id = id;
        this.landscapeId = landscapeId;
        this.latestEntityId = latestEntityId;
        this.modelId = modelId;
        this.name = name;
        this.status = status;
        this.type = type;
        this.updatedAt = updatedAt;
        this.updatedBy = updatedBy;
        this.updatedById = updatedById;
        this.version = version;
        this.versionId = versionId;
        this.viewedAt = viewedAt;
        this.viewedBy = viewedBy;
        this.viewedById = viewedById;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("comments")
    public Map<String, DiagramComment> getComments() {
        return comments;
    }

    @JsonProperty("commit")
    public double getCommit() {
        return commit;
    }

    @JsonProperty("connections")
    public Map<String, DiagramConnection> getConnections() {
        return connections;
    }

    @JsonProperty("objects")
    public Map<String, DiagramObject> getObjects() {
        return objects;
    }

    @JsonProperty("createdAt")
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    @JsonProperty("createdBy")
    public AuthType getCreatedBy() {
        return createdBy;
    }

    @JsonProperty("createdById")
    public String getCreatedById() {
        return createdById;
    }

    @JsonProperty("deletedAt")
    public Optional<OffsetDateTime> getDeletedAt() {
        return deletedAt;
    }

    @JsonProperty("deletedBy")
    public Optional<AuthType> getDeletedBy() {
        return deletedBy;
    }

    @JsonProperty("deletedById")
    public Optional<String> getDeletedById() {
        return deletedById;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("groupId")
    public OptionalNullable<String> getGroupId() {
        if (groupId == null) {
            return OptionalNullable.absent();
        }
        return groupId;
    }

    @JsonProperty("handleId")
    public String getHandleId() {
        return handleId;
    }

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("landscapeId")
    public String getLandscapeId() {
        return landscapeId;
    }

    @JsonProperty("latestEntityId")
    public Optional<String> getLatestEntityId() {
        return latestEntityId;
    }

    @JsonProperty("modelId")
    public String getModelId() {
        return modelId;
    }

    @JsonProperty("name")
    public String getName() {
        return name;
    }

    @JsonProperty("status")
    public DiagramStatus getStatus() {
        return status;
    }

    @JsonProperty("type")
    public DiagramType getType() {
        return type;
    }

    @JsonProperty("updatedAt")
    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    @JsonProperty("updatedBy")
    public AuthType getUpdatedBy() {
        return updatedBy;
    }

    @JsonProperty("updatedById")
    public String getUpdatedById() {
        return updatedById;
    }

    @JsonProperty("version")
    public double getVersion() {
        return version;
    }

    @JsonProperty("versionId")
    public String getVersionId() {
        return versionId;
    }

    @JsonProperty("viewedAt")
    public Optional<OffsetDateTime> getViewedAt() {
        return viewedAt;
    }

    @JsonProperty("viewedBy")
    public Optional<AuthType> getViewedBy() {
        return viewedBy;
    }

    @JsonProperty("viewedById")
    public Optional<String> getViewedById() {
        return viewedById;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("groupId")
    private OptionalNullable<String> _getGroupId() {
        return groupId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DiagramContent && equalTo((DiagramContent) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DiagramContent other) {
        return comments.equals(other.comments)
                && commit == other.commit
                && connections.equals(other.connections)
                && objects.equals(other.objects)
                && createdAt.equals(other.createdAt)
                && createdBy.equals(other.createdBy)
                && createdById.equals(other.createdById)
                && deletedAt.equals(other.deletedAt)
                && deletedBy.equals(other.deletedBy)
                && deletedById.equals(other.deletedById)
                && groupId.equals(other.groupId)
                && handleId.equals(other.handleId)
                && id.equals(other.id)
                && landscapeId.equals(other.landscapeId)
                && latestEntityId.equals(other.latestEntityId)
                && modelId.equals(other.modelId)
                && name.equals(other.name)
                && status.equals(other.status)
                && type.equals(other.type)
                && updatedAt.equals(other.updatedAt)
                && updatedBy.equals(other.updatedBy)
                && updatedById.equals(other.updatedById)
                && version == other.version
                && versionId.equals(other.versionId)
                && viewedAt.equals(other.viewedAt)
                && viewedBy.equals(other.viewedBy)
                && viewedById.equals(other.viewedById);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.comments,
                this.commit,
                this.connections,
                this.objects,
                this.createdAt,
                this.createdBy,
                this.createdById,
                this.deletedAt,
                this.deletedBy,
                this.deletedById,
                this.groupId,
                this.handleId,
                this.id,
                this.landscapeId,
                this.latestEntityId,
                this.modelId,
                this.name,
                this.status,
                this.type,
                this.updatedAt,
                this.updatedBy,
                this.updatedById,
                this.version,
                this.versionId,
                this.viewedAt,
                this.viewedBy,
                this.viewedById);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static CommitStage builder() {
        return new Builder();
    }

    public interface CommitStage {
        CreatedAtStage commit(double commit);

        Builder from(DiagramContent other);
    }

    public interface CreatedAtStage {
        CreatedByStage createdAt(@NotNull OffsetDateTime createdAt);
    }

    public interface CreatedByStage {
        CreatedByIdStage createdBy(@NotNull AuthType createdBy);
    }

    public interface CreatedByIdStage {
        HandleIdStage createdById(@NotNull String createdById);
    }

    public interface HandleIdStage {
        IdStage handleId(@NotNull String handleId);
    }

    public interface IdStage {
        LandscapeIdStage id(@NotNull String id);
    }

    public interface LandscapeIdStage {
        ModelIdStage landscapeId(@NotNull String landscapeId);
    }

    public interface ModelIdStage {
        NameStage modelId(@NotNull String modelId);
    }

    public interface NameStage {
        StatusStage name(@NotNull String name);
    }

    public interface StatusStage {
        TypeStage status(@NotNull DiagramStatus status);
    }

    public interface TypeStage {
        UpdatedAtStage type(@NotNull DiagramType type);
    }

    public interface UpdatedAtStage {
        UpdatedByStage updatedAt(@NotNull OffsetDateTime updatedAt);
    }

    public interface UpdatedByStage {
        UpdatedByIdStage updatedBy(@NotNull AuthType updatedBy);
    }

    public interface UpdatedByIdStage {
        VersionStage updatedById(@NotNull String updatedById);
    }

    public interface VersionStage {
        VersionIdStage version(double version);
    }

    public interface VersionIdStage {
        _FinalStage versionId(@NotNull String versionId);
    }

    public interface _FinalStage {
        DiagramContent build();

        _FinalStage comments(Map<String, DiagramComment> comments);

        _FinalStage putAllComments(Map<String, DiagramComment> comments);

        _FinalStage comments(String key, DiagramComment value);

        _FinalStage connections(Map<String, DiagramConnection> connections);

        _FinalStage putAllConnections(Map<String, DiagramConnection> connections);

        _FinalStage connections(String key, DiagramConnection value);

        _FinalStage objects(Map<String, DiagramObject> objects);

        _FinalStage putAllObjects(Map<String, DiagramObject> objects);

        _FinalStage objects(String key, DiagramObject value);

        _FinalStage deletedAt(Optional<OffsetDateTime> deletedAt);

        _FinalStage deletedAt(OffsetDateTime deletedAt);

        _FinalStage deletedBy(Optional<AuthType> deletedBy);

        _FinalStage deletedBy(AuthType deletedBy);

        _FinalStage deletedById(Optional<String> deletedById);

        _FinalStage deletedById(String deletedById);

        _FinalStage groupId(OptionalNullable<String> groupId);

        _FinalStage groupId(String groupId);

        _FinalStage groupId(Optional<String> groupId);

        _FinalStage groupId(Nullable<String> groupId);

        _FinalStage latestEntityId(Optional<String> latestEntityId);

        _FinalStage latestEntityId(String latestEntityId);

        _FinalStage viewedAt(Optional<OffsetDateTime> viewedAt);

        _FinalStage viewedAt(OffsetDateTime viewedAt);

        _FinalStage viewedBy(Optional<AuthType> viewedBy);

        _FinalStage viewedBy(AuthType viewedBy);

        _FinalStage viewedById(Optional<String> viewedById);

        _FinalStage viewedById(String viewedById);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements CommitStage,
                    CreatedAtStage,
                    CreatedByStage,
                    CreatedByIdStage,
                    HandleIdStage,
                    IdStage,
                    LandscapeIdStage,
                    ModelIdStage,
                    NameStage,
                    StatusStage,
                    TypeStage,
                    UpdatedAtStage,
                    UpdatedByStage,
                    UpdatedByIdStage,
                    VersionStage,
                    VersionIdStage,
                    _FinalStage {
        private double commit;

        private OffsetDateTime createdAt;

        private AuthType createdBy;

        private String createdById;

        private String handleId;

        private String id;

        private String landscapeId;

        private String modelId;

        private String name;

        private DiagramStatus status;

        private DiagramType type;

        private OffsetDateTime updatedAt;

        private AuthType updatedBy;

        private String updatedById;

        private double version;

        private String versionId;

        private Optional<String> viewedById = Optional.empty();

        private Optional<AuthType> viewedBy = Optional.empty();

        private Optional<OffsetDateTime> viewedAt = Optional.empty();

        private Optional<String> latestEntityId = Optional.empty();

        private OptionalNullable<String> groupId = OptionalNullable.absent();

        private Optional<String> deletedById = Optional.empty();

        private Optional<AuthType> deletedBy = Optional.empty();

        private Optional<OffsetDateTime> deletedAt = Optional.empty();

        private Map<String, DiagramObject> objects = new LinkedHashMap<>();

        private Map<String, DiagramConnection> connections = new LinkedHashMap<>();

        private Map<String, DiagramComment> comments = new LinkedHashMap<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(DiagramContent other) {
            comments(other.getComments());
            commit(other.getCommit());
            connections(other.getConnections());
            objects(other.getObjects());
            createdAt(other.getCreatedAt());
            createdBy(other.getCreatedBy());
            createdById(other.getCreatedById());
            deletedAt(other.getDeletedAt());
            deletedBy(other.getDeletedBy());
            deletedById(other.getDeletedById());
            groupId(other.getGroupId());
            handleId(other.getHandleId());
            id(other.getId());
            landscapeId(other.getLandscapeId());
            latestEntityId(other.getLatestEntityId());
            modelId(other.getModelId());
            name(other.getName());
            status(other.getStatus());
            type(other.getType());
            updatedAt(other.getUpdatedAt());
            updatedBy(other.getUpdatedBy());
            updatedById(other.getUpdatedById());
            version(other.getVersion());
            versionId(other.getVersionId());
            viewedAt(other.getViewedAt());
            viewedBy(other.getViewedBy());
            viewedById(other.getViewedById());
            return this;
        }

        @java.lang.Override
        @JsonSetter("commit")
        public CreatedAtStage commit(double commit) {
            this.commit = commit;
            return this;
        }

        @java.lang.Override
        @JsonSetter("createdAt")
        public CreatedByStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("createdBy")
        public CreatedByIdStage createdBy(@NotNull AuthType createdBy) {
            this.createdBy = Objects.requireNonNull(createdBy, "createdBy must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("createdById")
        public HandleIdStage createdById(@NotNull String createdById) {
            this.createdById = Objects.requireNonNull(createdById, "createdById must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("handleId")
        public IdStage handleId(@NotNull String handleId) {
            this.handleId = Objects.requireNonNull(handleId, "handleId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public LandscapeIdStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("landscapeId")
        public ModelIdStage landscapeId(@NotNull String landscapeId) {
            this.landscapeId = Objects.requireNonNull(landscapeId, "landscapeId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("modelId")
        public NameStage modelId(@NotNull String modelId) {
            this.modelId = Objects.requireNonNull(modelId, "modelId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("name")
        public StatusStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("status")
        public TypeStage status(@NotNull DiagramStatus status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("type")
        public UpdatedAtStage type(@NotNull DiagramType type) {
            this.type = Objects.requireNonNull(type, "type must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("updatedAt")
        public UpdatedByStage updatedAt(@NotNull OffsetDateTime updatedAt) {
            this.updatedAt = Objects.requireNonNull(updatedAt, "updatedAt must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("updatedBy")
        public UpdatedByIdStage updatedBy(@NotNull AuthType updatedBy) {
            this.updatedBy = Objects.requireNonNull(updatedBy, "updatedBy must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("updatedById")
        public VersionStage updatedById(@NotNull String updatedById) {
            this.updatedById = Objects.requireNonNull(updatedById, "updatedById must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("version")
        public VersionIdStage version(double version) {
            this.version = version;
            return this;
        }

        @java.lang.Override
        @JsonSetter("versionId")
        public _FinalStage versionId(@NotNull String versionId) {
            this.versionId = Objects.requireNonNull(versionId, "versionId must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage viewedById(String viewedById) {
            this.viewedById = Optional.ofNullable(viewedById);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "viewedById", nulls = Nulls.SKIP)
        public _FinalStage viewedById(Optional<String> viewedById) {
            this.viewedById = viewedById;
            return this;
        }

        @java.lang.Override
        public _FinalStage viewedBy(AuthType viewedBy) {
            this.viewedBy = Optional.ofNullable(viewedBy);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "viewedBy", nulls = Nulls.SKIP)
        public _FinalStage viewedBy(Optional<AuthType> viewedBy) {
            this.viewedBy = viewedBy;
            return this;
        }

        @java.lang.Override
        public _FinalStage viewedAt(OffsetDateTime viewedAt) {
            this.viewedAt = Optional.ofNullable(viewedAt);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "viewedAt", nulls = Nulls.SKIP)
        public _FinalStage viewedAt(Optional<OffsetDateTime> viewedAt) {
            this.viewedAt = viewedAt;
            return this;
        }

        @java.lang.Override
        public _FinalStage latestEntityId(String latestEntityId) {
            this.latestEntityId = Optional.ofNullable(latestEntityId);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "latestEntityId", nulls = Nulls.SKIP)
        public _FinalStage latestEntityId(Optional<String> latestEntityId) {
            this.latestEntityId = latestEntityId;
            return this;
        }

        @java.lang.Override
        public _FinalStage groupId(Nullable<String> groupId) {
            if (groupId.isNull()) {
                this.groupId = OptionalNullable.ofNull();
            } else if (groupId.isEmpty()) {
                this.groupId = OptionalNullable.absent();
            } else {
                this.groupId = OptionalNullable.of(groupId.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage groupId(Optional<String> groupId) {
            if (groupId.isPresent()) {
                this.groupId = OptionalNullable.of(groupId.get());
            } else {
                this.groupId = OptionalNullable.absent();
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage groupId(String groupId) {
            this.groupId = OptionalNullable.of(groupId);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "groupId", nulls = Nulls.SKIP)
        public _FinalStage groupId(OptionalNullable<String> groupId) {
            this.groupId = groupId;
            return this;
        }

        @java.lang.Override
        public _FinalStage deletedById(String deletedById) {
            this.deletedById = Optional.ofNullable(deletedById);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "deletedById", nulls = Nulls.SKIP)
        public _FinalStage deletedById(Optional<String> deletedById) {
            this.deletedById = deletedById;
            return this;
        }

        @java.lang.Override
        public _FinalStage deletedBy(AuthType deletedBy) {
            this.deletedBy = Optional.ofNullable(deletedBy);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "deletedBy", nulls = Nulls.SKIP)
        public _FinalStage deletedBy(Optional<AuthType> deletedBy) {
            this.deletedBy = deletedBy;
            return this;
        }

        @java.lang.Override
        public _FinalStage deletedAt(OffsetDateTime deletedAt) {
            this.deletedAt = Optional.ofNullable(deletedAt);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "deletedAt", nulls = Nulls.SKIP)
        public _FinalStage deletedAt(Optional<OffsetDateTime> deletedAt) {
            this.deletedAt = deletedAt;
            return this;
        }

        @java.lang.Override
        public _FinalStage objects(String key, DiagramObject value) {
            this.objects.put(key, value);
            return this;
        }

        @java.lang.Override
        public _FinalStage putAllObjects(Map<String, DiagramObject> objects) {
            if (objects != null) {
                this.objects.putAll(objects);
            }
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "objects", nulls = Nulls.SKIP)
        public _FinalStage objects(Map<String, DiagramObject> objects) {
            this.objects.clear();
            if (objects != null) {
                this.objects.putAll(objects);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage connections(String key, DiagramConnection value) {
            this.connections.put(key, value);
            return this;
        }

        @java.lang.Override
        public _FinalStage putAllConnections(Map<String, DiagramConnection> connections) {
            if (connections != null) {
                this.connections.putAll(connections);
            }
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "connections", nulls = Nulls.SKIP)
        public _FinalStage connections(Map<String, DiagramConnection> connections) {
            this.connections.clear();
            if (connections != null) {
                this.connections.putAll(connections);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage comments(String key, DiagramComment value) {
            this.comments.put(key, value);
            return this;
        }

        @java.lang.Override
        public _FinalStage putAllComments(Map<String, DiagramComment> comments) {
            if (comments != null) {
                this.comments.putAll(comments);
            }
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "comments", nulls = Nulls.SKIP)
        public _FinalStage comments(Map<String, DiagramComment> comments) {
            this.comments.clear();
            if (comments != null) {
                this.comments.putAll(comments);
            }
            return this;
        }

        @java.lang.Override
        public DiagramContent build() {
            return new DiagramContent(
                    comments,
                    commit,
                    connections,
                    objects,
                    createdAt,
                    createdBy,
                    createdById,
                    deletedAt,
                    deletedBy,
                    deletedById,
                    groupId,
                    handleId,
                    id,
                    landscapeId,
                    latestEntityId,
                    modelId,
                    name,
                    status,
                    type,
                    updatedAt,
                    updatedBy,
                    updatedById,
                    version,
                    versionId,
                    viewedAt,
                    viewedBy,
                    viewedById,
                    additionalProperties);
        }
    }
}
