/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.icepanel.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DraftsListRequest.Builder.class)
public final class DraftsListRequest {
    private final String landscapeId;

    private final String versionId;

    private final Optional<DraftFilter> filter;

    private final Map<String, Object> additionalProperties;

    private DraftsListRequest(
            String landscapeId,
            String versionId,
            Optional<DraftFilter> filter,
            Map<String, Object> additionalProperties) {
        this.landscapeId = landscapeId;
        this.versionId = versionId;
        this.filter = filter;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("landscapeId")
    public String getLandscapeId() {
        return landscapeId;
    }

    @JsonProperty("versionId")
    public String getVersionId() {
        return versionId;
    }

    @JsonProperty("filter")
    public Optional<DraftFilter> getFilter() {
        return filter;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DraftsListRequest && equalTo((DraftsListRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DraftsListRequest other) {
        return landscapeId.equals(other.landscapeId)
                && versionId.equals(other.versionId)
                && filter.equals(other.filter);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.landscapeId, this.versionId, this.filter);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static LandscapeIdStage builder() {
        return new Builder();
    }

    public interface LandscapeIdStage {
        VersionIdStage landscapeId(@NotNull String landscapeId);

        Builder from(DraftsListRequest other);
    }

    public interface VersionIdStage {
        _FinalStage versionId(@NotNull String versionId);
    }

    public interface _FinalStage {
        DraftsListRequest build();

        _FinalStage filter(Optional<DraftFilter> filter);

        _FinalStage filter(DraftFilter filter);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements LandscapeIdStage, VersionIdStage, _FinalStage {
        private String landscapeId;

        private String versionId;

        private Optional<DraftFilter> filter = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(DraftsListRequest other) {
            landscapeId(other.getLandscapeId());
            versionId(other.getVersionId());
            filter(other.getFilter());
            return this;
        }

        @java.lang.Override
        @JsonSetter("landscapeId")
        public VersionIdStage landscapeId(@NotNull String landscapeId) {
            this.landscapeId = Objects.requireNonNull(landscapeId, "landscapeId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("versionId")
        public _FinalStage versionId(@NotNull String versionId) {
            this.versionId = Objects.requireNonNull(versionId, "versionId must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage filter(DraftFilter filter) {
            this.filter = Optional.ofNullable(filter);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "filter", nulls = Nulls.SKIP)
        public _FinalStage filter(Optional<DraftFilter> filter) {
            this.filter = filter;
            return this;
        }

        @java.lang.Override
        public DraftsListRequest build() {
            return new DraftsListRequest(landscapeId, versionId, filter, additionalProperties);
        }
    }
}
