/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.icepanel.core.Nullable;
import com.icepanel.core.NullableNonemptyFilter;
import com.icepanel.core.ObjectMappers;
import com.icepanel.core.OptionalNullable;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FlowStep.Builder.class)
public final class FlowStep {
    private final String description;

    private final Optional<String> detailedDescription;

    private final OptionalNullable<String> flowId;

    private final String id;

    private final double index;

    private final OptionalNullable<String> originId;

    private final OptionalNullable<String> parentId;

    private final OptionalNullable<Map<String, FlowStepPath>> paths;

    private final OptionalNullable<String> targetId;

    private final OptionalNullable<Type> type;

    private final OptionalNullable<String> viaId;

    private final Map<String, Object> additionalProperties;

    private FlowStep(
            String description,
            Optional<String> detailedDescription,
            OptionalNullable<String> flowId,
            String id,
            double index,
            OptionalNullable<String> originId,
            OptionalNullable<String> parentId,
            OptionalNullable<Map<String, FlowStepPath>> paths,
            OptionalNullable<String> targetId,
            OptionalNullable<Type> type,
            OptionalNullable<String> viaId,
            Map<String, Object> additionalProperties) {
        this.description = description;
        this.detailedDescription = detailedDescription;
        this.flowId = flowId;
        this.id = id;
        this.index = index;
        this.originId = originId;
        this.parentId = parentId;
        this.paths = paths;
        this.targetId = targetId;
        this.type = type;
        this.viaId = viaId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Descriptive name for the flow step
     */
    @JsonProperty("description")
    public String getDescription() {
        return description;
    }

    /**
     * @return Long description for the flow step
     */
    @JsonProperty("detailedDescription")
    public Optional<String> getDetailedDescription() {
        return detailedDescription;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("flowId")
    public OptionalNullable<String> getFlowId() {
        if (flowId == null) {
            return OptionalNullable.absent();
        }
        return flowId;
    }

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("index")
    public double getIndex() {
        return index;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("originId")
    public OptionalNullable<String> getOriginId() {
        if (originId == null) {
            return OptionalNullable.absent();
        }
        return originId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("parentId")
    public OptionalNullable<String> getParentId() {
        if (parentId == null) {
            return OptionalNullable.absent();
        }
        return parentId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("paths")
    public OptionalNullable<Map<String, FlowStepPath>> getPaths() {
        if (paths == null) {
            return OptionalNullable.absent();
        }
        return paths;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("targetId")
    public OptionalNullable<String> getTargetId() {
        if (targetId == null) {
            return OptionalNullable.absent();
        }
        return targetId;
    }

    /**
     * @return Type of flow step - deprecated values: reply
     */
    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("type")
    public OptionalNullable<Type> getType() {
        if (type == null) {
            return OptionalNullable.absent();
        }
        return type;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("viaId")
    public OptionalNullable<String> getViaId() {
        if (viaId == null) {
            return OptionalNullable.absent();
        }
        return viaId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("flowId")
    private OptionalNullable<String> _getFlowId() {
        return flowId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("originId")
    private OptionalNullable<String> _getOriginId() {
        return originId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("parentId")
    private OptionalNullable<String> _getParentId() {
        return parentId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("paths")
    private OptionalNullable<Map<String, FlowStepPath>> _getPaths() {
        return paths;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("targetId")
    private OptionalNullable<String> _getTargetId() {
        return targetId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("type")
    private OptionalNullable<Type> _getType() {
        return type;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("viaId")
    private OptionalNullable<String> _getViaId() {
        return viaId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof FlowStep && equalTo((FlowStep) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(FlowStep other) {
        return description.equals(other.description)
                && detailedDescription.equals(other.detailedDescription)
                && flowId.equals(other.flowId)
                && id.equals(other.id)
                && index == other.index
                && originId.equals(other.originId)
                && parentId.equals(other.parentId)
                && paths.equals(other.paths)
                && targetId.equals(other.targetId)
                && type.equals(other.type)
                && viaId.equals(other.viaId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.description,
                this.detailedDescription,
                this.flowId,
                this.id,
                this.index,
                this.originId,
                this.parentId,
                this.paths,
                this.targetId,
                this.type,
                this.viaId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static DescriptionStage builder() {
        return new Builder();
    }

    public interface DescriptionStage {
        /**
         * <p>Descriptive name for the flow step</p>
         */
        IdStage description(@NotNull String description);

        Builder from(FlowStep other);
    }

    public interface IdStage {
        IndexStage id(@NotNull String id);
    }

    public interface IndexStage {
        _FinalStage index(double index);
    }

    public interface _FinalStage {
        FlowStep build();

        /**
         * <p>Long description for the flow step</p>
         */
        _FinalStage detailedDescription(Optional<String> detailedDescription);

        _FinalStage detailedDescription(String detailedDescription);

        _FinalStage flowId(OptionalNullable<String> flowId);

        _FinalStage flowId(String flowId);

        _FinalStage flowId(Optional<String> flowId);

        _FinalStage flowId(Nullable<String> flowId);

        _FinalStage originId(OptionalNullable<String> originId);

        _FinalStage originId(String originId);

        _FinalStage originId(Optional<String> originId);

        _FinalStage originId(Nullable<String> originId);

        _FinalStage parentId(OptionalNullable<String> parentId);

        _FinalStage parentId(String parentId);

        _FinalStage parentId(Optional<String> parentId);

        _FinalStage parentId(Nullable<String> parentId);

        _FinalStage paths(OptionalNullable<Map<String, FlowStepPath>> paths);

        _FinalStage paths(Map<String, FlowStepPath> paths);

        _FinalStage paths(Optional<Map<String, FlowStepPath>> paths);

        _FinalStage paths(Nullable<Map<String, FlowStepPath>> paths);

        _FinalStage targetId(OptionalNullable<String> targetId);

        _FinalStage targetId(String targetId);

        _FinalStage targetId(Optional<String> targetId);

        _FinalStage targetId(Nullable<String> targetId);

        /**
         * <p>Type of flow step - deprecated values: reply</p>
         */
        _FinalStage type(OptionalNullable<Type> type);

        _FinalStage type(Type type);

        _FinalStage type(Optional<Type> type);

        _FinalStage type(Nullable<Type> type);

        _FinalStage viaId(OptionalNullable<String> viaId);

        _FinalStage viaId(String viaId);

        _FinalStage viaId(Optional<String> viaId);

        _FinalStage viaId(Nullable<String> viaId);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements DescriptionStage, IdStage, IndexStage, _FinalStage {
        private String description;

        private String id;

        private double index;

        private OptionalNullable<String> viaId = OptionalNullable.absent();

        private OptionalNullable<Type> type = OptionalNullable.absent();

        private OptionalNullable<String> targetId = OptionalNullable.absent();

        private OptionalNullable<Map<String, FlowStepPath>> paths = OptionalNullable.absent();

        private OptionalNullable<String> parentId = OptionalNullable.absent();

        private OptionalNullable<String> originId = OptionalNullable.absent();

        private OptionalNullable<String> flowId = OptionalNullable.absent();

        private Optional<String> detailedDescription = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(FlowStep other) {
            description(other.getDescription());
            detailedDescription(other.getDetailedDescription());
            flowId(other.getFlowId());
            id(other.getId());
            index(other.getIndex());
            originId(other.getOriginId());
            parentId(other.getParentId());
            paths(other.getPaths());
            targetId(other.getTargetId());
            type(other.getType());
            viaId(other.getViaId());
            return this;
        }

        /**
         * <p>Descriptive name for the flow step</p>
         * <p>Descriptive name for the flow step</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("description")
        public IdStage description(@NotNull String description) {
            this.description = Objects.requireNonNull(description, "description must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public IndexStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("index")
        public _FinalStage index(double index) {
            this.index = index;
            return this;
        }

        @java.lang.Override
        public _FinalStage viaId(Nullable<String> viaId) {
            if (viaId.isNull()) {
                this.viaId = OptionalNullable.ofNull();
            } else if (viaId.isEmpty()) {
                this.viaId = OptionalNullable.absent();
            } else {
                this.viaId = OptionalNullable.of(viaId.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage viaId(Optional<String> viaId) {
            if (viaId.isPresent()) {
                this.viaId = OptionalNullable.of(viaId.get());
            } else {
                this.viaId = OptionalNullable.absent();
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage viaId(String viaId) {
            this.viaId = OptionalNullable.of(viaId);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "viaId", nulls = Nulls.SKIP)
        public _FinalStage viaId(OptionalNullable<String> viaId) {
            this.viaId = viaId;
            return this;
        }

        /**
         * <p>Type of flow step - deprecated values: reply</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage type(Nullable<Type> type) {
            if (type.isNull()) {
                this.type = OptionalNullable.ofNull();
            } else if (type.isEmpty()) {
                this.type = OptionalNullable.absent();
            } else {
                this.type = OptionalNullable.of(type.get());
            }
            return this;
        }

        /**
         * <p>Type of flow step - deprecated values: reply</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage type(Optional<Type> type) {
            if (type.isPresent()) {
                this.type = OptionalNullable.of(type.get());
            } else {
                this.type = OptionalNullable.absent();
            }
            return this;
        }

        /**
         * <p>Type of flow step - deprecated values: reply</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage type(Type type) {
            this.type = OptionalNullable.of(type);
            return this;
        }

        /**
         * <p>Type of flow step - deprecated values: reply</p>
         */
        @java.lang.Override
        @JsonSetter(value = "type", nulls = Nulls.SKIP)
        public _FinalStage type(OptionalNullable<Type> type) {
            this.type = type;
            return this;
        }

        @java.lang.Override
        public _FinalStage targetId(Nullable<String> targetId) {
            if (targetId.isNull()) {
                this.targetId = OptionalNullable.ofNull();
            } else if (targetId.isEmpty()) {
                this.targetId = OptionalNullable.absent();
            } else {
                this.targetId = OptionalNullable.of(targetId.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage targetId(Optional<String> targetId) {
            if (targetId.isPresent()) {
                this.targetId = OptionalNullable.of(targetId.get());
            } else {
                this.targetId = OptionalNullable.absent();
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage targetId(String targetId) {
            this.targetId = OptionalNullable.of(targetId);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "targetId", nulls = Nulls.SKIP)
        public _FinalStage targetId(OptionalNullable<String> targetId) {
            this.targetId = targetId;
            return this;
        }

        @java.lang.Override
        public _FinalStage paths(Nullable<Map<String, FlowStepPath>> paths) {
            if (paths.isNull()) {
                this.paths = OptionalNullable.ofNull();
            } else if (paths.isEmpty()) {
                this.paths = OptionalNullable.absent();
            } else {
                this.paths = OptionalNullable.of(paths.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage paths(Optional<Map<String, FlowStepPath>> paths) {
            if (paths.isPresent()) {
                this.paths = OptionalNullable.of(paths.get());
            } else {
                this.paths = OptionalNullable.absent();
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage paths(Map<String, FlowStepPath> paths) {
            this.paths = OptionalNullable.of(paths);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "paths", nulls = Nulls.SKIP)
        public _FinalStage paths(OptionalNullable<Map<String, FlowStepPath>> paths) {
            this.paths = paths;
            return this;
        }

        @java.lang.Override
        public _FinalStage parentId(Nullable<String> parentId) {
            if (parentId.isNull()) {
                this.parentId = OptionalNullable.ofNull();
            } else if (parentId.isEmpty()) {
                this.parentId = OptionalNullable.absent();
            } else {
                this.parentId = OptionalNullable.of(parentId.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage parentId(Optional<String> parentId) {
            if (parentId.isPresent()) {
                this.parentId = OptionalNullable.of(parentId.get());
            } else {
                this.parentId = OptionalNullable.absent();
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage parentId(String parentId) {
            this.parentId = OptionalNullable.of(parentId);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "parentId", nulls = Nulls.SKIP)
        public _FinalStage parentId(OptionalNullable<String> parentId) {
            this.parentId = parentId;
            return this;
        }

        @java.lang.Override
        public _FinalStage originId(Nullable<String> originId) {
            if (originId.isNull()) {
                this.originId = OptionalNullable.ofNull();
            } else if (originId.isEmpty()) {
                this.originId = OptionalNullable.absent();
            } else {
                this.originId = OptionalNullable.of(originId.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage originId(Optional<String> originId) {
            if (originId.isPresent()) {
                this.originId = OptionalNullable.of(originId.get());
            } else {
                this.originId = OptionalNullable.absent();
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage originId(String originId) {
            this.originId = OptionalNullable.of(originId);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "originId", nulls = Nulls.SKIP)
        public _FinalStage originId(OptionalNullable<String> originId) {
            this.originId = originId;
            return this;
        }

        @java.lang.Override
        public _FinalStage flowId(Nullable<String> flowId) {
            if (flowId.isNull()) {
                this.flowId = OptionalNullable.ofNull();
            } else if (flowId.isEmpty()) {
                this.flowId = OptionalNullable.absent();
            } else {
                this.flowId = OptionalNullable.of(flowId.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage flowId(Optional<String> flowId) {
            if (flowId.isPresent()) {
                this.flowId = OptionalNullable.of(flowId.get());
            } else {
                this.flowId = OptionalNullable.absent();
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage flowId(String flowId) {
            this.flowId = OptionalNullable.of(flowId);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "flowId", nulls = Nulls.SKIP)
        public _FinalStage flowId(OptionalNullable<String> flowId) {
            this.flowId = flowId;
            return this;
        }

        /**
         * <p>Long description for the flow step</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage detailedDescription(String detailedDescription) {
            this.detailedDescription = Optional.ofNullable(detailedDescription);
            return this;
        }

        /**
         * <p>Long description for the flow step</p>
         */
        @java.lang.Override
        @JsonSetter(value = "detailedDescription", nulls = Nulls.SKIP)
        public _FinalStage detailedDescription(Optional<String> detailedDescription) {
            this.detailedDescription = detailedDescription;
            return this;
        }

        @java.lang.Override
        public FlowStep build() {
            return new FlowStep(
                    description,
                    detailedDescription,
                    flowId,
                    id,
                    index,
                    originId,
                    parentId,
                    paths,
                    targetId,
                    type,
                    viaId,
                    additionalProperties);
        }
    }

    public static final class Type {
        public static final Type ALTERNATE_PATH = new Type(Value.ALTERNATE_PATH, "alternate-path");

        public static final Type PARALLEL_PATH = new Type(Value.PARALLEL_PATH, "parallel-path");

        public static final Type OUTGOING = new Type(Value.OUTGOING, "outgoing");

        public static final Type SUBFLOW = new Type(Value.SUBFLOW, "subflow");

        public static final Type INFORMATION = new Type(Value.INFORMATION, "information");

        public static final Type SELF_ACTION = new Type(Value.SELF_ACTION, "self-action");

        public static final Type REPLY = new Type(Value.REPLY, "reply");

        public static final Type INTRODUCTION = new Type(Value.INTRODUCTION, "introduction");

        public static final Type CONCLUSION = new Type(Value.CONCLUSION, "conclusion");

        private final Value value;

        private final String string;

        Type(Value value, String string) {
            this.value = value;
            this.string = string;
        }

        public Value getEnumValue() {
            return value;
        }

        @java.lang.Override
        @JsonValue
        public String toString() {
            return this.string;
        }

        @java.lang.Override
        public boolean equals(Object other) {
            return (this == other) || (other instanceof Type && this.string.equals(((Type) other).string));
        }

        @java.lang.Override
        public int hashCode() {
            return this.string.hashCode();
        }

        public <T> T visit(Visitor<T> visitor) {
            switch (value) {
                case ALTERNATE_PATH:
                    return visitor.visitAlternatePath();
                case PARALLEL_PATH:
                    return visitor.visitParallelPath();
                case OUTGOING:
                    return visitor.visitOutgoing();
                case SUBFLOW:
                    return visitor.visitSubflow();
                case INFORMATION:
                    return visitor.visitInformation();
                case SELF_ACTION:
                    return visitor.visitSelfAction();
                case REPLY:
                    return visitor.visitReply();
                case INTRODUCTION:
                    return visitor.visitIntroduction();
                case CONCLUSION:
                    return visitor.visitConclusion();
                case UNKNOWN:
                default:
                    return visitor.visitUnknown(string);
            }
        }

        @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
        public static Type valueOf(String value) {
            switch (value) {
                case "alternate-path":
                    return ALTERNATE_PATH;
                case "parallel-path":
                    return PARALLEL_PATH;
                case "outgoing":
                    return OUTGOING;
                case "subflow":
                    return SUBFLOW;
                case "information":
                    return INFORMATION;
                case "self-action":
                    return SELF_ACTION;
                case "reply":
                    return REPLY;
                case "introduction":
                    return INTRODUCTION;
                case "conclusion":
                    return CONCLUSION;
                default:
                    return new Type(Value.UNKNOWN, value);
            }
        }

        public enum Value {
            ALTERNATE_PATH,

            SUBFLOW,

            OUTGOING,

            PARALLEL_PATH,

            REPLY,

            SELF_ACTION,

            INTRODUCTION,

            INFORMATION,

            CONCLUSION,

            UNKNOWN
        }

        public interface Visitor<T> {
            T visitAlternatePath();

            T visitSubflow();

            T visitOutgoing();

            T visitParallelPath();

            T visitReply();

            T visitSelfAction();

            T visitIntroduction();

            T visitInformation();

            T visitConclusion();

            T visitUnknown(String unknownType);
        }
    }
}
