/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.icepanel.core.ObjectMappers;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ModelConnectionFilter.Builder.class)
public final class ModelConnectionFilter {
    private final Optional<ModelConnectionDirection> direction;

    private final Optional<HandleId> handleId;

    private final Optional<Map<String, String>> labels;

    private final Optional<Boolean> linked;

    private final Optional<String> name;

    private final Optional<OriginId> originId;

    private final Optional<Status> status;

    private final Optional<TagIds> tagIds;

    private final Optional<TargetId> targetId;

    private final Optional<TechnologyIds> technologyIds;

    private final Optional<ViaId> viaId;

    private final Map<String, Object> additionalProperties;

    private ModelConnectionFilter(
            Optional<ModelConnectionDirection> direction,
            Optional<HandleId> handleId,
            Optional<Map<String, String>> labels,
            Optional<Boolean> linked,
            Optional<String> name,
            Optional<OriginId> originId,
            Optional<Status> status,
            Optional<TagIds> tagIds,
            Optional<TargetId> targetId,
            Optional<TechnologyIds> technologyIds,
            Optional<ViaId> viaId,
            Map<String, Object> additionalProperties) {
        this.direction = direction;
        this.handleId = handleId;
        this.labels = labels;
        this.linked = linked;
        this.name = name;
        this.originId = originId;
        this.status = status;
        this.tagIds = tagIds;
        this.targetId = targetId;
        this.technologyIds = technologyIds;
        this.viaId = viaId;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("direction")
    public Optional<ModelConnectionDirection> getDirection() {
        return direction;
    }

    @JsonProperty("handleId")
    public Optional<HandleId> getHandleId() {
        return handleId;
    }

    @JsonProperty("labels")
    public Optional<Map<String, String>> getLabels() {
        return labels;
    }

    @JsonProperty("linked")
    public Optional<Boolean> getLinked() {
        return linked;
    }

    @JsonProperty("name")
    public Optional<String> getName() {
        return name;
    }

    @JsonProperty("originId")
    public Optional<OriginId> getOriginId() {
        return originId;
    }

    @JsonProperty("status")
    public Optional<Status> getStatus() {
        return status;
    }

    @JsonProperty("tagIds")
    public Optional<TagIds> getTagIds() {
        return tagIds;
    }

    @JsonProperty("targetId")
    public Optional<TargetId> getTargetId() {
        return targetId;
    }

    @JsonProperty("technologyIds")
    public Optional<TechnologyIds> getTechnologyIds() {
        return technologyIds;
    }

    @JsonProperty("viaId")
    public Optional<ViaId> getViaId() {
        return viaId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ModelConnectionFilter && equalTo((ModelConnectionFilter) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ModelConnectionFilter other) {
        return direction.equals(other.direction)
                && handleId.equals(other.handleId)
                && labels.equals(other.labels)
                && linked.equals(other.linked)
                && name.equals(other.name)
                && originId.equals(other.originId)
                && status.equals(other.status)
                && tagIds.equals(other.tagIds)
                && targetId.equals(other.targetId)
                && technologyIds.equals(other.technologyIds)
                && viaId.equals(other.viaId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.direction,
                this.handleId,
                this.labels,
                this.linked,
                this.name,
                this.originId,
                this.status,
                this.tagIds,
                this.targetId,
                this.technologyIds,
                this.viaId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<ModelConnectionDirection> direction = Optional.empty();

        private Optional<HandleId> handleId = Optional.empty();

        private Optional<Map<String, String>> labels = Optional.empty();

        private Optional<Boolean> linked = Optional.empty();

        private Optional<String> name = Optional.empty();

        private Optional<OriginId> originId = Optional.empty();

        private Optional<Status> status = Optional.empty();

        private Optional<TagIds> tagIds = Optional.empty();

        private Optional<TargetId> targetId = Optional.empty();

        private Optional<TechnologyIds> technologyIds = Optional.empty();

        private Optional<ViaId> viaId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ModelConnectionFilter other) {
            direction(other.getDirection());
            handleId(other.getHandleId());
            labels(other.getLabels());
            linked(other.getLinked());
            name(other.getName());
            originId(other.getOriginId());
            status(other.getStatus());
            tagIds(other.getTagIds());
            targetId(other.getTargetId());
            technologyIds(other.getTechnologyIds());
            viaId(other.getViaId());
            return this;
        }

        @JsonSetter(value = "direction", nulls = Nulls.SKIP)
        public Builder direction(Optional<ModelConnectionDirection> direction) {
            this.direction = direction;
            return this;
        }

        public Builder direction(ModelConnectionDirection direction) {
            this.direction = Optional.ofNullable(direction);
            return this;
        }

        @JsonSetter(value = "handleId", nulls = Nulls.SKIP)
        public Builder handleId(Optional<HandleId> handleId) {
            this.handleId = handleId;
            return this;
        }

        public Builder handleId(HandleId handleId) {
            this.handleId = Optional.ofNullable(handleId);
            return this;
        }

        @JsonSetter(value = "labels", nulls = Nulls.SKIP)
        public Builder labels(Optional<Map<String, String>> labels) {
            this.labels = labels;
            return this;
        }

        public Builder labels(Map<String, String> labels) {
            this.labels = Optional.ofNullable(labels);
            return this;
        }

        @JsonSetter(value = "linked", nulls = Nulls.SKIP)
        public Builder linked(Optional<Boolean> linked) {
            this.linked = linked;
            return this;
        }

        public Builder linked(Boolean linked) {
            this.linked = Optional.ofNullable(linked);
            return this;
        }

        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public Builder name(Optional<String> name) {
            this.name = name;
            return this;
        }

        public Builder name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        @JsonSetter(value = "originId", nulls = Nulls.SKIP)
        public Builder originId(Optional<OriginId> originId) {
            this.originId = originId;
            return this;
        }

        public Builder originId(OriginId originId) {
            this.originId = Optional.ofNullable(originId);
            return this;
        }

        @JsonSetter(value = "status", nulls = Nulls.SKIP)
        public Builder status(Optional<Status> status) {
            this.status = status;
            return this;
        }

        public Builder status(Status status) {
            this.status = Optional.ofNullable(status);
            return this;
        }

        @JsonSetter(value = "tagIds", nulls = Nulls.SKIP)
        public Builder tagIds(Optional<TagIds> tagIds) {
            this.tagIds = tagIds;
            return this;
        }

        public Builder tagIds(TagIds tagIds) {
            this.tagIds = Optional.ofNullable(tagIds);
            return this;
        }

        @JsonSetter(value = "targetId", nulls = Nulls.SKIP)
        public Builder targetId(Optional<TargetId> targetId) {
            this.targetId = targetId;
            return this;
        }

        public Builder targetId(TargetId targetId) {
            this.targetId = Optional.ofNullable(targetId);
            return this;
        }

        @JsonSetter(value = "technologyIds", nulls = Nulls.SKIP)
        public Builder technologyIds(Optional<TechnologyIds> technologyIds) {
            this.technologyIds = technologyIds;
            return this;
        }

        public Builder technologyIds(TechnologyIds technologyIds) {
            this.technologyIds = Optional.ofNullable(technologyIds);
            return this;
        }

        @JsonSetter(value = "viaId", nulls = Nulls.SKIP)
        public Builder viaId(Optional<ViaId> viaId) {
            this.viaId = viaId;
            return this;
        }

        public Builder viaId(ViaId viaId) {
            this.viaId = Optional.ofNullable(viaId);
            return this;
        }

        public ModelConnectionFilter build() {
            return new ModelConnectionFilter(
                    direction,
                    handleId,
                    labels,
                    linked,
                    name,
                    originId,
                    status,
                    tagIds,
                    targetId,
                    technologyIds,
                    viaId,
                    additionalProperties);
        }
    }

    @JsonDeserialize(using = TechnologyIds.Deserializer.class)
    public static final class TechnologyIds {
        private final Object value;

        private final int type;

        private TechnologyIds(Object value, int type) {
            this.value = value;
            this.type = type;
        }

        @JsonValue
        public Object get() {
            return this.value;
        }

        @SuppressWarnings("unchecked")
        public <T> T visit(Visitor<T> visitor) {
            if (this.type == 0) {
                return visitor.visit((String) this.value);
            } else if (this.type == 1) {
                return visitor.visit((List<String>) this.value);
            }
            throw new IllegalStateException("Failed to visit value. This should never happen.");
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof TechnologyIds && equalTo((TechnologyIds) other);
        }

        private boolean equalTo(TechnologyIds other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return this.value.toString();
        }

        public static TechnologyIds of(String value) {
            return new TechnologyIds(value, 0);
        }

        public static TechnologyIds of(List<String> value) {
            return new TechnologyIds(value, 1);
        }

        public interface Visitor<T> {
            T visit(String value);

            T visit(List<String> value);
        }

        static final class Deserializer extends StdDeserializer<TechnologyIds> {
            Deserializer() {
                super(TechnologyIds.class);
            }

            @java.lang.Override
            public TechnologyIds deserialize(JsonParser p, DeserializationContext context) throws IOException {
                Object value = p.readValueAs(Object.class);
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(value, String.class));
                } catch (RuntimeException e) {
                }
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(value, new TypeReference<List<String>>() {}));
                } catch (RuntimeException e) {
                }
                throw new JsonParseException(p, "Failed to deserialize");
            }
        }
    }

    @JsonDeserialize(using = Status.Deserializer.class)
    public static final class Status {
        private final Object value;

        private final int type;

        private Status(Object value, int type) {
            this.value = value;
            this.type = type;
        }

        @JsonValue
        public Object get() {
            return this.value;
        }

        @SuppressWarnings("unchecked")
        public <T> T visit(Visitor<T> visitor) {
            if (this.type == 0) {
                return visitor.visit((ModelConnectionStatus) this.value);
            } else if (this.type == 1) {
                return visitor.visit((List<ModelConnectionStatus>) this.value);
            }
            throw new IllegalStateException("Failed to visit value. This should never happen.");
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof Status && equalTo((Status) other);
        }

        private boolean equalTo(Status other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return this.value.toString();
        }

        public static Status of(ModelConnectionStatus value) {
            return new Status(value, 0);
        }

        public static Status of(List<ModelConnectionStatus> value) {
            return new Status(value, 1);
        }

        public interface Visitor<T> {
            T visit(ModelConnectionStatus value);

            T visit(List<ModelConnectionStatus> value);
        }

        static final class Deserializer extends StdDeserializer<Status> {
            Deserializer() {
                super(Status.class);
            }

            @java.lang.Override
            public Status deserialize(JsonParser p, DeserializationContext context) throws IOException {
                Object value = p.readValueAs(Object.class);
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(value, ModelConnectionStatus.class));
                } catch (RuntimeException e) {
                }
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(
                            value, new TypeReference<List<ModelConnectionStatus>>() {}));
                } catch (RuntimeException e) {
                }
                throw new JsonParseException(p, "Failed to deserialize");
            }
        }
    }

    @JsonDeserialize(using = OriginId.Deserializer.class)
    public static final class OriginId {
        private final Object value;

        private final int type;

        private OriginId(Object value, int type) {
            this.value = value;
            this.type = type;
        }

        @JsonValue
        public Object get() {
            return this.value;
        }

        @SuppressWarnings("unchecked")
        public <T> T visit(Visitor<T> visitor) {
            if (this.type == 0) {
                return visitor.visit((String) this.value);
            } else if (this.type == 1) {
                return visitor.visit((List<String>) this.value);
            }
            throw new IllegalStateException("Failed to visit value. This should never happen.");
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof OriginId && equalTo((OriginId) other);
        }

        private boolean equalTo(OriginId other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return this.value.toString();
        }

        public static OriginId of(String value) {
            return new OriginId(value, 0);
        }

        public static OriginId of(List<String> value) {
            return new OriginId(value, 1);
        }

        public interface Visitor<T> {
            T visit(String value);

            T visit(List<String> value);
        }

        static final class Deserializer extends StdDeserializer<OriginId> {
            Deserializer() {
                super(OriginId.class);
            }

            @java.lang.Override
            public OriginId deserialize(JsonParser p, DeserializationContext context) throws IOException {
                Object value = p.readValueAs(Object.class);
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(value, String.class));
                } catch (RuntimeException e) {
                }
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(value, new TypeReference<List<String>>() {}));
                } catch (RuntimeException e) {
                }
                throw new JsonParseException(p, "Failed to deserialize");
            }
        }
    }

    @JsonDeserialize(using = ViaId.Deserializer.class)
    public static final class ViaId {
        private final Object value;

        private final int type;

        private ViaId(Object value, int type) {
            this.value = value;
            this.type = type;
        }

        @JsonValue
        public Object get() {
            return this.value;
        }

        @SuppressWarnings("unchecked")
        public <T> T visit(Visitor<T> visitor) {
            if (this.type == 0) {
                return visitor.visit((String) this.value);
            } else if (this.type == 1) {
                return visitor.visit((List<String>) this.value);
            }
            throw new IllegalStateException("Failed to visit value. This should never happen.");
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof ViaId && equalTo((ViaId) other);
        }

        private boolean equalTo(ViaId other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return this.value.toString();
        }

        public static ViaId of(String value) {
            return new ViaId(value, 0);
        }

        public static ViaId of(List<String> value) {
            return new ViaId(value, 1);
        }

        public interface Visitor<T> {
            T visit(String value);

            T visit(List<String> value);
        }

        static final class Deserializer extends StdDeserializer<ViaId> {
            Deserializer() {
                super(ViaId.class);
            }

            @java.lang.Override
            public ViaId deserialize(JsonParser p, DeserializationContext context) throws IOException {
                Object value = p.readValueAs(Object.class);
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(value, String.class));
                } catch (RuntimeException e) {
                }
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(value, new TypeReference<List<String>>() {}));
                } catch (RuntimeException e) {
                }
                throw new JsonParseException(p, "Failed to deserialize");
            }
        }
    }

    @JsonDeserialize(using = HandleId.Deserializer.class)
    public static final class HandleId {
        private final Object value;

        private final int type;

        private HandleId(Object value, int type) {
            this.value = value;
            this.type = type;
        }

        @JsonValue
        public Object get() {
            return this.value;
        }

        @SuppressWarnings("unchecked")
        public <T> T visit(Visitor<T> visitor) {
            if (this.type == 0) {
                return visitor.visit((String) this.value);
            } else if (this.type == 1) {
                return visitor.visit((List<String>) this.value);
            }
            throw new IllegalStateException("Failed to visit value. This should never happen.");
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof HandleId && equalTo((HandleId) other);
        }

        private boolean equalTo(HandleId other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return this.value.toString();
        }

        public static HandleId of(String value) {
            return new HandleId(value, 0);
        }

        public static HandleId of(List<String> value) {
            return new HandleId(value, 1);
        }

        public interface Visitor<T> {
            T visit(String value);

            T visit(List<String> value);
        }

        static final class Deserializer extends StdDeserializer<HandleId> {
            Deserializer() {
                super(HandleId.class);
            }

            @java.lang.Override
            public HandleId deserialize(JsonParser p, DeserializationContext context) throws IOException {
                Object value = p.readValueAs(Object.class);
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(value, String.class));
                } catch (RuntimeException e) {
                }
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(value, new TypeReference<List<String>>() {}));
                } catch (RuntimeException e) {
                }
                throw new JsonParseException(p, "Failed to deserialize");
            }
        }
    }

    @JsonDeserialize(using = TagIds.Deserializer.class)
    public static final class TagIds {
        private final Object value;

        private final int type;

        private TagIds(Object value, int type) {
            this.value = value;
            this.type = type;
        }

        @JsonValue
        public Object get() {
            return this.value;
        }

        @SuppressWarnings("unchecked")
        public <T> T visit(Visitor<T> visitor) {
            if (this.type == 0) {
                return visitor.visit((String) this.value);
            } else if (this.type == 1) {
                return visitor.visit((List<String>) this.value);
            }
            throw new IllegalStateException("Failed to visit value. This should never happen.");
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof TagIds && equalTo((TagIds) other);
        }

        private boolean equalTo(TagIds other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return this.value.toString();
        }

        public static TagIds of(String value) {
            return new TagIds(value, 0);
        }

        public static TagIds of(List<String> value) {
            return new TagIds(value, 1);
        }

        public interface Visitor<T> {
            T visit(String value);

            T visit(List<String> value);
        }

        static final class Deserializer extends StdDeserializer<TagIds> {
            Deserializer() {
                super(TagIds.class);
            }

            @java.lang.Override
            public TagIds deserialize(JsonParser p, DeserializationContext context) throws IOException {
                Object value = p.readValueAs(Object.class);
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(value, String.class));
                } catch (RuntimeException e) {
                }
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(value, new TypeReference<List<String>>() {}));
                } catch (RuntimeException e) {
                }
                throw new JsonParseException(p, "Failed to deserialize");
            }
        }
    }

    @JsonDeserialize(using = TargetId.Deserializer.class)
    public static final class TargetId {
        private final Object value;

        private final int type;

        private TargetId(Object value, int type) {
            this.value = value;
            this.type = type;
        }

        @JsonValue
        public Object get() {
            return this.value;
        }

        @SuppressWarnings("unchecked")
        public <T> T visit(Visitor<T> visitor) {
            if (this.type == 0) {
                return visitor.visit((String) this.value);
            } else if (this.type == 1) {
                return visitor.visit((List<String>) this.value);
            }
            throw new IllegalStateException("Failed to visit value. This should never happen.");
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof TargetId && equalTo((TargetId) other);
        }

        private boolean equalTo(TargetId other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return this.value.toString();
        }

        public static TargetId of(String value) {
            return new TargetId(value, 0);
        }

        public static TargetId of(List<String> value) {
            return new TargetId(value, 1);
        }

        public interface Visitor<T> {
            T visit(String value);

            T visit(List<String> value);
        }

        static final class Deserializer extends StdDeserializer<TargetId> {
            Deserializer() {
                super(TargetId.class);
            }

            @java.lang.Override
            public TargetId deserialize(JsonParser p, DeserializationContext context) throws IOException {
                Object value = p.readValueAs(Object.class);
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(value, String.class));
                } catch (RuntimeException e) {
                }
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(value, new TypeReference<List<String>>() {}));
                } catch (RuntimeException e) {
                }
                throw new JsonParseException(p, "Failed to deserialize");
            }
        }
    }
}
