/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.icepanel.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = OrganizationLogStatsListByType.Builder.class)
public final class OrganizationLogStatsListByType {
    private final Map<String, ActionLogStatsContributor> contributors;

    private final List<OrganizationLogStatsDateByType> dates;

    private final double totalCount;

    private final Map<String, Object> additionalProperties;

    private OrganizationLogStatsListByType(
            Map<String, ActionLogStatsContributor> contributors,
            List<OrganizationLogStatsDateByType> dates,
            double totalCount,
            Map<String, Object> additionalProperties) {
        this.contributors = contributors;
        this.dates = dates;
        this.totalCount = totalCount;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("contributors")
    public Map<String, ActionLogStatsContributor> getContributors() {
        return contributors;
    }

    @JsonProperty("dates")
    public List<OrganizationLogStatsDateByType> getDates() {
        return dates;
    }

    @JsonProperty("totalCount")
    public double getTotalCount() {
        return totalCount;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof OrganizationLogStatsListByType && equalTo((OrganizationLogStatsListByType) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(OrganizationLogStatsListByType other) {
        return contributors.equals(other.contributors) && dates.equals(other.dates) && totalCount == other.totalCount;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.contributors, this.dates, this.totalCount);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TotalCountStage builder() {
        return new Builder();
    }

    public interface TotalCountStage {
        _FinalStage totalCount(double totalCount);

        Builder from(OrganizationLogStatsListByType other);
    }

    public interface _FinalStage {
        OrganizationLogStatsListByType build();

        _FinalStage contributors(Map<String, ActionLogStatsContributor> contributors);

        _FinalStage putAllContributors(Map<String, ActionLogStatsContributor> contributors);

        _FinalStage contributors(String key, ActionLogStatsContributor value);

        _FinalStage dates(List<OrganizationLogStatsDateByType> dates);

        _FinalStage addDates(OrganizationLogStatsDateByType dates);

        _FinalStage addAllDates(List<OrganizationLogStatsDateByType> dates);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TotalCountStage, _FinalStage {
        private double totalCount;

        private List<OrganizationLogStatsDateByType> dates = new ArrayList<>();

        private Map<String, ActionLogStatsContributor> contributors = new LinkedHashMap<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(OrganizationLogStatsListByType other) {
            contributors(other.getContributors());
            dates(other.getDates());
            totalCount(other.getTotalCount());
            return this;
        }

        @java.lang.Override
        @JsonSetter("totalCount")
        public _FinalStage totalCount(double totalCount) {
            this.totalCount = totalCount;
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllDates(List<OrganizationLogStatsDateByType> dates) {
            if (dates != null) {
                this.dates.addAll(dates);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addDates(OrganizationLogStatsDateByType dates) {
            this.dates.add(dates);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "dates", nulls = Nulls.SKIP)
        public _FinalStage dates(List<OrganizationLogStatsDateByType> dates) {
            this.dates.clear();
            if (dates != null) {
                this.dates.addAll(dates);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage contributors(String key, ActionLogStatsContributor value) {
            this.contributors.put(key, value);
            return this;
        }

        @java.lang.Override
        public _FinalStage putAllContributors(Map<String, ActionLogStatsContributor> contributors) {
            if (contributors != null) {
                this.contributors.putAll(contributors);
            }
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "contributors", nulls = Nulls.SKIP)
        public _FinalStage contributors(Map<String, ActionLogStatsContributor> contributors) {
            this.contributors.clear();
            if (contributors != null) {
                this.contributors.putAll(contributors);
            }
            return this;
        }

        @java.lang.Override
        public OrganizationLogStatsListByType build() {
            return new OrganizationLogStatsListByType(contributors, dates, totalCount, additionalProperties);
        }
    }
}
