/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.icepanel.core.Nullable;
import com.icepanel.core.NullableNonemptyFilter;
import com.icepanel.core.ObjectMappers;
import com.icepanel.core.OptionalNullable;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = VersionPartial.Builder.class)
public final class VersionPartial {
    private final OptionalNullable<String> modelHandleId;

    private final Optional<String> name;

    private final Optional<String> notes;

    private final Map<String, Object> additionalProperties;

    private VersionPartial(
            OptionalNullable<String> modelHandleId,
            Optional<String> name,
            Optional<String> notes,
            Map<String, Object> additionalProperties) {
        this.modelHandleId = modelHandleId;
        this.name = name;
        this.notes = notes;
        this.additionalProperties = additionalProperties;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("modelHandleId")
    public OptionalNullable<String> getModelHandleId() {
        if (modelHandleId == null) {
            return OptionalNullable.absent();
        }
        return modelHandleId;
    }

    @JsonProperty("name")
    public Optional<String> getName() {
        return name;
    }

    @JsonProperty("notes")
    public Optional<String> getNotes() {
        return notes;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("modelHandleId")
    private OptionalNullable<String> _getModelHandleId() {
        return modelHandleId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof VersionPartial && equalTo((VersionPartial) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(VersionPartial other) {
        return modelHandleId.equals(other.modelHandleId) && name.equals(other.name) && notes.equals(other.notes);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.modelHandleId, this.name, this.notes);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private OptionalNullable<String> modelHandleId = OptionalNullable.absent();

        private Optional<String> name = Optional.empty();

        private Optional<String> notes = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(VersionPartial other) {
            modelHandleId(other.getModelHandleId());
            name(other.getName());
            notes(other.getNotes());
            return this;
        }

        @JsonSetter(value = "modelHandleId", nulls = Nulls.SKIP)
        public Builder modelHandleId(OptionalNullable<String> modelHandleId) {
            this.modelHandleId = modelHandleId;
            return this;
        }

        public Builder modelHandleId(String modelHandleId) {
            this.modelHandleId = OptionalNullable.of(modelHandleId);
            return this;
        }

        public Builder modelHandleId(Optional<String> modelHandleId) {
            if (modelHandleId.isPresent()) {
                this.modelHandleId = OptionalNullable.of(modelHandleId.get());
            } else {
                this.modelHandleId = OptionalNullable.absent();
            }
            return this;
        }

        public Builder modelHandleId(Nullable<String> modelHandleId) {
            if (modelHandleId.isNull()) {
                this.modelHandleId = OptionalNullable.ofNull();
            } else if (modelHandleId.isEmpty()) {
                this.modelHandleId = OptionalNullable.absent();
            } else {
                this.modelHandleId = OptionalNullable.of(modelHandleId.get());
            }
            return this;
        }

        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public Builder name(Optional<String> name) {
            this.name = name;
            return this;
        }

        public Builder name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        @JsonSetter(value = "notes", nulls = Nulls.SKIP)
        public Builder notes(Optional<String> notes) {
            this.notes = notes;
            return this;
        }

        public Builder notes(String notes) {
            this.notes = Optional.ofNullable(notes);
            return this;
        }

        public VersionPartial build() {
            return new VersionPartial(modelHandleId, name, notes, additionalProperties);
        }
    }
}
