/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.icepanel.api.resources.organizations.logs;

import com.icepanel.api.core.ClientOptions;
import com.icepanel.api.core.RequestOptions;
import com.icepanel.api.core.Suppliers;
import com.icepanel.api.resources.organizations.logs.requests.OrganizationLogFindRequest;
import com.icepanel.api.resources.organizations.logs.requests.OrganizationLogsListRequest;
import com.icepanel.api.resources.organizations.logs.stats.AsyncStatsClient;
import com.icepanel.api.resources.organizations.logs.types.LogsGetResponse;
import com.icepanel.api.resources.organizations.logs.types.LogsListResponse;
import java.util.concurrent.CompletableFuture;
import java.util.function.Supplier;

public class AsyncLogsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawLogsClient rawClient;

    protected final Supplier<AsyncStatsClient> statsClient;

    public AsyncLogsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawLogsClient(clientOptions);
        this.statsClient = Suppliers.memoize(() -> new AsyncStatsClient(clientOptions));
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawLogsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * List organization logs (only available on the scale plan and above)
     */
    public CompletableFuture<LogsListResponse> list(String organizationId) {
        return this.rawClient.list(organizationId).thenApply(response -> response.body());
    }

    /**
     * List organization logs (only available on the scale plan and above)
     */
    public CompletableFuture<LogsListResponse> list(String organizationId, OrganizationLogsListRequest request) {
        return this.rawClient.list(organizationId, request).thenApply(response -> response.body());
    }

    /**
     * List organization logs (only available on the scale plan and above)
     */
    public CompletableFuture<LogsListResponse> list(
            String organizationId, OrganizationLogsListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(organizationId, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Find an organization log (only available on the scale plan and above)
     */
    public CompletableFuture<LogsGetResponse> get(String organizationId, String organizationLogId) {
        return this.rawClient.get(organizationId, organizationLogId).thenApply(response -> response.body());
    }

    /**
     * Find an organization log (only available on the scale plan and above)
     */
    public CompletableFuture<LogsGetResponse> get(
            String organizationId, String organizationLogId, OrganizationLogFindRequest request) {
        return this.rawClient.get(organizationId, organizationLogId, request).thenApply(response -> response.body());
    }

    /**
     * Find an organization log (only available on the scale plan and above)
     */
    public CompletableFuture<LogsGetResponse> get(
            String organizationId,
            String organizationLogId,
            OrganizationLogFindRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .get(organizationId, organizationLogId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public AsyncStatsClient stats() {
        return this.statsClient.get();
    }
}
